/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.memberships;

import com.whop.api.core.ClientOptions;
import com.whop.api.core.RequestOptions;
import com.whop.api.core.pagination.SyncPagingIterable;
import com.whop.api.resources.memberships.requests.AddFreeDaysMembershipRequest;
import com.whop.api.resources.memberships.requests.CancelMembershipsRequest;
import com.whop.api.resources.memberships.requests.ExtendMembershipsRequest;
import com.whop.api.resources.memberships.requests.ListMembershipsRequest;
import com.whop.api.resources.memberships.requests.PauseMembershipsRequest;
import com.whop.api.resources.memberships.requests.ResumeMembershipsRequest;
import com.whop.api.resources.memberships.requests.ResyncAccessMembershipRequest;
import com.whop.api.resources.memberships.requests.RetrieveMembershipsRequest;
import com.whop.api.resources.memberships.requests.TransferMembershipsRequest;
import com.whop.api.resources.memberships.requests.UncancelMembershipRequest;
import com.whop.api.resources.memberships.requests.UpdateMembershipsRequest;
import com.whop.api.resources.memberships.types.InviteMembershipsRequestBody;
import com.whop.api.resources.memberships.types.InviteMembershipsResponse;
import com.whop.api.resources.memberships.types.TransferMembershipsResponse;
import com.whop.api.types.Membership;
import java.util.concurrent.CompletableFuture;

public class AsyncMembershipsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawMembershipsClient rawClient;

    public AsyncMembershipsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawMembershipsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawMembershipsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Lists every membership the caller can read: an account API key its account's; a user credential their own plus those of every account they manage. <code>account_id</code> and <code>user_id</code> only narrow that list — values outside the caller's reach return fewer results, not an error.
     */
    public CompletableFuture<SyncPagingIterable<Membership>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Lists every membership the caller can read: an account API key its account's; a user credential their own plus those of every account they manage. <code>account_id</code> and <code>user_id</code> only narrow that list — values outside the caller's reach return fewer results, not an error.
     */
    public CompletableFuture<SyncPagingIterable<Membership>> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Lists every membership the caller can read: an account API key its account's; a user credential their own plus those of every account they manage. <code>account_id</code> and <code>user_id</code> only narrow that list — values outside the caller's reach return fewer results, not an error.
     */
    public CompletableFuture<SyncPagingIterable<Membership>> list(ListMembershipsRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Lists every membership the caller can read: an account API key its account's; a user credential their own plus those of every account they manage. <code>account_id</code> and <code>user_id</code> only narrow that list — values outside the caller's reach return fewer results, not an error.
     */
    public CompletableFuture<SyncPagingIterable<Membership>> list(
            ListMembershipsRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Sends an email inviting one recipient to join the account through a free plan. Identify the recipient by exactly one of <code>user_id</code> or <code>email</code>. The invitation is bound to that recipient; after signing in, accepting it immediately grants the membership without checkout. This Experimental endpoint is available only to accounts enabled for membership invitations.
     */
    public CompletableFuture<InviteMembershipsResponse> invite(InviteMembershipsRequestBody request) {
        return this.rawClient.invite(request).thenApply(response -> response.body());
    }

    /**
     * Sends an email inviting one recipient to join the account through a free plan. Identify the recipient by exactly one of <code>user_id</code> or <code>email</code>. The invitation is bound to that recipient; after signing in, accepting it immediately grants the membership without checkout. This Experimental endpoint is available only to accounts enabled for membership invitations.
     */
    public CompletableFuture<InviteMembershipsResponse> invite(
            InviteMembershipsRequestBody request, RequestOptions requestOptions) {
        return this.rawClient.invite(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves a membership by ID or license key. Accessible to the account and to the membership's own user.
     */
    public CompletableFuture<Membership> retrieve(String id) {
        return this.rawClient.retrieve(id).thenApply(response -> response.body());
    }

    /**
     * Retrieves a membership by ID or license key. Accessible to the account and to the membership's own user.
     */
    public CompletableFuture<Membership> retrieve(String id, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves a membership by ID or license key. Accessible to the account and to the membership's own user.
     */
    public CompletableFuture<Membership> retrieve(String id, RetrieveMembershipsRequest request) {
        return this.rawClient.retrieve(id, request).thenApply(response -> response.body());
    }

    /**
     * Retrieves a membership by ID or license key. Accessible to the account and to the membership's own user.
     */
    public CompletableFuture<Membership> retrieve(
            String id, RetrieveMembershipsRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Updates a membership: merge metadata key-value pairs, or toggle <code>cancel_at_period_end</code> — <code>true</code> schedules the cancellation for the end of the current billing period, <code>false</code> reverses a pending one.
     */
    public CompletableFuture<Membership> update(String id) {
        return this.rawClient.update(id).thenApply(response -> response.body());
    }

    /**
     * Updates a membership: merge metadata key-value pairs, or toggle <code>cancel_at_period_end</code> — <code>true</code> schedules the cancellation for the end of the current billing period, <code>false</code> reverses a pending one.
     */
    public CompletableFuture<Membership> update(String id, RequestOptions requestOptions) {
        return this.rawClient.update(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Updates a membership: merge metadata key-value pairs, or toggle <code>cancel_at_period_end</code> — <code>true</code> schedules the cancellation for the end of the current billing period, <code>false</code> reverses a pending one.
     */
    public CompletableFuture<Membership> update(String id, UpdateMembershipsRequest request) {
        return this.rawClient.update(id, request).thenApply(response -> response.body());
    }

    /**
     * Updates a membership: merge metadata key-value pairs, or toggle <code>cancel_at_period_end</code> — <code>true</code> schedules the cancellation for the end of the current billing period, <code>false</code> reverses a pending one.
     */
    public CompletableFuture<Membership> update(
            String id, UpdateMembershipsRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Add free days to extend a membership's current billing period, expiration date, or Stripe trial.
     * <p>Required permissions:</p>
     * <ul>
     * <li><code>member:manage</code></li>
     * <li><code>member:email:read</code></li>
     * <li><code>member:basic:read</code></li>
     * </ul>
     */
    public CompletableFuture<Membership> addFreeDaysMembership(String id, AddFreeDaysMembershipRequest request) {
        return this.rawClient.addFreeDaysMembership(id, request).thenApply(response -> response.body());
    }

    /**
     * Add free days to extend a membership's current billing period, expiration date, or Stripe trial.
     * <p>Required permissions:</p>
     * <ul>
     * <li><code>member:manage</code></li>
     * <li><code>member:email:read</code></li>
     * <li><code>member:basic:read</code></li>
     * </ul>
     */
    public CompletableFuture<Membership> addFreeDaysMembership(
            String id, AddFreeDaysMembershipRequest request, RequestOptions requestOptions) {
        return this.rawClient.addFreeDaysMembership(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Cancels a membership. Pass <code>cancel_at_period_end: true</code> to stop auto-renewal and keep access until the current billing period ends. Omit it (or pass <code>false</code>) to revoke access immediately. Buyers cannot cancel buy-now-pay-later (<code>splitit</code>, <code>sezzle</code>) or non-trial split-pay memberships.
     */
    public CompletableFuture<Membership> cancel(String id) {
        return this.rawClient.cancel(id).thenApply(response -> response.body());
    }

    /**
     * Cancels a membership. Pass <code>cancel_at_period_end: true</code> to stop auto-renewal and keep access until the current billing period ends. Omit it (or pass <code>false</code>) to revoke access immediately. Buyers cannot cancel buy-now-pay-later (<code>splitit</code>, <code>sezzle</code>) or non-trial split-pay memberships.
     */
    public CompletableFuture<Membership> cancel(String id, RequestOptions requestOptions) {
        return this.rawClient.cancel(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Cancels a membership. Pass <code>cancel_at_period_end: true</code> to stop auto-renewal and keep access until the current billing period ends. Omit it (or pass <code>false</code>) to revoke access immediately. Buyers cannot cancel buy-now-pay-later (<code>splitit</code>, <code>sezzle</code>) or non-trial split-pay memberships.
     */
    public CompletableFuture<Membership> cancel(String id, CancelMembershipsRequest request) {
        return this.rawClient.cancel(id, request).thenApply(response -> response.body());
    }

    /**
     * Cancels a membership. Pass <code>cancel_at_period_end: true</code> to stop auto-renewal and keep access until the current billing period ends. Omit it (or pass <code>false</code>) to revoke access immediately. Buyers cannot cancel buy-now-pay-later (<code>splitit</code>, <code>sezzle</code>) or non-trial split-pay memberships.
     */
    public CompletableFuture<Membership> cancel(
            String id, CancelMembershipsRequest request, RequestOptions requestOptions) {
        return this.rawClient.cancel(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Adds free days to a membership, extending its current billing period, expiration date, or trial depending on the plan type.
     */
    public CompletableFuture<Membership> extend(String id, ExtendMembershipsRequest request) {
        return this.rawClient.extend(id, request).thenApply(response -> response.body());
    }

    /**
     * Adds free days to a membership, extending its current billing period, expiration date, or trial depending on the plan type.
     */
    public CompletableFuture<Membership> extend(
            String id, ExtendMembershipsRequest request, RequestOptions requestOptions) {
        return this.rawClient.extend(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Pauses a membership's recurring payment collection. The customer keeps access but is not charged until the membership is resumed.
     */
    public CompletableFuture<Membership> pause(String id) {
        return this.rawClient.pause(id).thenApply(response -> response.body());
    }

    /**
     * Pauses a membership's recurring payment collection. The customer keeps access but is not charged until the membership is resumed.
     */
    public CompletableFuture<Membership> pause(String id, RequestOptions requestOptions) {
        return this.rawClient.pause(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Pauses a membership's recurring payment collection. The customer keeps access but is not charged until the membership is resumed.
     */
    public CompletableFuture<Membership> pause(String id, PauseMembershipsRequest request) {
        return this.rawClient.pause(id, request).thenApply(response -> response.body());
    }

    /**
     * Pauses a membership's recurring payment collection. The customer keeps access but is not charged until the membership is resumed.
     */
    public CompletableFuture<Membership> pause(
            String id, PauseMembershipsRequest request, RequestOptions requestOptions) {
        return this.rawClient.pause(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Resumes a previously paused membership's recurring payment collection. Billing resumes on the next cycle.
     */
    public CompletableFuture<Membership> resume(String id) {
        return this.rawClient.resume(id).thenApply(response -> response.body());
    }

    /**
     * Resumes a previously paused membership's recurring payment collection. Billing resumes on the next cycle.
     */
    public CompletableFuture<Membership> resume(String id, RequestOptions requestOptions) {
        return this.rawClient.resume(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Resumes a previously paused membership's recurring payment collection. Billing resumes on the next cycle.
     */
    public CompletableFuture<Membership> resume(String id, ResumeMembershipsRequest request) {
        return this.rawClient.resume(id, request).thenApply(response -> response.body());
    }

    /**
     * Resumes a previously paused membership's recurring payment collection. Billing resumes on the next cycle.
     */
    public CompletableFuture<Membership> resume(
            String id, ResumeMembershipsRequest request, RequestOptions requestOptions) {
        return this.rawClient.resume(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Re-run access fulfillment for a membership. Recomputes the member's content access on Whop, re-validates their Discord link (re-adding them to the server and re-assigning roles if needed), and re-fulfills TradingView indicator access. Telegram access is invite-based and cannot be resynced here. The outcome is written to the membership's logs.
     * <p>Required permissions:</p>
     * <ul>
     * <li><code>membership:resync_access</code></li>
     * <li><code>member:email:read</code></li>
     * <li><code>member:basic:read</code></li>
     * </ul>
     */
    public CompletableFuture<Membership> resyncAccessMembership(String id) {
        return this.rawClient.resyncAccessMembership(id).thenApply(response -> response.body());
    }

    /**
     * Re-run access fulfillment for a membership. Recomputes the member's content access on Whop, re-validates their Discord link (re-adding them to the server and re-assigning roles if needed), and re-fulfills TradingView indicator access. Telegram access is invite-based and cannot be resynced here. The outcome is written to the membership's logs.
     * <p>Required permissions:</p>
     * <ul>
     * <li><code>membership:resync_access</code></li>
     * <li><code>member:email:read</code></li>
     * <li><code>member:basic:read</code></li>
     * </ul>
     */
    public CompletableFuture<Membership> resyncAccessMembership(String id, RequestOptions requestOptions) {
        return this.rawClient.resyncAccessMembership(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Re-run access fulfillment for a membership. Recomputes the member's content access on Whop, re-validates their Discord link (re-adding them to the server and re-assigning roles if needed), and re-fulfills TradingView indicator access. Telegram access is invite-based and cannot be resynced here. The outcome is written to the membership's logs.
     * <p>Required permissions:</p>
     * <ul>
     * <li><code>membership:resync_access</code></li>
     * <li><code>member:email:read</code></li>
     * <li><code>member:basic:read</code></li>
     * </ul>
     */
    public CompletableFuture<Membership> resyncAccessMembership(String id, ResyncAccessMembershipRequest request) {
        return this.rawClient.resyncAccessMembership(id, request).thenApply(response -> response.body());
    }

    /**
     * Re-run access fulfillment for a membership. Recomputes the member's content access on Whop, re-validates their Discord link (re-adding them to the server and re-assigning roles if needed), and re-fulfills TradingView indicator access. Telegram access is invite-based and cannot be resynced here. The outcome is written to the membership's logs.
     * <p>Required permissions:</p>
     * <ul>
     * <li><code>membership:resync_access</code></li>
     * <li><code>member:email:read</code></li>
     * <li><code>member:basic:read</code></li>
     * </ul>
     */
    public CompletableFuture<Membership> resyncAccessMembership(
            String id, ResyncAccessMembershipRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .resyncAccessMembership(id, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Creates a one-use transfer URL for a membership. Opening the URL while logged into a different Whop account claims the membership onto that account. The membership's buyer can generate a link for their own membership with <code>membership:transfer</code> when the product allows transfers and the membership is <code>trialing</code>, <code>active</code>, or <code>completed</code>. An account credential with <code>membership:update</code> bypasses both restrictions.
     */
    public CompletableFuture<TransferMembershipsResponse> transfer(String id) {
        return this.rawClient.transfer(id).thenApply(response -> response.body());
    }

    /**
     * Creates a one-use transfer URL for a membership. Opening the URL while logged into a different Whop account claims the membership onto that account. The membership's buyer can generate a link for their own membership with <code>membership:transfer</code> when the product allows transfers and the membership is <code>trialing</code>, <code>active</code>, or <code>completed</code>. An account credential with <code>membership:update</code> bypasses both restrictions.
     */
    public CompletableFuture<TransferMembershipsResponse> transfer(String id, RequestOptions requestOptions) {
        return this.rawClient.transfer(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Creates a one-use transfer URL for a membership. Opening the URL while logged into a different Whop account claims the membership onto that account. The membership's buyer can generate a link for their own membership with <code>membership:transfer</code> when the product allows transfers and the membership is <code>trialing</code>, <code>active</code>, or <code>completed</code>. An account credential with <code>membership:update</code> bypasses both restrictions.
     */
    public CompletableFuture<TransferMembershipsResponse> transfer(String id, TransferMembershipsRequest request) {
        return this.rawClient.transfer(id, request).thenApply(response -> response.body());
    }

    /**
     * Creates a one-use transfer URL for a membership. Opening the URL while logged into a different Whop account claims the membership onto that account. The membership's buyer can generate a link for their own membership with <code>membership:transfer</code> when the product allows transfers and the membership is <code>trialing</code>, <code>active</code>, or <code>completed</code>. An account credential with <code>membership:update</code> bypasses both restrictions.
     */
    public CompletableFuture<TransferMembershipsResponse> transfer(
            String id, TransferMembershipsRequest request, RequestOptions requestOptions) {
        return this.rawClient.transfer(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Reverse a pending cancellation for a membership that was scheduled to cancel at period end.
     * <p>Required permissions:</p>
     * <ul>
     * <li><code>member:manage</code></li>
     * <li><code>member:email:read</code></li>
     * <li><code>member:basic:read</code></li>
     * </ul>
     */
    public CompletableFuture<Membership> uncancelMembership(String id) {
        return this.rawClient.uncancelMembership(id).thenApply(response -> response.body());
    }

    /**
     * Reverse a pending cancellation for a membership that was scheduled to cancel at period end.
     * <p>Required permissions:</p>
     * <ul>
     * <li><code>member:manage</code></li>
     * <li><code>member:email:read</code></li>
     * <li><code>member:basic:read</code></li>
     * </ul>
     */
    public CompletableFuture<Membership> uncancelMembership(String id, RequestOptions requestOptions) {
        return this.rawClient.uncancelMembership(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Reverse a pending cancellation for a membership that was scheduled to cancel at period end.
     * <p>Required permissions:</p>
     * <ul>
     * <li><code>member:manage</code></li>
     * <li><code>member:email:read</code></li>
     * <li><code>member:basic:read</code></li>
     * </ul>
     */
    public CompletableFuture<Membership> uncancelMembership(String id, UncancelMembershipRequest request) {
        return this.rawClient.uncancelMembership(id, request).thenApply(response -> response.body());
    }

    /**
     * Reverse a pending cancellation for a membership that was scheduled to cancel at period end.
     * <p>Required permissions:</p>
     * <ul>
     * <li><code>member:manage</code></li>
     * <li><code>member:email:read</code></li>
     * <li><code>member:basic:read</code></li>
     * </ul>
     */
    public CompletableFuture<Membership> uncancelMembership(
            String id, UncancelMembershipRequest request, RequestOptions requestOptions) {
        return this.rawClient.uncancelMembership(id, request, requestOptions).thenApply(response -> response.body());
    }
}
