/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.payouts.methods.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CreateMethodsResponseSupportedPayoutMethodDeliveryType {
    public static final CreateMethodsResponseSupportedPayoutMethodDeliveryType CRYPTOCURRENCY =
            new CreateMethodsResponseSupportedPayoutMethodDeliveryType(Value.CRYPTOCURRENCY, "cryptocurrency");

    public static final CreateMethodsResponseSupportedPayoutMethodDeliveryType CHECK =
            new CreateMethodsResponseSupportedPayoutMethodDeliveryType(Value.CHECK, "check");

    public static final CreateMethodsResponseSupportedPayoutMethodDeliveryType CARD =
            new CreateMethodsResponseSupportedPayoutMethodDeliveryType(Value.CARD, "card");

    public static final CreateMethodsResponseSupportedPayoutMethodDeliveryType UNKNOWN =
            new CreateMethodsResponseSupportedPayoutMethodDeliveryType(Value.UNKNOWN, "unknown");

    public static final CreateMethodsResponseSupportedPayoutMethodDeliveryType HOME_DELIVERY =
            new CreateMethodsResponseSupportedPayoutMethodDeliveryType(Value.HOME_DELIVERY, "home_delivery");

    public static final CreateMethodsResponseSupportedPayoutMethodDeliveryType BANK_DEPOSIT =
            new CreateMethodsResponseSupportedPayoutMethodDeliveryType(Value.BANK_DEPOSIT, "bank_deposit");

    public static final CreateMethodsResponseSupportedPayoutMethodDeliveryType MOBILE_WALLET =
            new CreateMethodsResponseSupportedPayoutMethodDeliveryType(Value.MOBILE_WALLET, "mobile_wallet");

    public static final CreateMethodsResponseSupportedPayoutMethodDeliveryType CASH_PICKUP =
            new CreateMethodsResponseSupportedPayoutMethodDeliveryType(Value.CASH_PICKUP, "cash_pickup");

    public static final CreateMethodsResponseSupportedPayoutMethodDeliveryType BILL =
            new CreateMethodsResponseSupportedPayoutMethodDeliveryType(Value.BILL, "bill");

    private final Value value;

    private final String string;

    CreateMethodsResponseSupportedPayoutMethodDeliveryType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CreateMethodsResponseSupportedPayoutMethodDeliveryType
                        && this.string.equals(((CreateMethodsResponseSupportedPayoutMethodDeliveryType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CRYPTOCURRENCY:
                return visitor.visitCryptocurrency();
            case CHECK:
                return visitor.visitCheck();
            case CARD:
                return visitor.visitCard();
            case UNKNOWN:
                return visitor.visitUnknown();
            case HOME_DELIVERY:
                return visitor.visitHomeDelivery();
            case BANK_DEPOSIT:
                return visitor.visitBankDeposit();
            case MOBILE_WALLET:
                return visitor.visitMobileWallet();
            case CASH_PICKUP:
                return visitor.visitCashPickup();
            case BILL:
                return visitor.visitBill();
            case _UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CreateMethodsResponseSupportedPayoutMethodDeliveryType valueOf(String value) {
        switch (value) {
            case "cryptocurrency":
                return CRYPTOCURRENCY;
            case "check":
                return CHECK;
            case "card":
                return CARD;
            case "unknown":
                return UNKNOWN;
            case "home_delivery":
                return HOME_DELIVERY;
            case "bank_deposit":
                return BANK_DEPOSIT;
            case "mobile_wallet":
                return MOBILE_WALLET;
            case "cash_pickup":
                return CASH_PICKUP;
            case "bill":
                return BILL;
            default:
                return new CreateMethodsResponseSupportedPayoutMethodDeliveryType(Value._UNKNOWN, value);
        }
    }

    public enum Value {
        CASH_PICKUP,

        BANK_DEPOSIT,

        HOME_DELIVERY,

        MOBILE_WALLET,

        CARD,

        CHECK,

        BILL,

        CRYPTOCURRENCY,

        UNKNOWN,

        _UNKNOWN
    }

    public interface Visitor<T> {
        T visitCashPickup();

        T visitBankDeposit();

        T visitHomeDelivery();

        T visitMobileWallet();

        T visitCard();

        T visitCheck();

        T visitBill();

        T visitCryptocurrency();

        T visitUnknown();

        T visitUnknown(String unknownType);
    }
}
