/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.cards.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PostCardTransactionCreatedPayloadType {
    public static final PostCardTransactionCreatedPayloadType CARD_TRANSACTION_CREATED =
            new PostCardTransactionCreatedPayloadType(Value.CARD_TRANSACTION_CREATED, "card_transaction.created");

    private final Value value;

    private final String string;

    PostCardTransactionCreatedPayloadType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PostCardTransactionCreatedPayloadType
                        && this.string.equals(((PostCardTransactionCreatedPayloadType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CARD_TRANSACTION_CREATED:
                return visitor.visitCardTransactionCreated();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PostCardTransactionCreatedPayloadType valueOf(String value) {
        switch (value) {
            case "card_transaction.created":
                return CARD_TRANSACTION_CREATED;
            default:
                return new PostCardTransactionCreatedPayloadType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CARD_TRANSACTION_CREATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCardTransactionCreated();

        T visitUnknown(String unknownType);
    }
}
