/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.identityprofiles.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.ObjectMappers;
import com.whop.api.types.IdentityProfileListItem;
import com.whop.api.types.PageInfo;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListIdentityProfileResponse.Builder.class)
public final class ListIdentityProfileResponse {
    private final List<IdentityProfileListItem> data;

    private final PageInfo pageInfo;

    private final Map<String, Object> additionalProperties;

    private ListIdentityProfileResponse(
            List<IdentityProfileListItem> data, PageInfo pageInfo, Map<String, Object> additionalProperties) {
        this.data = data;
        this.pageInfo = pageInfo;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A list of nodes.
     */
    @JsonProperty("data")
    public List<IdentityProfileListItem> getData() {
        return data;
    }

    /**
     * @return Information to aid in pagination.
     */
    @JsonProperty("page_info")
    public PageInfo getPageInfo() {
        return pageInfo;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListIdentityProfileResponse && equalTo((ListIdentityProfileResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListIdentityProfileResponse other) {
        return data.equals(other.data) && pageInfo.equals(other.pageInfo);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.data, this.pageInfo);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PageInfoStage builder() {
        return new Builder();
    }

    public interface PageInfoStage {
        /**
         * <p>Information to aid in pagination.</p>
         */
        _FinalStage pageInfo(@NotNull PageInfo pageInfo);

        Builder from(ListIdentityProfileResponse other);
    }

    public interface _FinalStage {
        ListIdentityProfileResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>A list of nodes.</p>
         */
        _FinalStage data(List<IdentityProfileListItem> data);

        _FinalStage addData(IdentityProfileListItem data);

        _FinalStage addAllData(List<IdentityProfileListItem> data);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PageInfoStage, _FinalStage {
        private PageInfo pageInfo;

        private List<IdentityProfileListItem> data = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ListIdentityProfileResponse other) {
            data(other.getData());
            pageInfo(other.getPageInfo());
            return this;
        }

        /**
         * <p>Information to aid in pagination.</p>
         * <p>Information to aid in pagination.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("page_info")
        public _FinalStage pageInfo(@NotNull PageInfo pageInfo) {
            this.pageInfo = Objects.requireNonNull(pageInfo, "pageInfo must not be null");
            return this;
        }

        /**
         * <p>A list of nodes.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllData(List<IdentityProfileListItem> data) {
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        /**
         * <p>A list of nodes.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addData(IdentityProfileListItem data) {
            this.data.add(data);
            return this;
        }

        /**
         * <p>A list of nodes.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public _FinalStage data(List<IdentityProfileListItem> data) {
            this.data.clear();
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        @java.lang.Override
        public ListIdentityProfileResponse build() {
            return new ListIdentityProfileResponse(data, pageInfo, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
