/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.dmmembers.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListDmMembersRequest.Builder.class)
public final class ListDmMembersRequest {
    private final Optional<String> after;

    private final Optional<String> before;

    private final Optional<Integer> first;

    private final Optional<Integer> last;

    private final String channelId;

    private final Map<String, Object> additionalProperties;

    private ListDmMembersRequest(
            Optional<String> after,
            Optional<String> before,
            Optional<Integer> first,
            Optional<Integer> last,
            String channelId,
            Map<String, Object> additionalProperties) {
        this.after = after;
        this.before = before;
        this.first = first;
        this.last = last;
        this.channelId = channelId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return <p>the elements in the list that come after the specified cursor.</p>
     */
    @JsonProperty("after")
    public Optional<String> getAfter() {
        return after;
    }

    /**
     * @return <p>the elements in the list that come before the specified cursor.</p>
     */
    @JsonProperty("before")
    public Optional<String> getBefore() {
        return before;
    }

    /**
     * @return <p>the first <em>n</em> elements from the list.</p>
     */
    @JsonProperty("first")
    public Optional<Integer> getFirst() {
        return first;
    }

    /**
     * @return <p>the last <em>n</em> elements from the list.</p>
     */
    @JsonProperty("last")
    public Optional<Integer> getLast() {
        return last;
    }

    /**
     * @return The unique identifier of the DM channel to list members for.
     */
    @JsonProperty("channel_id")
    public String getChannelId() {
        return channelId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListDmMembersRequest && equalTo((ListDmMembersRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListDmMembersRequest other) {
        return after.equals(other.after)
                && before.equals(other.before)
                && first.equals(other.first)
                && last.equals(other.last)
                && channelId.equals(other.channelId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.after, this.before, this.first, this.last, this.channelId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ChannelIdStage builder() {
        return new Builder();
    }

    public interface ChannelIdStage {
        /**
         * <p>The unique identifier of the DM channel to list members for.</p>
         */
        _FinalStage channelId(@NotNull String channelId);

        Builder from(ListDmMembersRequest other);
    }

    public interface _FinalStage {
        ListDmMembersRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Returns the elements in the list that come after the specified cursor.</p>
         */
        _FinalStage after(Optional<String> after);

        _FinalStage after(String after);

        /**
         * <p>Returns the elements in the list that come before the specified cursor.</p>
         */
        _FinalStage before(Optional<String> before);

        _FinalStage before(String before);

        /**
         * <p>Returns the first <em>n</em> elements from the list.</p>
         */
        _FinalStage first(Optional<Integer> first);

        _FinalStage first(Integer first);

        /**
         * <p>Returns the last <em>n</em> elements from the list.</p>
         */
        _FinalStage last(Optional<Integer> last);

        _FinalStage last(Integer last);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ChannelIdStage, _FinalStage {
        private String channelId;

        private Optional<Integer> last = Optional.empty();

        private Optional<Integer> first = Optional.empty();

        private Optional<String> before = Optional.empty();

        private Optional<String> after = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ListDmMembersRequest other) {
            after(other.getAfter());
            before(other.getBefore());
            first(other.getFirst());
            last(other.getLast());
            channelId(other.getChannelId());
            return this;
        }

        /**
         * <p>The unique identifier of the DM channel to list members for.</p>
         * <p>The unique identifier of the DM channel to list members for.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("channel_id")
        public _FinalStage channelId(@NotNull String channelId) {
            this.channelId = Objects.requireNonNull(channelId, "channelId must not be null");
            return this;
        }

        /**
         * <p>Returns the last <em>n</em> elements from the list.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage last(Integer last) {
            this.last = Optional.ofNullable(last);
            return this;
        }

        /**
         * <p>Returns the last <em>n</em> elements from the list.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "last", nulls = Nulls.SKIP)
        public _FinalStage last(Optional<Integer> last) {
            this.last = last;
            return this;
        }

        /**
         * <p>Returns the first <em>n</em> elements from the list.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage first(Integer first) {
            this.first = Optional.ofNullable(first);
            return this;
        }

        /**
         * <p>Returns the first <em>n</em> elements from the list.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "first", nulls = Nulls.SKIP)
        public _FinalStage first(Optional<Integer> first) {
            this.first = first;
            return this;
        }

        /**
         * <p>Returns the elements in the list that come before the specified cursor.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage before(String before) {
            this.before = Optional.ofNullable(before);
            return this;
        }

        /**
         * <p>Returns the elements in the list that come before the specified cursor.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "before", nulls = Nulls.SKIP)
        public _FinalStage before(Optional<String> before) {
            this.before = before;
            return this;
        }

        /**
         * <p>Returns the elements in the list that come after the specified cursor.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage after(String after) {
            this.after = Optional.ofNullable(after);
            return this;
        }

        /**
         * <p>Returns the elements in the list that come after the specified cursor.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "after", nulls = Nulls.SKIP)
        public _FinalStage after(Optional<String> after) {
            this.after = after;
            return this;
        }

        @java.lang.Override
        public ListDmMembersRequest build() {
            return new ListDmMembersRequest(after, before, first, last, channelId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
