/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AdCallToAction {
    public static final AdCallToAction WHATSAPP_MESSAGE =
            new AdCallToAction(Value.WHATSAPP_MESSAGE, "whatsapp_message");

    public static final AdCallToAction REQUEST_TIME = new AdCallToAction(Value.REQUEST_TIME, "request_time");

    public static final AdCallToAction NO_BUTTON = new AdCallToAction(Value.NO_BUTTON, "no_button");

    public static final AdCallToAction GET_STARTED = new AdCallToAction(Value.GET_STARTED, "get_started");

    public static final AdCallToAction GET_OFFER = new AdCallToAction(Value.GET_OFFER, "get_offer");

    public static final AdCallToAction OPEN_LINK = new AdCallToAction(Value.OPEN_LINK, "open_link");

    public static final AdCallToAction INSTAGRAM_MESSAGE =
            new AdCallToAction(Value.INSTAGRAM_MESSAGE, "instagram_message");

    public static final AdCallToAction LISTEN_NOW = new AdCallToAction(Value.LISTEN_NOW, "listen_now");

    public static final AdCallToAction ORDER_NOW = new AdCallToAction(Value.ORDER_NOW, "order_now");

    public static final AdCallToAction GET_QUOTE = new AdCallToAction(Value.GET_QUOTE, "get_quote");

    public static final AdCallToAction LEARN_MORE = new AdCallToAction(Value.LEARN_MORE, "learn_more");

    public static final AdCallToAction DOWNLOAD = new AdCallToAction(Value.DOWNLOAD, "download");

    public static final AdCallToAction SEND_UPDATES = new AdCallToAction(Value.SEND_UPDATES, "send_updates");

    public static final AdCallToAction CONTACT_US = new AdCallToAction(Value.CONTACT_US, "contact_us");

    public static final AdCallToAction WATCH_MORE = new AdCallToAction(Value.WATCH_MORE, "watch_more");

    public static final AdCallToAction BOOK_NOW = new AdCallToAction(Value.BOOK_NOW, "book_now");

    public static final AdCallToAction SIGN_UP = new AdCallToAction(Value.SIGN_UP, "sign_up");

    public static final AdCallToAction GET_EVENT_TICKETS =
            new AdCallToAction(Value.GET_EVENT_TICKETS, "get_event_tickets");

    public static final AdCallToAction VIEW_INSTAGRAM_PROFILE =
            new AdCallToAction(Value.VIEW_INSTAGRAM_PROFILE, "view_instagram_profile");

    public static final AdCallToAction EVENT_RSVP = new AdCallToAction(Value.EVENT_RSVP, "event_rsvp");

    public static final AdCallToAction SHOP_NOW = new AdCallToAction(Value.SHOP_NOW, "shop_now");

    public static final AdCallToAction GET_OFFER_VIEW = new AdCallToAction(Value.GET_OFFER_VIEW, "get_offer_view");

    public static final AdCallToAction MESSAGE_PAGE = new AdCallToAction(Value.MESSAGE_PAGE, "message_page");

    public static final AdCallToAction GET_DIRECTIONS = new AdCallToAction(Value.GET_DIRECTIONS, "get_directions");

    public static final AdCallToAction SEE_DETAILS = new AdCallToAction(Value.SEE_DETAILS, "see_details");

    public static final AdCallToAction CALL_NOW = new AdCallToAction(Value.CALL_NOW, "call_now");

    public static final AdCallToAction SUBSCRIBE = new AdCallToAction(Value.SUBSCRIBE, "subscribe");

    public static final AdCallToAction BUY_NOW = new AdCallToAction(Value.BUY_NOW, "buy_now");

    public static final AdCallToAction SEE_MENU = new AdCallToAction(Value.SEE_MENU, "see_menu");

    public static final AdCallToAction APPLY_NOW = new AdCallToAction(Value.APPLY_NOW, "apply_now");

    public static final AdCallToAction PLAY_GAME = new AdCallToAction(Value.PLAY_GAME, "play_game");

    private final Value value;

    private final String string;

    AdCallToAction(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AdCallToAction && this.string.equals(((AdCallToAction) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case WHATSAPP_MESSAGE:
                return visitor.visitWhatsappMessage();
            case REQUEST_TIME:
                return visitor.visitRequestTime();
            case NO_BUTTON:
                return visitor.visitNoButton();
            case GET_STARTED:
                return visitor.visitGetStarted();
            case GET_OFFER:
                return visitor.visitGetOffer();
            case OPEN_LINK:
                return visitor.visitOpenLink();
            case INSTAGRAM_MESSAGE:
                return visitor.visitInstagramMessage();
            case LISTEN_NOW:
                return visitor.visitListenNow();
            case ORDER_NOW:
                return visitor.visitOrderNow();
            case GET_QUOTE:
                return visitor.visitGetQuote();
            case LEARN_MORE:
                return visitor.visitLearnMore();
            case DOWNLOAD:
                return visitor.visitDownload();
            case SEND_UPDATES:
                return visitor.visitSendUpdates();
            case CONTACT_US:
                return visitor.visitContactUs();
            case WATCH_MORE:
                return visitor.visitWatchMore();
            case BOOK_NOW:
                return visitor.visitBookNow();
            case SIGN_UP:
                return visitor.visitSignUp();
            case GET_EVENT_TICKETS:
                return visitor.visitGetEventTickets();
            case VIEW_INSTAGRAM_PROFILE:
                return visitor.visitViewInstagramProfile();
            case EVENT_RSVP:
                return visitor.visitEventRsvp();
            case SHOP_NOW:
                return visitor.visitShopNow();
            case GET_OFFER_VIEW:
                return visitor.visitGetOfferView();
            case MESSAGE_PAGE:
                return visitor.visitMessagePage();
            case GET_DIRECTIONS:
                return visitor.visitGetDirections();
            case SEE_DETAILS:
                return visitor.visitSeeDetails();
            case CALL_NOW:
                return visitor.visitCallNow();
            case SUBSCRIBE:
                return visitor.visitSubscribe();
            case BUY_NOW:
                return visitor.visitBuyNow();
            case SEE_MENU:
                return visitor.visitSeeMenu();
            case APPLY_NOW:
                return visitor.visitApplyNow();
            case PLAY_GAME:
                return visitor.visitPlayGame();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AdCallToAction valueOf(String value) {
        switch (value) {
            case "whatsapp_message":
                return WHATSAPP_MESSAGE;
            case "request_time":
                return REQUEST_TIME;
            case "no_button":
                return NO_BUTTON;
            case "get_started":
                return GET_STARTED;
            case "get_offer":
                return GET_OFFER;
            case "open_link":
                return OPEN_LINK;
            case "instagram_message":
                return INSTAGRAM_MESSAGE;
            case "listen_now":
                return LISTEN_NOW;
            case "order_now":
                return ORDER_NOW;
            case "get_quote":
                return GET_QUOTE;
            case "learn_more":
                return LEARN_MORE;
            case "download":
                return DOWNLOAD;
            case "send_updates":
                return SEND_UPDATES;
            case "contact_us":
                return CONTACT_US;
            case "watch_more":
                return WATCH_MORE;
            case "book_now":
                return BOOK_NOW;
            case "sign_up":
                return SIGN_UP;
            case "get_event_tickets":
                return GET_EVENT_TICKETS;
            case "view_instagram_profile":
                return VIEW_INSTAGRAM_PROFILE;
            case "event_rsvp":
                return EVENT_RSVP;
            case "shop_now":
                return SHOP_NOW;
            case "get_offer_view":
                return GET_OFFER_VIEW;
            case "message_page":
                return MESSAGE_PAGE;
            case "get_directions":
                return GET_DIRECTIONS;
            case "see_details":
                return SEE_DETAILS;
            case "call_now":
                return CALL_NOW;
            case "subscribe":
                return SUBSCRIBE;
            case "buy_now":
                return BUY_NOW;
            case "see_menu":
                return SEE_MENU;
            case "apply_now":
                return APPLY_NOW;
            case "play_game":
                return PLAY_GAME;
            default:
                return new AdCallToAction(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        LEARN_MORE,

        SHOP_NOW,

        SIGN_UP,

        SUBSCRIBE,

        GET_STARTED,

        BOOK_NOW,

        APPLY_NOW,

        CONTACT_US,

        DOWNLOAD,

        ORDER_NOW,

        BUY_NOW,

        GET_QUOTE,

        MESSAGE_PAGE,

        WHATSAPP_MESSAGE,

        INSTAGRAM_MESSAGE,

        CALL_NOW,

        GET_DIRECTIONS,

        SEND_UPDATES,

        GET_OFFER,

        WATCH_MORE,

        LISTEN_NOW,

        PLAY_GAME,

        OPEN_LINK,

        NO_BUTTON,

        GET_OFFER_VIEW,

        GET_EVENT_TICKETS,

        SEE_MENU,

        REQUEST_TIME,

        EVENT_RSVP,

        SEE_DETAILS,

        VIEW_INSTAGRAM_PROFILE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitLearnMore();

        T visitShopNow();

        T visitSignUp();

        T visitSubscribe();

        T visitGetStarted();

        T visitBookNow();

        T visitApplyNow();

        T visitContactUs();

        T visitDownload();

        T visitOrderNow();

        T visitBuyNow();

        T visitGetQuote();

        T visitMessagePage();

        T visitWhatsappMessage();

        T visitInstagramMessage();

        T visitCallNow();

        T visitGetDirections();

        T visitSendUpdates();

        T visitGetOffer();

        T visitWatchMore();

        T visitListenNow();

        T visitPlayGame();

        T visitOpenLink();

        T visitNoButton();

        T visitGetOfferView();

        T visitGetEventTickets();

        T visitSeeMenu();

        T visitRequestTime();

        T visitEventRsvp();

        T visitSeeDetails();

        T visitViewInstagramProfile();

        T visitUnknown(String unknownType);
    }
}
