/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AppListItemAppType {
    public static final AppListItemAppType COMPONENT = new AppListItemAppType(Value.COMPONENT, "component");

    public static final AppListItemAppType WEBSITE = new AppListItemAppType(Value.WEBSITE, "website");

    public static final AppListItemAppType B2B_APP = new AppListItemAppType(Value.B2B_APP, "b2b_app");

    public static final AppListItemAppType B2C_APP = new AppListItemAppType(Value.B2C_APP, "b2c_app");

    public static final AppListItemAppType COMPANY_APP = new AppListItemAppType(Value.COMPANY_APP, "company_app");

    private final Value value;

    private final String string;

    AppListItemAppType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AppListItemAppType && this.string.equals(((AppListItemAppType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case COMPONENT:
                return visitor.visitComponent();
            case WEBSITE:
                return visitor.visitWebsite();
            case B2B_APP:
                return visitor.visitB2BApp();
            case B2C_APP:
                return visitor.visitB2CApp();
            case COMPANY_APP:
                return visitor.visitCompanyApp();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AppListItemAppType valueOf(String value) {
        switch (value) {
            case "component":
                return COMPONENT;
            case "website":
                return WEBSITE;
            case "b2b_app":
                return B2B_APP;
            case "b2c_app":
                return B2C_APP;
            case "company_app":
                return COMPANY_APP;
            default:
                return new AppListItemAppType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        B2B_APP,

        B2C_APP,

        COMPANY_APP,

        COMPONENT,

        WEBSITE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitB2BApp();

        T visitB2CApp();

        T visitCompanyApp();

        T visitComponent();

        T visitWebsite();

        T visitUnknown(String unknownType);
    }
}
