/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AppOauthClientTypes {
    public static final AppOauthClientTypes PUBLIC = new AppOauthClientTypes(Value.PUBLIC, "public");

    public static final AppOauthClientTypes CONFIDENTIAL = new AppOauthClientTypes(Value.CONFIDENTIAL, "confidential");

    private final Value value;

    private final String string;

    AppOauthClientTypes(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AppOauthClientTypes && this.string.equals(((AppOauthClientTypes) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PUBLIC:
                return visitor.visitPublic();
            case CONFIDENTIAL:
                return visitor.visitConfidential();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AppOauthClientTypes valueOf(String value) {
        switch (value) {
            case "public":
                return PUBLIC;
            case "confidential":
                return CONFIDENTIAL;
            default:
                return new AppOauthClientTypes(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PUBLIC,

        CONFIDENTIAL,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPublic();

        T visitConfidential();

        T visitUnknown(String unknownType);
    }
}
