/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AppRequiredScopesItem {
    public static final AppRequiredScopesItem READ_USER = new AppRequiredScopesItem(Value.READ_USER, "read_user");

    private final Value value;

    private final String string;

    AppRequiredScopesItem(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AppRequiredScopesItem
                        && this.string.equals(((AppRequiredScopesItem) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case READ_USER:
                return visitor.visitReadUser();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AppRequiredScopesItem valueOf(String value) {
        switch (value) {
            case "read_user":
                return READ_USER;
            default:
                return new AppRequiredScopesItem(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        READ_USER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitReadUser();

        T visitUnknown(String unknownType);
    }
}
