/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CheckoutShapes {
    public static final CheckoutShapes RECTANGULAR = new CheckoutShapes(Value.RECTANGULAR, "rectangular");

    public static final CheckoutShapes ROUNDED = new CheckoutShapes(Value.ROUNDED, "rounded");

    public static final CheckoutShapes PILL = new CheckoutShapes(Value.PILL, "pill");

    private final Value value;

    private final String string;

    CheckoutShapes(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CheckoutShapes && this.string.equals(((CheckoutShapes) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case RECTANGULAR:
                return visitor.visitRectangular();
            case ROUNDED:
                return visitor.visitRounded();
            case PILL:
                return visitor.visitPill();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CheckoutShapes valueOf(String value) {
        switch (value) {
            case "rectangular":
                return RECTANGULAR;
            case "rounded":
                return ROUNDED;
            case "pill":
                return PILL;
            default:
                return new CheckoutShapes(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ROUNDED,

        PILL,

        RECTANGULAR,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitRounded();

        T visitPill();

        T visitRectangular();

        T visitUnknown(String unknownType);
    }
}
