/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CourseChaptersItem.Builder.class)
public final class CourseChaptersItem {
    private final String id;

    private final List<CourseChaptersItemLessonsItem> lessons;

    private final int order;

    private final String title;

    private final Map<String, Object> additionalProperties;

    private CourseChaptersItem(
            String id,
            List<CourseChaptersItemLessonsItem> lessons,
            int order,
            String title,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.lessons = lessons;
        this.order = order;
        this.title = title;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique identifier for the chapter.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return An ordered list of lessons in this chapter, sorted by display position. Hidden lessons are excluded for non-admin users.
     */
    @JsonProperty("lessons")
    public List<CourseChaptersItemLessonsItem> getLessons() {
        return lessons;
    }

    /**
     * @return The sort position of this chapter within its parent course, starting from zero.
     */
    @JsonProperty("order")
    public int getOrder() {
        return order;
    }

    /**
     * @return The display name of the chapter shown to students. Maximum 150 characters.
     */
    @JsonProperty("title")
    public String getTitle() {
        return title;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CourseChaptersItem && equalTo((CourseChaptersItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CourseChaptersItem other) {
        return id.equals(other.id)
                && lessons.equals(other.lessons)
                && order == other.order
                && title.equals(other.title);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.lessons, this.order, this.title);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The unique identifier for the chapter.</p>
         */
        OrderStage id(@NotNull String id);

        Builder from(CourseChaptersItem other);
    }

    public interface OrderStage {
        /**
         * <p>The sort position of this chapter within its parent course, starting from zero.</p>
         */
        TitleStage order(int order);
    }

    public interface TitleStage {
        /**
         * <p>The display name of the chapter shown to students. Maximum 150 characters.</p>
         */
        _FinalStage title(@NotNull String title);
    }

    public interface _FinalStage {
        CourseChaptersItem build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>An ordered list of lessons in this chapter, sorted by display position. Hidden lessons are excluded for non-admin users.</p>
         */
        _FinalStage lessons(List<CourseChaptersItemLessonsItem> lessons);

        _FinalStage addLessons(CourseChaptersItemLessonsItem lessons);

        _FinalStage addAllLessons(List<CourseChaptersItemLessonsItem> lessons);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, OrderStage, TitleStage, _FinalStage {
        private String id;

        private int order;

        private String title;

        private List<CourseChaptersItemLessonsItem> lessons = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CourseChaptersItem other) {
            id(other.getId());
            lessons(other.getLessons());
            order(other.getOrder());
            title(other.getTitle());
            return this;
        }

        /**
         * <p>The unique identifier for the chapter.</p>
         * <p>The unique identifier for the chapter.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public OrderStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The sort position of this chapter within its parent course, starting from zero.</p>
         * <p>The sort position of this chapter within its parent course, starting from zero.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("order")
        public TitleStage order(int order) {
            this.order = order;
            return this;
        }

        /**
         * <p>The display name of the chapter shown to students. Maximum 150 characters.</p>
         * <p>The display name of the chapter shown to students. Maximum 150 characters.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("title")
        public _FinalStage title(@NotNull String title) {
            this.title = Objects.requireNonNull(title, "title must not be null");
            return this;
        }

        /**
         * <p>An ordered list of lessons in this chapter, sorted by display position. Hidden lessons are excluded for non-admin users.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllLessons(List<CourseChaptersItemLessonsItem> lessons) {
            if (lessons != null) {
                this.lessons.addAll(lessons);
            }
            return this;
        }

        /**
         * <p>An ordered list of lessons in this chapter, sorted by display position. Hidden lessons are excluded for non-admin users.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addLessons(CourseChaptersItemLessonsItem lessons) {
            this.lessons.add(lessons);
            return this;
        }

        /**
         * <p>An ordered list of lessons in this chapter, sorted by display position. Hidden lessons are excluded for non-admin users.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "lessons", nulls = Nulls.SKIP)
        public _FinalStage lessons(List<CourseChaptersItemLessonsItem> lessons) {
            this.lessons.clear();
            if (lessons != null) {
                this.lessons.addAll(lessons);
            }
            return this;
        }

        @java.lang.Override
        public CourseChaptersItem build() {
            return new CourseChaptersItem(id, lessons, order, title, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
