/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CourseLessonInteractionLesson.Builder.class)
public final class CourseLessonInteractionLesson {
    private final CourseLessonInteractionLessonChapter chapter;

    private final String id;

    private final String title;

    private final Map<String, Object> additionalProperties;

    private CourseLessonInteractionLesson(
            CourseLessonInteractionLessonChapter chapter,
            String id,
            String title,
            Map<String, Object> additionalProperties) {
        this.chapter = chapter;
        this.id = id;
        this.title = title;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The parent chapter that contains this lesson.
     */
    @JsonProperty("chapter")
    public CourseLessonInteractionLessonChapter getChapter() {
        return chapter;
    }

    /**
     * @return The unique identifier for the lesson.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return The display name of the lesson shown to students. Maximum 120 characters.
     */
    @JsonProperty("title")
    public String getTitle() {
        return title;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CourseLessonInteractionLesson && equalTo((CourseLessonInteractionLesson) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CourseLessonInteractionLesson other) {
        return chapter.equals(other.chapter) && id.equals(other.id) && title.equals(other.title);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.chapter, this.id, this.title);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ChapterStage builder() {
        return new Builder();
    }

    public interface ChapterStage {
        /**
         * <p>The parent chapter that contains this lesson.</p>
         */
        IdStage chapter(@NotNull CourseLessonInteractionLessonChapter chapter);

        Builder from(CourseLessonInteractionLesson other);
    }

    public interface IdStage {
        /**
         * <p>The unique identifier for the lesson.</p>
         */
        TitleStage id(@NotNull String id);
    }

    public interface TitleStage {
        /**
         * <p>The display name of the lesson shown to students. Maximum 120 characters.</p>
         */
        _FinalStage title(@NotNull String title);
    }

    public interface _FinalStage {
        CourseLessonInteractionLesson build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ChapterStage, IdStage, TitleStage, _FinalStage {
        private CourseLessonInteractionLessonChapter chapter;

        private String id;

        private String title;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CourseLessonInteractionLesson other) {
            chapter(other.getChapter());
            id(other.getId());
            title(other.getTitle());
            return this;
        }

        /**
         * <p>The parent chapter that contains this lesson.</p>
         * <p>The parent chapter that contains this lesson.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("chapter")
        public IdStage chapter(@NotNull CourseLessonInteractionLessonChapter chapter) {
            this.chapter = Objects.requireNonNull(chapter, "chapter must not be null");
            return this;
        }

        /**
         * <p>The unique identifier for the lesson.</p>
         * <p>The unique identifier for the lesson.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public TitleStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The display name of the lesson shown to students. Maximum 120 characters.</p>
         * <p>The display name of the lesson shown to students. Maximum 120 characters.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("title")
        public _FinalStage title(@NotNull String title) {
            this.title = Objects.requireNonNull(title, "title must not be null");
            return this;
        }

        @java.lang.Override
        public CourseLessonInteractionLesson build() {
            return new CourseLessonInteractionLesson(chapter, id, title, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
