/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.Nullable;
import com.whop.api.core.NullableNonemptyFilter;
import com.whop.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DisputeListItem.Builder.class)
public final class DisputeListItem {
    private final double amount;

    private final Optional<DisputeListItemCompany> company;

    private final Optional<OffsetDateTime> createdAt;

    private final Currencies currency;

    private final Optional<Boolean> editable;

    private final String id;

    private final Optional<OffsetDateTime> needsResponseBy;

    private final Optional<DisputeListItemPayment> payment;

    private final Optional<DisputeListItemPlan> plan;

    private final Optional<DisputeListItemProduct> product;

    private final Optional<String> reason;

    private final Optional<String> reasonCode;

    private final DisputeStatuses status;

    private final boolean visaRdr;

    private final Map<String, Object> additionalProperties;

    private DisputeListItem(
            double amount,
            Optional<DisputeListItemCompany> company,
            Optional<OffsetDateTime> createdAt,
            Currencies currency,
            Optional<Boolean> editable,
            String id,
            Optional<OffsetDateTime> needsResponseBy,
            Optional<DisputeListItemPayment> payment,
            Optional<DisputeListItemPlan> plan,
            Optional<DisputeListItemProduct> product,
            Optional<String> reason,
            Optional<String> reasonCode,
            DisputeStatuses status,
            boolean visaRdr,
            Map<String, Object> additionalProperties) {
        this.amount = amount;
        this.company = company;
        this.createdAt = createdAt;
        this.currency = currency;
        this.editable = editable;
        this.id = id;
        this.needsResponseBy = needsResponseBy;
        this.payment = payment;
        this.plan = plan;
        this.product = product;
        this.reason = reason;
        this.reasonCode = reasonCode;
        this.status = status;
        this.visaRdr = visaRdr;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The disputed amount in the specified currency, formatted as a decimal.
     */
    @JsonProperty("amount")
    public double getAmount() {
        return amount;
    }

    /**
     * @return The company that the dispute was filed against.
     */
    @JsonIgnore
    public Optional<DisputeListItemCompany> getCompany() {
        if (company == null) {
            return Optional.empty();
        }
        return company;
    }

    /**
     * @return The datetime the dispute was created.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getCreatedAt() {
        if (createdAt == null) {
            return Optional.empty();
        }
        return createdAt;
    }

    /**
     * @return The three-letter ISO currency code for the disputed amount.
     */
    @JsonProperty("currency")
    public Currencies getCurrency() {
        return currency;
    }

    /**
     * @return Whether the dispute evidence can still be edited and submitted.
     */
    @JsonIgnore
    public Optional<Boolean> getEditable() {
        if (editable == null) {
            return Optional.empty();
        }
        return editable;
    }

    /**
     * @return The unique identifier for the dispute.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return The deadline by which dispute evidence must be submitted. Null if no response deadline is set.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getNeedsResponseBy() {
        if (needsResponseBy == null) {
            return Optional.empty();
        }
        return needsResponseBy;
    }

    /**
     * @return The original payment that was disputed.
     */
    @JsonIgnore
    public Optional<DisputeListItemPayment> getPayment() {
        if (payment == null) {
            return Optional.empty();
        }
        return payment;
    }

    /**
     * @return The plan associated with the disputed payment. Null if the dispute is not linked to a specific plan.
     */
    @JsonIgnore
    public Optional<DisputeListItemPlan> getPlan() {
        if (plan == null) {
            return Optional.empty();
        }
        return plan;
    }

    /**
     * @return The product associated with the disputed payment. Null if the dispute is not linked to a specific product.
     */
    @JsonIgnore
    public Optional<DisputeListItemProduct> getProduct() {
        if (product == null) {
            return Optional.empty();
        }
        return product;
    }

    /**
     * @return A human-readable reason for the dispute.
     */
    @JsonIgnore
    public Optional<String> getReason() {
        if (reason == null) {
            return Optional.empty();
        }
        return reason;
    }

    /**
     * @return The card network reason code for the dispute. Null when the payment processor did not provide one.
     */
    @JsonIgnore
    public Optional<String> getReasonCode() {
        if (reasonCode == null) {
            return Optional.empty();
        }
        return reasonCode;
    }

    /**
     * @return The current status of the dispute lifecycle, such as needs_response, under_review, won, or lost.
     */
    @JsonProperty("status")
    public DisputeStatuses getStatus() {
        return status;
    }

    /**
     * @return Whether the dispute was automatically resolved through Visa Rapid Dispute Resolution (RDR).
     */
    @JsonProperty("visa_rdr")
    public boolean getVisaRdr() {
        return visaRdr;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("company")
    private Optional<DisputeListItemCompany> _getCompany() {
        return company;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("created_at")
    private Optional<OffsetDateTime> _getCreatedAt() {
        return createdAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("editable")
    private Optional<Boolean> _getEditable() {
        return editable;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("needs_response_by")
    private Optional<OffsetDateTime> _getNeedsResponseBy() {
        return needsResponseBy;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("payment")
    private Optional<DisputeListItemPayment> _getPayment() {
        return payment;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("plan")
    private Optional<DisputeListItemPlan> _getPlan() {
        return plan;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("product")
    private Optional<DisputeListItemProduct> _getProduct() {
        return product;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("reason")
    private Optional<String> _getReason() {
        return reason;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("reason_code")
    private Optional<String> _getReasonCode() {
        return reasonCode;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DisputeListItem && equalTo((DisputeListItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DisputeListItem other) {
        return amount == other.amount
                && company.equals(other.company)
                && createdAt.equals(other.createdAt)
                && currency.equals(other.currency)
                && editable.equals(other.editable)
                && id.equals(other.id)
                && needsResponseBy.equals(other.needsResponseBy)
                && payment.equals(other.payment)
                && plan.equals(other.plan)
                && product.equals(other.product)
                && reason.equals(other.reason)
                && reasonCode.equals(other.reasonCode)
                && status.equals(other.status)
                && visaRdr == other.visaRdr;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.amount,
                this.company,
                this.createdAt,
                this.currency,
                this.editable,
                this.id,
                this.needsResponseBy,
                this.payment,
                this.plan,
                this.product,
                this.reason,
                this.reasonCode,
                this.status,
                this.visaRdr);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AmountStage builder() {
        return new Builder();
    }

    public interface AmountStage {
        /**
         * <p>The disputed amount in the specified currency, formatted as a decimal.</p>
         */
        CurrencyStage amount(double amount);

        Builder from(DisputeListItem other);
    }

    public interface CurrencyStage {
        /**
         * <p>The three-letter ISO currency code for the disputed amount.</p>
         */
        IdStage currency(@NotNull Currencies currency);
    }

    public interface IdStage {
        /**
         * <p>The unique identifier for the dispute.</p>
         */
        StatusStage id(@NotNull String id);
    }

    public interface StatusStage {
        /**
         * <p>The current status of the dispute lifecycle, such as needs_response, under_review, won, or lost.</p>
         */
        VisaRdrStage status(@NotNull DisputeStatuses status);
    }

    public interface VisaRdrStage {
        /**
         * <p>Whether the dispute was automatically resolved through Visa Rapid Dispute Resolution (RDR).</p>
         */
        _FinalStage visaRdr(boolean visaRdr);
    }

    public interface _FinalStage {
        DisputeListItem build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The company that the dispute was filed against.</p>
         */
        _FinalStage company(Optional<DisputeListItemCompany> company);

        _FinalStage company(DisputeListItemCompany company);

        _FinalStage company(Nullable<DisputeListItemCompany> company);

        /**
         * <p>The datetime the dispute was created.</p>
         */
        _FinalStage createdAt(Optional<OffsetDateTime> createdAt);

        _FinalStage createdAt(OffsetDateTime createdAt);

        _FinalStage createdAt(Nullable<OffsetDateTime> createdAt);

        /**
         * <p>Whether the dispute evidence can still be edited and submitted.</p>
         */
        _FinalStage editable(Optional<Boolean> editable);

        _FinalStage editable(Boolean editable);

        _FinalStage editable(Nullable<Boolean> editable);

        /**
         * <p>The deadline by which dispute evidence must be submitted. Null if no response deadline is set.</p>
         */
        _FinalStage needsResponseBy(Optional<OffsetDateTime> needsResponseBy);

        _FinalStage needsResponseBy(OffsetDateTime needsResponseBy);

        _FinalStage needsResponseBy(Nullable<OffsetDateTime> needsResponseBy);

        /**
         * <p>The original payment that was disputed.</p>
         */
        _FinalStage payment(Optional<DisputeListItemPayment> payment);

        _FinalStage payment(DisputeListItemPayment payment);

        _FinalStage payment(Nullable<DisputeListItemPayment> payment);

        /**
         * <p>The plan associated with the disputed payment. Null if the dispute is not linked to a specific plan.</p>
         */
        _FinalStage plan(Optional<DisputeListItemPlan> plan);

        _FinalStage plan(DisputeListItemPlan plan);

        _FinalStage plan(Nullable<DisputeListItemPlan> plan);

        /**
         * <p>The product associated with the disputed payment. Null if the dispute is not linked to a specific product.</p>
         */
        _FinalStage product(Optional<DisputeListItemProduct> product);

        _FinalStage product(DisputeListItemProduct product);

        _FinalStage product(Nullable<DisputeListItemProduct> product);

        /**
         * <p>A human-readable reason for the dispute.</p>
         */
        _FinalStage reason(Optional<String> reason);

        _FinalStage reason(String reason);

        _FinalStage reason(Nullable<String> reason);

        /**
         * <p>The card network reason code for the dispute. Null when the payment processor did not provide one.</p>
         */
        _FinalStage reasonCode(Optional<String> reasonCode);

        _FinalStage reasonCode(String reasonCode);

        _FinalStage reasonCode(Nullable<String> reasonCode);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements AmountStage, CurrencyStage, IdStage, StatusStage, VisaRdrStage, _FinalStage {
        private double amount;

        private Currencies currency;

        private String id;

        private DisputeStatuses status;

        private boolean visaRdr;

        private Optional<String> reasonCode = Optional.empty();

        private Optional<String> reason = Optional.empty();

        private Optional<DisputeListItemProduct> product = Optional.empty();

        private Optional<DisputeListItemPlan> plan = Optional.empty();

        private Optional<DisputeListItemPayment> payment = Optional.empty();

        private Optional<OffsetDateTime> needsResponseBy = Optional.empty();

        private Optional<Boolean> editable = Optional.empty();

        private Optional<OffsetDateTime> createdAt = Optional.empty();

        private Optional<DisputeListItemCompany> company = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DisputeListItem other) {
            amount(other.getAmount());
            company(other.getCompany());
            createdAt(other.getCreatedAt());
            currency(other.getCurrency());
            editable(other.getEditable());
            id(other.getId());
            needsResponseBy(other.getNeedsResponseBy());
            payment(other.getPayment());
            plan(other.getPlan());
            product(other.getProduct());
            reason(other.getReason());
            reasonCode(other.getReasonCode());
            status(other.getStatus());
            visaRdr(other.getVisaRdr());
            return this;
        }

        /**
         * <p>The disputed amount in the specified currency, formatted as a decimal.</p>
         * <p>The disputed amount in the specified currency, formatted as a decimal.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("amount")
        public CurrencyStage amount(double amount) {
            this.amount = amount;
            return this;
        }

        /**
         * <p>The three-letter ISO currency code for the disputed amount.</p>
         * <p>The three-letter ISO currency code for the disputed amount.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("currency")
        public IdStage currency(@NotNull Currencies currency) {
            this.currency = Objects.requireNonNull(currency, "currency must not be null");
            return this;
        }

        /**
         * <p>The unique identifier for the dispute.</p>
         * <p>The unique identifier for the dispute.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public StatusStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The current status of the dispute lifecycle, such as needs_response, under_review, won, or lost.</p>
         * <p>The current status of the dispute lifecycle, such as needs_response, under_review, won, or lost.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public VisaRdrStage status(@NotNull DisputeStatuses status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>Whether the dispute was automatically resolved through Visa Rapid Dispute Resolution (RDR).</p>
         * <p>Whether the dispute was automatically resolved through Visa Rapid Dispute Resolution (RDR).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("visa_rdr")
        public _FinalStage visaRdr(boolean visaRdr) {
            this.visaRdr = visaRdr;
            return this;
        }

        /**
         * <p>The card network reason code for the dispute. Null when the payment processor did not provide one.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage reasonCode(Nullable<String> reasonCode) {
            if (reasonCode.isNull()) {
                this.reasonCode = null;
            } else if (reasonCode.isEmpty()) {
                this.reasonCode = Optional.empty();
            } else {
                this.reasonCode = Optional.of(reasonCode.get());
            }
            return this;
        }

        /**
         * <p>The card network reason code for the dispute. Null when the payment processor did not provide one.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage reasonCode(String reasonCode) {
            this.reasonCode = Optional.ofNullable(reasonCode);
            return this;
        }

        /**
         * <p>The card network reason code for the dispute. Null when the payment processor did not provide one.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "reason_code", nulls = Nulls.SKIP)
        public _FinalStage reasonCode(Optional<String> reasonCode) {
            this.reasonCode = reasonCode;
            return this;
        }

        /**
         * <p>A human-readable reason for the dispute.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage reason(Nullable<String> reason) {
            if (reason.isNull()) {
                this.reason = null;
            } else if (reason.isEmpty()) {
                this.reason = Optional.empty();
            } else {
                this.reason = Optional.of(reason.get());
            }
            return this;
        }

        /**
         * <p>A human-readable reason for the dispute.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage reason(String reason) {
            this.reason = Optional.ofNullable(reason);
            return this;
        }

        /**
         * <p>A human-readable reason for the dispute.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "reason", nulls = Nulls.SKIP)
        public _FinalStage reason(Optional<String> reason) {
            this.reason = reason;
            return this;
        }

        /**
         * <p>The product associated with the disputed payment. Null if the dispute is not linked to a specific product.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage product(Nullable<DisputeListItemProduct> product) {
            if (product.isNull()) {
                this.product = null;
            } else if (product.isEmpty()) {
                this.product = Optional.empty();
            } else {
                this.product = Optional.of(product.get());
            }
            return this;
        }

        /**
         * <p>The product associated with the disputed payment. Null if the dispute is not linked to a specific product.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage product(DisputeListItemProduct product) {
            this.product = Optional.ofNullable(product);
            return this;
        }

        /**
         * <p>The product associated with the disputed payment. Null if the dispute is not linked to a specific product.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "product", nulls = Nulls.SKIP)
        public _FinalStage product(Optional<DisputeListItemProduct> product) {
            this.product = product;
            return this;
        }

        /**
         * <p>The plan associated with the disputed payment. Null if the dispute is not linked to a specific plan.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage plan(Nullable<DisputeListItemPlan> plan) {
            if (plan.isNull()) {
                this.plan = null;
            } else if (plan.isEmpty()) {
                this.plan = Optional.empty();
            } else {
                this.plan = Optional.of(plan.get());
            }
            return this;
        }

        /**
         * <p>The plan associated with the disputed payment. Null if the dispute is not linked to a specific plan.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage plan(DisputeListItemPlan plan) {
            this.plan = Optional.ofNullable(plan);
            return this;
        }

        /**
         * <p>The plan associated with the disputed payment. Null if the dispute is not linked to a specific plan.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "plan", nulls = Nulls.SKIP)
        public _FinalStage plan(Optional<DisputeListItemPlan> plan) {
            this.plan = plan;
            return this;
        }

        /**
         * <p>The original payment that was disputed.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage payment(Nullable<DisputeListItemPayment> payment) {
            if (payment.isNull()) {
                this.payment = null;
            } else if (payment.isEmpty()) {
                this.payment = Optional.empty();
            } else {
                this.payment = Optional.of(payment.get());
            }
            return this;
        }

        /**
         * <p>The original payment that was disputed.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage payment(DisputeListItemPayment payment) {
            this.payment = Optional.ofNullable(payment);
            return this;
        }

        /**
         * <p>The original payment that was disputed.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "payment", nulls = Nulls.SKIP)
        public _FinalStage payment(Optional<DisputeListItemPayment> payment) {
            this.payment = payment;
            return this;
        }

        /**
         * <p>The deadline by which dispute evidence must be submitted. Null if no response deadline is set.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage needsResponseBy(Nullable<OffsetDateTime> needsResponseBy) {
            if (needsResponseBy.isNull()) {
                this.needsResponseBy = null;
            } else if (needsResponseBy.isEmpty()) {
                this.needsResponseBy = Optional.empty();
            } else {
                this.needsResponseBy = Optional.of(needsResponseBy.get());
            }
            return this;
        }

        /**
         * <p>The deadline by which dispute evidence must be submitted. Null if no response deadline is set.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage needsResponseBy(OffsetDateTime needsResponseBy) {
            this.needsResponseBy = Optional.ofNullable(needsResponseBy);
            return this;
        }

        /**
         * <p>The deadline by which dispute evidence must be submitted. Null if no response deadline is set.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "needs_response_by", nulls = Nulls.SKIP)
        public _FinalStage needsResponseBy(Optional<OffsetDateTime> needsResponseBy) {
            this.needsResponseBy = needsResponseBy;
            return this;
        }

        /**
         * <p>Whether the dispute evidence can still be edited and submitted.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage editable(Nullable<Boolean> editable) {
            if (editable.isNull()) {
                this.editable = null;
            } else if (editable.isEmpty()) {
                this.editable = Optional.empty();
            } else {
                this.editable = Optional.of(editable.get());
            }
            return this;
        }

        /**
         * <p>Whether the dispute evidence can still be edited and submitted.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage editable(Boolean editable) {
            this.editable = Optional.ofNullable(editable);
            return this;
        }

        /**
         * <p>Whether the dispute evidence can still be edited and submitted.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "editable", nulls = Nulls.SKIP)
        public _FinalStage editable(Optional<Boolean> editable) {
            this.editable = editable;
            return this;
        }

        /**
         * <p>The datetime the dispute was created.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage createdAt(Nullable<OffsetDateTime> createdAt) {
            if (createdAt.isNull()) {
                this.createdAt = null;
            } else if (createdAt.isEmpty()) {
                this.createdAt = Optional.empty();
            } else {
                this.createdAt = Optional.of(createdAt.get());
            }
            return this;
        }

        /**
         * <p>The datetime the dispute was created.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage createdAt(OffsetDateTime createdAt) {
            this.createdAt = Optional.ofNullable(createdAt);
            return this;
        }

        /**
         * <p>The datetime the dispute was created.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "created_at", nulls = Nulls.SKIP)
        public _FinalStage createdAt(Optional<OffsetDateTime> createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * <p>The company that the dispute was filed against.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage company(Nullable<DisputeListItemCompany> company) {
            if (company.isNull()) {
                this.company = null;
            } else if (company.isEmpty()) {
                this.company = Optional.empty();
            } else {
                this.company = Optional.of(company.get());
            }
            return this;
        }

        /**
         * <p>The company that the dispute was filed against.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage company(DisputeListItemCompany company) {
            this.company = Optional.ofNullable(company);
            return this;
        }

        /**
         * <p>The company that the dispute was filed against.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "company", nulls = Nulls.SKIP)
        public _FinalStage company(Optional<DisputeListItemCompany> company) {
            this.company = company;
            return this;
        }

        @java.lang.Override
        public DisputeListItem build() {
            return new DisputeListItem(
                    amount,
                    company,
                    createdAt,
                    currency,
                    editable,
                    id,
                    needsResponseBy,
                    payment,
                    plan,
                    product,
                    reason,
                    reasonCode,
                    status,
                    visaRdr,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
