/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DisputeEvidenceDocumentDocumentType {
    public static final DisputeEvidenceDocumentDocumentType DIGITAL_FULFILLMENT =
            new DisputeEvidenceDocumentDocumentType(Value.DIGITAL_FULFILLMENT, "digital_fulfillment");

    public static final DisputeEvidenceDocumentDocumentType RETURN_POLICY =
            new DisputeEvidenceDocumentDocumentType(Value.RETURN_POLICY, "return_policy");

    public static final DisputeEvidenceDocumentDocumentType SHIPPING_POLICY =
            new DisputeEvidenceDocumentDocumentType(Value.SHIPPING_POLICY, "shipping_policy");

    public static final DisputeEvidenceDocumentDocumentType CUSTOMER_ORDER_HISTORY =
            new DisputeEvidenceDocumentDocumentType(Value.CUSTOMER_ORDER_HISTORY, "customer_order_history");

    public static final DisputeEvidenceDocumentDocumentType SUBSCRIPTION =
            new DisputeEvidenceDocumentDocumentType(Value.SUBSCRIPTION, "subscription");

    public static final DisputeEvidenceDocumentDocumentType PRODUCT_IMAGE =
            new DisputeEvidenceDocumentDocumentType(Value.PRODUCT_IMAGE, "product_image");

    public static final DisputeEvidenceDocumentDocumentType PHYSICAL_FULFILLMENT =
            new DisputeEvidenceDocumentDocumentType(Value.PHYSICAL_FULFILLMENT, "physical_fulfillment");

    public static final DisputeEvidenceDocumentDocumentType CUSTOMER_SESSION =
            new DisputeEvidenceDocumentDocumentType(Value.CUSTOMER_SESSION, "customer_session");

    public static final DisputeEvidenceDocumentDocumentType PRIOR_TRANSACTIONS =
            new DisputeEvidenceDocumentDocumentType(Value.PRIOR_TRANSACTIONS, "prior_transactions");

    private final Value value;

    private final String string;

    DisputeEvidenceDocumentDocumentType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DisputeEvidenceDocumentDocumentType
                        && this.string.equals(((DisputeEvidenceDocumentDocumentType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DIGITAL_FULFILLMENT:
                return visitor.visitDigitalFulfillment();
            case RETURN_POLICY:
                return visitor.visitReturnPolicy();
            case SHIPPING_POLICY:
                return visitor.visitShippingPolicy();
            case CUSTOMER_ORDER_HISTORY:
                return visitor.visitCustomerOrderHistory();
            case SUBSCRIPTION:
                return visitor.visitSubscription();
            case PRODUCT_IMAGE:
                return visitor.visitProductImage();
            case PHYSICAL_FULFILLMENT:
                return visitor.visitPhysicalFulfillment();
            case CUSTOMER_SESSION:
                return visitor.visitCustomerSession();
            case PRIOR_TRANSACTIONS:
                return visitor.visitPriorTransactions();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DisputeEvidenceDocumentDocumentType valueOf(String value) {
        switch (value) {
            case "digital_fulfillment":
                return DIGITAL_FULFILLMENT;
            case "return_policy":
                return RETURN_POLICY;
            case "shipping_policy":
                return SHIPPING_POLICY;
            case "customer_order_history":
                return CUSTOMER_ORDER_HISTORY;
            case "subscription":
                return SUBSCRIPTION;
            case "product_image":
                return PRODUCT_IMAGE;
            case "physical_fulfillment":
                return PHYSICAL_FULFILLMENT;
            case "customer_session":
                return CUSTOMER_SESSION;
            case "prior_transactions":
                return PRIOR_TRANSACTIONS;
            default:
                return new DisputeEvidenceDocumentDocumentType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        RETURN_POLICY,

        SHIPPING_POLICY,

        PHYSICAL_FULFILLMENT,

        CUSTOMER_ORDER_HISTORY,

        PRODUCT_IMAGE,

        PRIOR_TRANSACTIONS,

        CUSTOMER_SESSION,

        DIGITAL_FULFILLMENT,

        SUBSCRIPTION,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitReturnPolicy();

        T visitShippingPolicy();

        T visitPhysicalFulfillment();

        T visitCustomerOrderHistory();

        T visitProductImage();

        T visitPriorTransactions();

        T visitCustomerSession();

        T visitDigitalFulfillment();

        T visitSubscription();

        T visitUnknown(String unknownType);
    }
}
