/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InvoiceListItemCurrentPlan.Builder.class)
public final class InvoiceListItemCurrentPlan {
    private final Currencies currency;

    private final String formattedPrice;

    private final String id;

    private final Map<String, Object> additionalProperties;

    private InvoiceListItemCurrentPlan(
            Currencies currency, String formattedPrice, String id, Map<String, Object> additionalProperties) {
        this.currency = currency;
        this.formattedPrice = formattedPrice;
        this.id = id;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The currency used for all prices on this plan (e.g., 'usd', 'eur'). All monetary amounts on the plan are denominated in this currency.
     */
    @JsonProperty("currency")
    public Currencies getCurrency() {
        return currency;
    }

    /**
     * @return The formatted price (including currency) for the plan.
     */
    @JsonProperty("formatted_price")
    public String getFormattedPrice() {
        return formattedPrice;
    }

    /**
     * @return The unique identifier for the plan.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InvoiceListItemCurrentPlan && equalTo((InvoiceListItemCurrentPlan) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InvoiceListItemCurrentPlan other) {
        return currency.equals(other.currency) && formattedPrice.equals(other.formattedPrice) && id.equals(other.id);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.currency, this.formattedPrice, this.id);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CurrencyStage builder() {
        return new Builder();
    }

    public interface CurrencyStage {
        /**
         * <p>The currency used for all prices on this plan (e.g., 'usd', 'eur'). All monetary amounts on the plan are denominated in this currency.</p>
         */
        FormattedPriceStage currency(@NotNull Currencies currency);

        Builder from(InvoiceListItemCurrentPlan other);
    }

    public interface FormattedPriceStage {
        /**
         * <p>The formatted price (including currency) for the plan.</p>
         */
        IdStage formattedPrice(@NotNull String formattedPrice);
    }

    public interface IdStage {
        /**
         * <p>The unique identifier for the plan.</p>
         */
        _FinalStage id(@NotNull String id);
    }

    public interface _FinalStage {
        InvoiceListItemCurrentPlan build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CurrencyStage, FormattedPriceStage, IdStage, _FinalStage {
        private Currencies currency;

        private String formattedPrice;

        private String id;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(InvoiceListItemCurrentPlan other) {
            currency(other.getCurrency());
            formattedPrice(other.getFormattedPrice());
            id(other.getId());
            return this;
        }

        /**
         * <p>The currency used for all prices on this plan (e.g., 'usd', 'eur'). All monetary amounts on the plan are denominated in this currency.</p>
         * <p>The currency used for all prices on this plan (e.g., 'usd', 'eur'). All monetary amounts on the plan are denominated in this currency.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("currency")
        public FormattedPriceStage currency(@NotNull Currencies currency) {
            this.currency = Objects.requireNonNull(currency, "currency must not be null");
            return this;
        }

        /**
         * <p>The formatted price (including currency) for the plan.</p>
         * <p>The formatted price (including currency) for the plan.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("formatted_price")
        public IdStage formattedPrice(@NotNull String formattedPrice) {
            this.formattedPrice = Objects.requireNonNull(formattedPrice, "formattedPrice must not be null");
            return this;
        }

        /**
         * <p>The unique identifier for the plan.</p>
         * <p>The unique identifier for the plan.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public _FinalStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        public InvoiceListItemCurrentPlan build() {
            return new InvoiceListItemCurrentPlan(currency, formattedPrice, id, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
