/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.Nullable;
import com.whop.api.core.NullableNonemptyFilter;
import com.whop.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PaymentLastPaymentError.Builder.class)
public final class PaymentLastPaymentError {
    private final Optional<String> code;

    private final Optional<PaymentLastPaymentErrorDeclineCode> declineCode;

    private final Optional<String> message;

    private final Map<String, Object> additionalProperties;

    private PaymentLastPaymentError(
            Optional<String> code,
            Optional<PaymentLastPaymentErrorDeclineCode> declineCode,
            Optional<String> message,
            Map<String, Object> additionalProperties) {
        this.code = code;
        this.declineCode = declineCode;
        this.message = message;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A machine-readable classification of the failure.
     */
    @JsonIgnore
    public Optional<String> getCode() {
        if (code == null) {
            return Optional.empty();
        }
        return code;
    }

    /**
     * @return The reason the payment was declined.
     */
    @JsonIgnore
    public Optional<PaymentLastPaymentErrorDeclineCode> getDeclineCode() {
        if (declineCode == null) {
            return Optional.empty();
        }
        return declineCode;
    }

    /**
     * @return A human-readable explanation of the failure.
     */
    @JsonIgnore
    public Optional<String> getMessage() {
        if (message == null) {
            return Optional.empty();
        }
        return message;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("code")
    private Optional<String> _getCode() {
        return code;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("decline_code")
    private Optional<PaymentLastPaymentErrorDeclineCode> _getDeclineCode() {
        return declineCode;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("message")
    private Optional<String> _getMessage() {
        return message;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PaymentLastPaymentError && equalTo((PaymentLastPaymentError) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PaymentLastPaymentError other) {
        return code.equals(other.code) && declineCode.equals(other.declineCode) && message.equals(other.message);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.code, this.declineCode, this.message);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> code = Optional.empty();

        private Optional<PaymentLastPaymentErrorDeclineCode> declineCode = Optional.empty();

        private Optional<String> message = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(PaymentLastPaymentError other) {
            code(other.getCode());
            declineCode(other.getDeclineCode());
            message(other.getMessage());
            return this;
        }

        /**
         * <p>A machine-readable classification of the failure.</p>
         */
        @JsonSetter(value = "code", nulls = Nulls.SKIP)
        public Builder code(Optional<String> code) {
            this.code = code;
            return this;
        }

        public Builder code(String code) {
            this.code = Optional.ofNullable(code);
            return this;
        }

        public Builder code(Nullable<String> code) {
            if (code.isNull()) {
                this.code = null;
            } else if (code.isEmpty()) {
                this.code = Optional.empty();
            } else {
                this.code = Optional.of(code.get());
            }
            return this;
        }

        /**
         * <p>The reason the payment was declined.</p>
         */
        @JsonSetter(value = "decline_code", nulls = Nulls.SKIP)
        public Builder declineCode(Optional<PaymentLastPaymentErrorDeclineCode> declineCode) {
            this.declineCode = declineCode;
            return this;
        }

        public Builder declineCode(PaymentLastPaymentErrorDeclineCode declineCode) {
            this.declineCode = Optional.ofNullable(declineCode);
            return this;
        }

        public Builder declineCode(Nullable<PaymentLastPaymentErrorDeclineCode> declineCode) {
            if (declineCode.isNull()) {
                this.declineCode = null;
            } else if (declineCode.isEmpty()) {
                this.declineCode = Optional.empty();
            } else {
                this.declineCode = Optional.of(declineCode.get());
            }
            return this;
        }

        /**
         * <p>A human-readable explanation of the failure.</p>
         */
        @JsonSetter(value = "message", nulls = Nulls.SKIP)
        public Builder message(Optional<String> message) {
            this.message = message;
            return this;
        }

        public Builder message(String message) {
            this.message = Optional.ofNullable(message);
            return this;
        }

        public Builder message(Nullable<String> message) {
            if (message.isNull()) {
                this.message = null;
            } else if (message.isEmpty()) {
                this.message = Optional.empty();
            } else {
                this.message = Optional.of(message.get());
            }
            return this;
        }

        public PaymentLastPaymentError build() {
            return new PaymentLastPaymentError(code, declineCode, message, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
