/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PaymentMethodListItemUsBankAccountPaymentMethodIcons.Builder.class)
public final class PaymentMethodListItemUsBankAccountPaymentMethodIcons {
    private final PaymentMethodListItemUsBankAccountPaymentMethodIconsCard card;

    private final PaymentMethodListItemUsBankAccountPaymentMethodIconsSquare square;

    private final Map<String, Object> additionalProperties;

    private PaymentMethodListItemUsBankAccountPaymentMethodIcons(
            PaymentMethodListItemUsBankAccountPaymentMethodIconsCard card,
            PaymentMethodListItemUsBankAccountPaymentMethodIconsSquare square,
            Map<String, Object> additionalProperties) {
        this.card = card;
        this.square = square;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The credit-card-proportioned tile (48x30).
     */
    @JsonProperty("card")
    public PaymentMethodListItemUsBankAccountPaymentMethodIconsCard getCard() {
        return card;
    }

    /**
     * @return The square tile (32x32).
     */
    @JsonProperty("square")
    public PaymentMethodListItemUsBankAccountPaymentMethodIconsSquare getSquare() {
        return square;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PaymentMethodListItemUsBankAccountPaymentMethodIcons
                && equalTo((PaymentMethodListItemUsBankAccountPaymentMethodIcons) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PaymentMethodListItemUsBankAccountPaymentMethodIcons other) {
        return card.equals(other.card) && square.equals(other.square);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.card, this.square);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CardStage builder() {
        return new Builder();
    }

    public interface CardStage {
        /**
         * <p>The credit-card-proportioned tile (48x30).</p>
         */
        SquareStage card(@NotNull PaymentMethodListItemUsBankAccountPaymentMethodIconsCard card);

        Builder from(PaymentMethodListItemUsBankAccountPaymentMethodIcons other);
    }

    public interface SquareStage {
        /**
         * <p>The square tile (32x32).</p>
         */
        _FinalStage square(@NotNull PaymentMethodListItemUsBankAccountPaymentMethodIconsSquare square);
    }

    public interface _FinalStage {
        PaymentMethodListItemUsBankAccountPaymentMethodIcons build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CardStage, SquareStage, _FinalStage {
        private PaymentMethodListItemUsBankAccountPaymentMethodIconsCard card;

        private PaymentMethodListItemUsBankAccountPaymentMethodIconsSquare square;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PaymentMethodListItemUsBankAccountPaymentMethodIcons other) {
            card(other.getCard());
            square(other.getSquare());
            return this;
        }

        /**
         * <p>The credit-card-proportioned tile (48x30).</p>
         * <p>The credit-card-proportioned tile (48x30).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("card")
        public SquareStage card(@NotNull PaymentMethodListItemUsBankAccountPaymentMethodIconsCard card) {
            this.card = Objects.requireNonNull(card, "card must not be null");
            return this;
        }

        /**
         * <p>The square tile (32x32).</p>
         * <p>The square tile (32x32).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("square")
        public _FinalStage square(@NotNull PaymentMethodListItemUsBankAccountPaymentMethodIconsSquare square) {
            this.square = Objects.requireNonNull(square, "square must not be null");
            return this;
        }

        @java.lang.Override
        public PaymentMethodListItemUsBankAccountPaymentMethodIcons build() {
            return new PaymentMethodListItemUsBankAccountPaymentMethodIcons(card, square, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
