/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.Nullable;
import com.whop.api.core.NullableNonemptyFilter;
import com.whop.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PaymentResolutionsItem.Builder.class)
public final class PaymentResolutionsItem {
    private final boolean customerAppealed;

    private final List<ResolutionCenterCaseCustomerResponses> customerResponseActions;

    private final Optional<OffsetDateTime> dueDate;

    private final String id;

    private final ResolutionCenterCaseIssueTypes issue;

    private final boolean merchantAppealed;

    private final List<ResolutionCenterCaseMerchantResponses> merchantResponseActions;

    private final List<ResolutionCenterCasePlatformResponses> platformResponseActions;

    private final ResolutionCenterCaseStatuses status;

    private final Map<String, Object> additionalProperties;

    private PaymentResolutionsItem(
            boolean customerAppealed,
            List<ResolutionCenterCaseCustomerResponses> customerResponseActions,
            Optional<OffsetDateTime> dueDate,
            String id,
            ResolutionCenterCaseIssueTypes issue,
            boolean merchantAppealed,
            List<ResolutionCenterCaseMerchantResponses> merchantResponseActions,
            List<ResolutionCenterCasePlatformResponses> platformResponseActions,
            ResolutionCenterCaseStatuses status,
            Map<String, Object> additionalProperties) {
        this.customerAppealed = customerAppealed;
        this.customerResponseActions = customerResponseActions;
        this.dueDate = dueDate;
        this.id = id;
        this.issue = issue;
        this.merchantAppealed = merchantAppealed;
        this.merchantResponseActions = merchantResponseActions;
        this.platformResponseActions = platformResponseActions;
        this.status = status;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Whether the customer has filed an appeal after the initial resolution decision.
     */
    @JsonProperty("customer_appealed")
    public boolean getCustomerAppealed() {
        return customerAppealed;
    }

    /**
     * @return The list of actions currently available to the customer.
     */
    @JsonProperty("customer_response_actions")
    public List<ResolutionCenterCaseCustomerResponses> getCustomerResponseActions() {
        return customerResponseActions;
    }

    /**
     * @return The deadline by which the next response is required. Null if no deadline is currently active. As a Unix timestamp.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getDueDate() {
        if (dueDate == null) {
            return Optional.empty();
        }
        return dueDate;
    }

    /**
     * @return The unique identifier for the resolution.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return The category of the dispute.
     */
    @JsonProperty("issue")
    public ResolutionCenterCaseIssueTypes getIssue() {
        return issue;
    }

    /**
     * @return Whether the merchant has filed an appeal after the initial resolution decision.
     */
    @JsonProperty("merchant_appealed")
    public boolean getMerchantAppealed() {
        return merchantAppealed;
    }

    /**
     * @return The list of actions currently available to the merchant.
     */
    @JsonProperty("merchant_response_actions")
    public List<ResolutionCenterCaseMerchantResponses> getMerchantResponseActions() {
        return merchantResponseActions;
    }

    /**
     * @return The list of actions currently available to the Whop platform for moderating this resolution.
     */
    @JsonProperty("platform_response_actions")
    public List<ResolutionCenterCasePlatformResponses> getPlatformResponseActions() {
        return platformResponseActions;
    }

    /**
     * @return The current status of the resolution case, indicating which party needs to respond or if the case is closed.
     */
    @JsonProperty("status")
    public ResolutionCenterCaseStatuses getStatus() {
        return status;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("due_date")
    private Optional<OffsetDateTime> _getDueDate() {
        return dueDate;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PaymentResolutionsItem && equalTo((PaymentResolutionsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PaymentResolutionsItem other) {
        return customerAppealed == other.customerAppealed
                && customerResponseActions.equals(other.customerResponseActions)
                && dueDate.equals(other.dueDate)
                && id.equals(other.id)
                && issue.equals(other.issue)
                && merchantAppealed == other.merchantAppealed
                && merchantResponseActions.equals(other.merchantResponseActions)
                && platformResponseActions.equals(other.platformResponseActions)
                && status.equals(other.status);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.customerAppealed,
                this.customerResponseActions,
                this.dueDate,
                this.id,
                this.issue,
                this.merchantAppealed,
                this.merchantResponseActions,
                this.platformResponseActions,
                this.status);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CustomerAppealedStage builder() {
        return new Builder();
    }

    public interface CustomerAppealedStage {
        /**
         * <p>Whether the customer has filed an appeal after the initial resolution decision.</p>
         */
        IdStage customerAppealed(boolean customerAppealed);

        Builder from(PaymentResolutionsItem other);
    }

    public interface IdStage {
        /**
         * <p>The unique identifier for the resolution.</p>
         */
        IssueStage id(@NotNull String id);
    }

    public interface IssueStage {
        /**
         * <p>The category of the dispute.</p>
         */
        MerchantAppealedStage issue(@NotNull ResolutionCenterCaseIssueTypes issue);
    }

    public interface MerchantAppealedStage {
        /**
         * <p>Whether the merchant has filed an appeal after the initial resolution decision.</p>
         */
        StatusStage merchantAppealed(boolean merchantAppealed);
    }

    public interface StatusStage {
        /**
         * <p>The current status of the resolution case, indicating which party needs to respond or if the case is closed.</p>
         */
        _FinalStage status(@NotNull ResolutionCenterCaseStatuses status);
    }

    public interface _FinalStage {
        PaymentResolutionsItem build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The list of actions currently available to the customer.</p>
         */
        _FinalStage customerResponseActions(List<ResolutionCenterCaseCustomerResponses> customerResponseActions);

        _FinalStage addCustomerResponseActions(ResolutionCenterCaseCustomerResponses customerResponseActions);

        _FinalStage addAllCustomerResponseActions(List<ResolutionCenterCaseCustomerResponses> customerResponseActions);

        /**
         * <p>The deadline by which the next response is required. Null if no deadline is currently active. As a Unix timestamp.</p>
         */
        _FinalStage dueDate(Optional<OffsetDateTime> dueDate);

        _FinalStage dueDate(OffsetDateTime dueDate);

        _FinalStage dueDate(Nullable<OffsetDateTime> dueDate);

        /**
         * <p>The list of actions currently available to the merchant.</p>
         */
        _FinalStage merchantResponseActions(List<ResolutionCenterCaseMerchantResponses> merchantResponseActions);

        _FinalStage addMerchantResponseActions(ResolutionCenterCaseMerchantResponses merchantResponseActions);

        _FinalStage addAllMerchantResponseActions(List<ResolutionCenterCaseMerchantResponses> merchantResponseActions);

        /**
         * <p>The list of actions currently available to the Whop platform for moderating this resolution.</p>
         */
        _FinalStage platformResponseActions(List<ResolutionCenterCasePlatformResponses> platformResponseActions);

        _FinalStage addPlatformResponseActions(ResolutionCenterCasePlatformResponses platformResponseActions);

        _FinalStage addAllPlatformResponseActions(List<ResolutionCenterCasePlatformResponses> platformResponseActions);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements CustomerAppealedStage, IdStage, IssueStage, MerchantAppealedStage, StatusStage, _FinalStage {
        private boolean customerAppealed;

        private String id;

        private ResolutionCenterCaseIssueTypes issue;

        private boolean merchantAppealed;

        private ResolutionCenterCaseStatuses status;

        private List<ResolutionCenterCasePlatformResponses> platformResponseActions = new ArrayList<>();

        private List<ResolutionCenterCaseMerchantResponses> merchantResponseActions = new ArrayList<>();

        private Optional<OffsetDateTime> dueDate = Optional.empty();

        private List<ResolutionCenterCaseCustomerResponses> customerResponseActions = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PaymentResolutionsItem other) {
            customerAppealed(other.getCustomerAppealed());
            customerResponseActions(other.getCustomerResponseActions());
            dueDate(other.getDueDate());
            id(other.getId());
            issue(other.getIssue());
            merchantAppealed(other.getMerchantAppealed());
            merchantResponseActions(other.getMerchantResponseActions());
            platformResponseActions(other.getPlatformResponseActions());
            status(other.getStatus());
            return this;
        }

        /**
         * <p>Whether the customer has filed an appeal after the initial resolution decision.</p>
         * <p>Whether the customer has filed an appeal after the initial resolution decision.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("customer_appealed")
        public IdStage customerAppealed(boolean customerAppealed) {
            this.customerAppealed = customerAppealed;
            return this;
        }

        /**
         * <p>The unique identifier for the resolution.</p>
         * <p>The unique identifier for the resolution.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public IssueStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The category of the dispute.</p>
         * <p>The category of the dispute.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("issue")
        public MerchantAppealedStage issue(@NotNull ResolutionCenterCaseIssueTypes issue) {
            this.issue = Objects.requireNonNull(issue, "issue must not be null");
            return this;
        }

        /**
         * <p>Whether the merchant has filed an appeal after the initial resolution decision.</p>
         * <p>Whether the merchant has filed an appeal after the initial resolution decision.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("merchant_appealed")
        public StatusStage merchantAppealed(boolean merchantAppealed) {
            this.merchantAppealed = merchantAppealed;
            return this;
        }

        /**
         * <p>The current status of the resolution case, indicating which party needs to respond or if the case is closed.</p>
         * <p>The current status of the resolution case, indicating which party needs to respond or if the case is closed.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public _FinalStage status(@NotNull ResolutionCenterCaseStatuses status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>The list of actions currently available to the Whop platform for moderating this resolution.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllPlatformResponseActions(
                List<ResolutionCenterCasePlatformResponses> platformResponseActions) {
            if (platformResponseActions != null) {
                this.platformResponseActions.addAll(platformResponseActions);
            }
            return this;
        }

        /**
         * <p>The list of actions currently available to the Whop platform for moderating this resolution.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addPlatformResponseActions(ResolutionCenterCasePlatformResponses platformResponseActions) {
            this.platformResponseActions.add(platformResponseActions);
            return this;
        }

        /**
         * <p>The list of actions currently available to the Whop platform for moderating this resolution.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "platform_response_actions", nulls = Nulls.SKIP)
        public _FinalStage platformResponseActions(
                List<ResolutionCenterCasePlatformResponses> platformResponseActions) {
            this.platformResponseActions.clear();
            if (platformResponseActions != null) {
                this.platformResponseActions.addAll(platformResponseActions);
            }
            return this;
        }

        /**
         * <p>The list of actions currently available to the merchant.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllMerchantResponseActions(
                List<ResolutionCenterCaseMerchantResponses> merchantResponseActions) {
            if (merchantResponseActions != null) {
                this.merchantResponseActions.addAll(merchantResponseActions);
            }
            return this;
        }

        /**
         * <p>The list of actions currently available to the merchant.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addMerchantResponseActions(ResolutionCenterCaseMerchantResponses merchantResponseActions) {
            this.merchantResponseActions.add(merchantResponseActions);
            return this;
        }

        /**
         * <p>The list of actions currently available to the merchant.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "merchant_response_actions", nulls = Nulls.SKIP)
        public _FinalStage merchantResponseActions(
                List<ResolutionCenterCaseMerchantResponses> merchantResponseActions) {
            this.merchantResponseActions.clear();
            if (merchantResponseActions != null) {
                this.merchantResponseActions.addAll(merchantResponseActions);
            }
            return this;
        }

        /**
         * <p>The deadline by which the next response is required. Null if no deadline is currently active. As a Unix timestamp.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage dueDate(Nullable<OffsetDateTime> dueDate) {
            if (dueDate.isNull()) {
                this.dueDate = null;
            } else if (dueDate.isEmpty()) {
                this.dueDate = Optional.empty();
            } else {
                this.dueDate = Optional.of(dueDate.get());
            }
            return this;
        }

        /**
         * <p>The deadline by which the next response is required. Null if no deadline is currently active. As a Unix timestamp.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage dueDate(OffsetDateTime dueDate) {
            this.dueDate = Optional.ofNullable(dueDate);
            return this;
        }

        /**
         * <p>The deadline by which the next response is required. Null if no deadline is currently active. As a Unix timestamp.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "due_date", nulls = Nulls.SKIP)
        public _FinalStage dueDate(Optional<OffsetDateTime> dueDate) {
            this.dueDate = dueDate;
            return this;
        }

        /**
         * <p>The list of actions currently available to the customer.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllCustomerResponseActions(
                List<ResolutionCenterCaseCustomerResponses> customerResponseActions) {
            if (customerResponseActions != null) {
                this.customerResponseActions.addAll(customerResponseActions);
            }
            return this;
        }

        /**
         * <p>The list of actions currently available to the customer.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addCustomerResponseActions(ResolutionCenterCaseCustomerResponses customerResponseActions) {
            this.customerResponseActions.add(customerResponseActions);
            return this;
        }

        /**
         * <p>The list of actions currently available to the customer.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "customer_response_actions", nulls = Nulls.SKIP)
        public _FinalStage customerResponseActions(
                List<ResolutionCenterCaseCustomerResponses> customerResponseActions) {
            this.customerResponseActions.clear();
            if (customerResponseActions != null) {
                this.customerResponseActions.addAll(customerResponseActions);
            }
            return this;
        }

        @java.lang.Override
        public PaymentResolutionsItem build() {
            return new PaymentResolutionsItem(
                    customerAppealed,
                    customerResponseActions,
                    dueDate,
                    id,
                    issue,
                    merchantAppealed,
                    merchantResponseActions,
                    platformResponseActions,
                    status,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
