/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PaymentMethodListItemIdealPaymentMethod.Builder.class)
public final class PaymentMethodListItemIdealPaymentMethod {
    private final OffsetDateTime createdAt;

    private final PaymentMethodListItemIdealPaymentMethodIcons icons;

    private final String id;

    private final PaymentMethodListItemIdealPaymentMethodIdeal ideal;

    private final PaymentMethodTypes paymentMethodType;

    private final Map<String, Object> additionalProperties;

    private PaymentMethodListItemIdealPaymentMethod(
            OffsetDateTime createdAt,
            PaymentMethodListItemIdealPaymentMethodIcons icons,
            String id,
            PaymentMethodListItemIdealPaymentMethodIdeal ideal,
            PaymentMethodTypes paymentMethodType,
            Map<String, Object> additionalProperties) {
        this.createdAt = createdAt;
        this.icons = icons;
        this.id = id;
        this.ideal = ideal;
        this.paymentMethodType = paymentMethodType;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The time of the event in ISO 8601 UTC format with millisecond precision
     */
    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Every rendition of the icon to display this payment method with. A saved card carries its brand's icon (Visa, Mastercard, ...) rather than the generic card art.
     */
    @JsonProperty("icons")
    public PaymentMethodListItemIdealPaymentMethodIcons getIcons() {
        return icons;
    }

    /**
     * @return Represents a unique identifier that is Base64 obfuscated. It is often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as <code>&quot;VXNlci0xMA==&quot;</code>) or integer (such as <code>4</code>) input value will be accepted as an ID.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return The iDEAL-specific details for this payment method, including bank name and BIC.
     */
    @JsonProperty("ideal")
    public PaymentMethodListItemIdealPaymentMethodIdeal getIdeal() {
        return ideal;
    }

    /**
     * @return The type of payment instrument stored on file (e.g., card, us_bank_account, cashapp, ideal, sepa_debit).
     */
    @JsonProperty("payment_method_type")
    public PaymentMethodTypes getPaymentMethodType() {
        return paymentMethodType;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PaymentMethodListItemIdealPaymentMethod
                && equalTo((PaymentMethodListItemIdealPaymentMethod) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PaymentMethodListItemIdealPaymentMethod other) {
        return createdAt.equals(other.createdAt)
                && icons.equals(other.icons)
                && id.equals(other.id)
                && ideal.equals(other.ideal)
                && paymentMethodType.equals(other.paymentMethodType);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.createdAt, this.icons, this.id, this.ideal, this.paymentMethodType);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CreatedAtStage builder() {
        return new Builder();
    }

    public interface CreatedAtStage {
        /**
         * <p>The time of the event in ISO 8601 UTC format with millisecond precision</p>
         */
        IconsStage createdAt(@NotNull OffsetDateTime createdAt);

        Builder from(PaymentMethodListItemIdealPaymentMethod other);
    }

    public interface IconsStage {
        /**
         * <p>Every rendition of the icon to display this payment method with. A saved card carries its brand's icon (Visa, Mastercard, ...) rather than the generic card art.</p>
         */
        IdStage icons(@NotNull PaymentMethodListItemIdealPaymentMethodIcons icons);
    }

    public interface IdStage {
        /**
         * <p>Represents a unique identifier that is Base64 obfuscated. It is often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as <code>&quot;VXNlci0xMA==&quot;</code>) or integer (such as <code>4</code>) input value will be accepted as an ID.</p>
         */
        IdealStage id(@NotNull String id);
    }

    public interface IdealStage {
        /**
         * <p>The iDEAL-specific details for this payment method, including bank name and BIC.</p>
         */
        PaymentMethodTypeStage ideal(@NotNull PaymentMethodListItemIdealPaymentMethodIdeal ideal);
    }

    public interface PaymentMethodTypeStage {
        /**
         * <p>The type of payment instrument stored on file (e.g., card, us_bank_account, cashapp, ideal, sepa_debit).</p>
         */
        _FinalStage paymentMethodType(@NotNull PaymentMethodTypes paymentMethodType);
    }

    public interface _FinalStage {
        PaymentMethodListItemIdealPaymentMethod build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements CreatedAtStage, IconsStage, IdStage, IdealStage, PaymentMethodTypeStage, _FinalStage {
        private OffsetDateTime createdAt;

        private PaymentMethodListItemIdealPaymentMethodIcons icons;

        private String id;

        private PaymentMethodListItemIdealPaymentMethodIdeal ideal;

        private PaymentMethodTypes paymentMethodType;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PaymentMethodListItemIdealPaymentMethod other) {
            createdAt(other.getCreatedAt());
            icons(other.getIcons());
            id(other.getId());
            ideal(other.getIdeal());
            paymentMethodType(other.getPaymentMethodType());
            return this;
        }

        /**
         * <p>The time of the event in ISO 8601 UTC format with millisecond precision</p>
         * <p>The time of the event in ISO 8601 UTC format with millisecond precision</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public IconsStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>Every rendition of the icon to display this payment method with. A saved card carries its brand's icon (Visa, Mastercard, ...) rather than the generic card art.</p>
         * <p>Every rendition of the icon to display this payment method with. A saved card carries its brand's icon (Visa, Mastercard, ...) rather than the generic card art.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("icons")
        public IdStage icons(@NotNull PaymentMethodListItemIdealPaymentMethodIcons icons) {
            this.icons = Objects.requireNonNull(icons, "icons must not be null");
            return this;
        }

        /**
         * <p>Represents a unique identifier that is Base64 obfuscated. It is often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as <code>&quot;VXNlci0xMA==&quot;</code>) or integer (such as <code>4</code>) input value will be accepted as an ID.</p>
         * <p>Represents a unique identifier that is Base64 obfuscated. It is often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as <code>&quot;VXNlci0xMA==&quot;</code>) or integer (such as <code>4</code>) input value will be accepted as an ID.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public IdealStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The iDEAL-specific details for this payment method, including bank name and BIC.</p>
         * <p>The iDEAL-specific details for this payment method, including bank name and BIC.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("ideal")
        public PaymentMethodTypeStage ideal(@NotNull PaymentMethodListItemIdealPaymentMethodIdeal ideal) {
            this.ideal = Objects.requireNonNull(ideal, "ideal must not be null");
            return this;
        }

        /**
         * <p>The type of payment instrument stored on file (e.g., card, us_bank_account, cashapp, ideal, sepa_debit).</p>
         * <p>The type of payment instrument stored on file (e.g., card, us_bank_account, cashapp, ideal, sepa_debit).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("payment_method_type")
        public _FinalStage paymentMethodType(@NotNull PaymentMethodTypes paymentMethodType) {
            this.paymentMethodType = Objects.requireNonNull(paymentMethodType, "paymentMethodType must not be null");
            return this;
        }

        @java.lang.Override
        public PaymentMethodListItemIdealPaymentMethod build() {
            return new PaymentMethodListItemIdealPaymentMethod(
                    createdAt, icons, id, ideal, paymentMethodType, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
