/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.Nullable;
import com.whop.api.core.NullableNonemptyFilter;
import com.whop.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ProductPublicPlan.Builder.class)
public final class ProductPublicPlan {
    private final Optional<Double> billingPeriod;

    private final Optional<Double> expirationDays;

    private final String id;

    private final Money initialPrice;

    private final ProductPublicPlanPlanType planType;

    private final Money renewalPrice;

    private final Optional<String> title;

    private final boolean unlimitedStock;

    private final ProductPublicPlanVisibility visibility;

    private final Map<String, Object> additionalProperties;

    private ProductPublicPlan(
            Optional<Double> billingPeriod,
            Optional<Double> expirationDays,
            String id,
            Money initialPrice,
            ProductPublicPlanPlanType planType,
            Money renewalPrice,
            Optional<String> title,
            boolean unlimitedStock,
            ProductPublicPlanVisibility visibility,
            Map<String, Object> additionalProperties) {
        this.billingPeriod = billingPeriod;
        this.expirationDays = expirationDays;
        this.id = id;
        this.initialPrice = initialPrice;
        this.planType = planType;
        this.renewalPrice = renewalPrice;
        this.title = title;
        this.unlimitedStock = unlimitedStock;
        this.visibility = visibility;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Number of days between recurring charges, such as 30 for monthly or 365 for annual. <code>null</code> for one-time plans.
     */
    @JsonIgnore
    public Optional<Double> getBillingPeriod() {
        if (billingPeriod == null) {
            return Optional.empty();
        }
        return billingPeriod;
    }

    /**
     * @return Access duration in days for expiration-based plans. <code>null</code> for plans without an expiration.
     */
    @JsonIgnore
    public Optional<Double> getExpirationDays() {
        if (expirationDays == null) {
            return Optional.empty();
        }
        return expirationDays;
    }

    /**
     * @return Plan ID, prefixed <code>plan_</code>.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return What checkout charges up front. <code>amount</code> is <code>&quot;0.00&quot;</code> when the first charge is free, such as a trial.
     */
    @JsonProperty("initial_price")
    public Money getInitialPrice() {
        return initialPrice;
    }

    /**
     * @return Billing model for this plan: <code>one_time</code> or <code>renewal</code>.
     */
    @JsonProperty("plan_type")
    public ProductPublicPlanPlanType getPlanType() {
        return planType;
    }

    /**
     * @return The recurring charge every <code>billing_period</code> days. <code>amount</code> is <code>&quot;0.00&quot;</code> for one-time plans.
     */
    @JsonProperty("renewal_price")
    public Money getRenewalPrice() {
        return renewalPrice;
    }

    /**
     * @return Plan display name shown to customers. <code>null</code> if no title has been set.
     */
    @JsonIgnore
    public Optional<String> getTitle() {
        if (title == null) {
            return Optional.empty();
        }
        return title;
    }

    /**
     * @return Whether the plan has unlimited stock.
     */
    @JsonProperty("unlimited_stock")
    public boolean getUnlimitedStock() {
        return unlimitedStock;
    }

    /**
     * @return Where this plan can be seen. <code>visible</code> plans appear on the product page.
     */
    @JsonProperty("visibility")
    public ProductPublicPlanVisibility getVisibility() {
        return visibility;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("billing_period")
    private Optional<Double> _getBillingPeriod() {
        return billingPeriod;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("expiration_days")
    private Optional<Double> _getExpirationDays() {
        return expirationDays;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("title")
    private Optional<String> _getTitle() {
        return title;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProductPublicPlan && equalTo((ProductPublicPlan) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ProductPublicPlan other) {
        return billingPeriod.equals(other.billingPeriod)
                && expirationDays.equals(other.expirationDays)
                && id.equals(other.id)
                && initialPrice.equals(other.initialPrice)
                && planType.equals(other.planType)
                && renewalPrice.equals(other.renewalPrice)
                && title.equals(other.title)
                && unlimitedStock == other.unlimitedStock
                && visibility.equals(other.visibility);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.billingPeriod,
                this.expirationDays,
                this.id,
                this.initialPrice,
                this.planType,
                this.renewalPrice,
                this.title,
                this.unlimitedStock,
                this.visibility);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Plan ID, prefixed <code>plan_</code>.</p>
         */
        InitialPriceStage id(@NotNull String id);

        Builder from(ProductPublicPlan other);
    }

    public interface InitialPriceStage {
        /**
         * <p>What checkout charges up front. <code>amount</code> is <code>&quot;0.00&quot;</code> when the first charge is free, such as a trial.</p>
         */
        PlanTypeStage initialPrice(@NotNull Money initialPrice);
    }

    public interface PlanTypeStage {
        /**
         * <p>Billing model for this plan: <code>one_time</code> or <code>renewal</code>.</p>
         */
        RenewalPriceStage planType(@NotNull ProductPublicPlanPlanType planType);
    }

    public interface RenewalPriceStage {
        /**
         * <p>The recurring charge every <code>billing_period</code> days. <code>amount</code> is <code>&quot;0.00&quot;</code> for one-time plans.</p>
         */
        UnlimitedStockStage renewalPrice(@NotNull Money renewalPrice);
    }

    public interface UnlimitedStockStage {
        /**
         * <p>Whether the plan has unlimited stock.</p>
         */
        VisibilityStage unlimitedStock(boolean unlimitedStock);
    }

    public interface VisibilityStage {
        /**
         * <p>Where this plan can be seen. <code>visible</code> plans appear on the product page.</p>
         */
        _FinalStage visibility(@NotNull ProductPublicPlanVisibility visibility);
    }

    public interface _FinalStage {
        ProductPublicPlan build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Number of days between recurring charges, such as 30 for monthly or 365 for annual. <code>null</code> for one-time plans.</p>
         */
        _FinalStage billingPeriod(Optional<Double> billingPeriod);

        _FinalStage billingPeriod(Double billingPeriod);

        _FinalStage billingPeriod(Nullable<Double> billingPeriod);

        /**
         * <p>Access duration in days for expiration-based plans. <code>null</code> for plans without an expiration.</p>
         */
        _FinalStage expirationDays(Optional<Double> expirationDays);

        _FinalStage expirationDays(Double expirationDays);

        _FinalStage expirationDays(Nullable<Double> expirationDays);

        /**
         * <p>Plan display name shown to customers. <code>null</code> if no title has been set.</p>
         */
        _FinalStage title(Optional<String> title);

        _FinalStage title(String title);

        _FinalStage title(Nullable<String> title);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage,
                    InitialPriceStage,
                    PlanTypeStage,
                    RenewalPriceStage,
                    UnlimitedStockStage,
                    VisibilityStage,
                    _FinalStage {
        private String id;

        private Money initialPrice;

        private ProductPublicPlanPlanType planType;

        private Money renewalPrice;

        private boolean unlimitedStock;

        private ProductPublicPlanVisibility visibility;

        private Optional<String> title = Optional.empty();

        private Optional<Double> expirationDays = Optional.empty();

        private Optional<Double> billingPeriod = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ProductPublicPlan other) {
            billingPeriod(other.getBillingPeriod());
            expirationDays(other.getExpirationDays());
            id(other.getId());
            initialPrice(other.getInitialPrice());
            planType(other.getPlanType());
            renewalPrice(other.getRenewalPrice());
            title(other.getTitle());
            unlimitedStock(other.getUnlimitedStock());
            visibility(other.getVisibility());
            return this;
        }

        /**
         * <p>Plan ID, prefixed <code>plan_</code>.</p>
         * <p>Plan ID, prefixed <code>plan_</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public InitialPriceStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>What checkout charges up front. <code>amount</code> is <code>&quot;0.00&quot;</code> when the first charge is free, such as a trial.</p>
         * <p>What checkout charges up front. <code>amount</code> is <code>&quot;0.00&quot;</code> when the first charge is free, such as a trial.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("initial_price")
        public PlanTypeStage initialPrice(@NotNull Money initialPrice) {
            this.initialPrice = Objects.requireNonNull(initialPrice, "initialPrice must not be null");
            return this;
        }

        /**
         * <p>Billing model for this plan: <code>one_time</code> or <code>renewal</code>.</p>
         * <p>Billing model for this plan: <code>one_time</code> or <code>renewal</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("plan_type")
        public RenewalPriceStage planType(@NotNull ProductPublicPlanPlanType planType) {
            this.planType = Objects.requireNonNull(planType, "planType must not be null");
            return this;
        }

        /**
         * <p>The recurring charge every <code>billing_period</code> days. <code>amount</code> is <code>&quot;0.00&quot;</code> for one-time plans.</p>
         * <p>The recurring charge every <code>billing_period</code> days. <code>amount</code> is <code>&quot;0.00&quot;</code> for one-time plans.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("renewal_price")
        public UnlimitedStockStage renewalPrice(@NotNull Money renewalPrice) {
            this.renewalPrice = Objects.requireNonNull(renewalPrice, "renewalPrice must not be null");
            return this;
        }

        /**
         * <p>Whether the plan has unlimited stock.</p>
         * <p>Whether the plan has unlimited stock.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("unlimited_stock")
        public VisibilityStage unlimitedStock(boolean unlimitedStock) {
            this.unlimitedStock = unlimitedStock;
            return this;
        }

        /**
         * <p>Where this plan can be seen. <code>visible</code> plans appear on the product page.</p>
         * <p>Where this plan can be seen. <code>visible</code> plans appear on the product page.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("visibility")
        public _FinalStage visibility(@NotNull ProductPublicPlanVisibility visibility) {
            this.visibility = Objects.requireNonNull(visibility, "visibility must not be null");
            return this;
        }

        /**
         * <p>Plan display name shown to customers. <code>null</code> if no title has been set.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage title(Nullable<String> title) {
            if (title.isNull()) {
                this.title = null;
            } else if (title.isEmpty()) {
                this.title = Optional.empty();
            } else {
                this.title = Optional.of(title.get());
            }
            return this;
        }

        /**
         * <p>Plan display name shown to customers. <code>null</code> if no title has been set.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage title(String title) {
            this.title = Optional.ofNullable(title);
            return this;
        }

        /**
         * <p>Plan display name shown to customers. <code>null</code> if no title has been set.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "title", nulls = Nulls.SKIP)
        public _FinalStage title(Optional<String> title) {
            this.title = title;
            return this;
        }

        /**
         * <p>Access duration in days for expiration-based plans. <code>null</code> for plans without an expiration.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage expirationDays(Nullable<Double> expirationDays) {
            if (expirationDays.isNull()) {
                this.expirationDays = null;
            } else if (expirationDays.isEmpty()) {
                this.expirationDays = Optional.empty();
            } else {
                this.expirationDays = Optional.of(expirationDays.get());
            }
            return this;
        }

        /**
         * <p>Access duration in days for expiration-based plans. <code>null</code> for plans without an expiration.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage expirationDays(Double expirationDays) {
            this.expirationDays = Optional.ofNullable(expirationDays);
            return this;
        }

        /**
         * <p>Access duration in days for expiration-based plans. <code>null</code> for plans without an expiration.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "expiration_days", nulls = Nulls.SKIP)
        public _FinalStage expirationDays(Optional<Double> expirationDays) {
            this.expirationDays = expirationDays;
            return this;
        }

        /**
         * <p>Number of days between recurring charges, such as 30 for monthly or 365 for annual. <code>null</code> for one-time plans.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage billingPeriod(Nullable<Double> billingPeriod) {
            if (billingPeriod.isNull()) {
                this.billingPeriod = null;
            } else if (billingPeriod.isEmpty()) {
                this.billingPeriod = Optional.empty();
            } else {
                this.billingPeriod = Optional.of(billingPeriod.get());
            }
            return this;
        }

        /**
         * <p>Number of days between recurring charges, such as 30 for monthly or 365 for annual. <code>null</code> for one-time plans.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage billingPeriod(Double billingPeriod) {
            this.billingPeriod = Optional.ofNullable(billingPeriod);
            return this;
        }

        /**
         * <p>Number of days between recurring charges, such as 30 for monthly or 365 for annual. <code>null</code> for one-time plans.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "billing_period", nulls = Nulls.SKIP)
        public _FinalStage billingPeriod(Optional<Double> billingPeriod) {
            this.billingPeriod = billingPeriod;
            return this;
        }

        @java.lang.Override
        public ProductPublicPlan build() {
            return new ProductPublicPlan(
                    billingPeriod,
                    expirationDays,
                    id,
                    initialPrice,
                    planType,
                    renewalPrice,
                    title,
                    unlimitedStock,
                    visibility,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
