/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SetupStatusStatus {
    public static final SetupStatusStatus SUCCEEDED = new SetupStatusStatus(Value.SUCCEEDED, "succeeded");

    public static final SetupStatusStatus PROCESSING = new SetupStatusStatus(Value.PROCESSING, "processing");

    public static final SetupStatusStatus CANCELED = new SetupStatusStatus(Value.CANCELED, "canceled");

    public static final SetupStatusStatus REQUIRES_ACTION =
            new SetupStatusStatus(Value.REQUIRES_ACTION, "requires_action");

    private final Value value;

    private final String string;

    SetupStatusStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SetupStatusStatus && this.string.equals(((SetupStatusStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SUCCEEDED:
                return visitor.visitSucceeded();
            case PROCESSING:
                return visitor.visitProcessing();
            case CANCELED:
                return visitor.visitCanceled();
            case REQUIRES_ACTION:
                return visitor.visitRequiresAction();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SetupStatusStatus valueOf(String value) {
        switch (value) {
            case "succeeded":
                return SUCCEEDED;
            case "processing":
                return PROCESSING;
            case "canceled":
                return CANCELED;
            case "requires_action":
                return REQUIRES_ACTION;
            default:
                return new SetupStatusStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PROCESSING,

        SUCCEEDED,

        CANCELED,

        REQUIRES_ACTION,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitProcessing();

        T visitSucceeded();

        T visitCanceled();

        T visitRequiresAction();

        T visitUnknown(String unknownType);
    }
}
