/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.Nullable;
import com.whop.api.core.NullableNonemptyFilter;
import com.whop.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SocialAccountLeadForm.Builder.class)
public final class SocialAccountLeadForm {
    private final Optional<AdLeadFormCompletion> completion;

    private final Optional<String> createdAt;

    private final Optional<AdLeadFormDisclaimer> disclaimer;

    private final SocialAccountLeadFormFormType formType;

    private final String id;

    private final Optional<AdLeadFormIntro> intro;

    private final Optional<String> locale;

    private final Optional<String> name;

    private final Optional<String> privacyPolicyLinkText;

    private final Optional<String> privacyPolicyUrl;

    private final List<String> questionLabels;

    private final List<AdLeadFormQuestion> questions;

    private final Map<String, Object> additionalProperties;

    private SocialAccountLeadForm(
            Optional<AdLeadFormCompletion> completion,
            Optional<String> createdAt,
            Optional<AdLeadFormDisclaimer> disclaimer,
            SocialAccountLeadFormFormType formType,
            String id,
            Optional<AdLeadFormIntro> intro,
            Optional<String> locale,
            Optional<String> name,
            Optional<String> privacyPolicyLinkText,
            Optional<String> privacyPolicyUrl,
            List<String> questionLabels,
            List<AdLeadFormQuestion> questions,
            Map<String, Object> additionalProperties) {
        this.completion = completion;
        this.createdAt = createdAt;
        this.disclaimer = disclaimer;
        this.formType = formType;
        this.id = id;
        this.intro = intro;
        this.locale = locale;
        this.name = name;
        this.privacyPolicyLinkText = privacyPolicyLinkText;
        this.privacyPolicyUrl = privacyPolicyUrl;
        this.questionLabels = questionLabels;
        this.questions = questions;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Screen shown after the form is submitted. <code>null</code> when the form has none.
     */
    @JsonIgnore
    public Optional<AdLeadFormCompletion> getCompletion() {
        if (completion == null) {
            return Optional.empty();
        }
        return completion;
    }

    /**
     * @return When the form was created, as an ISO 8601 timestamp.
     */
    @JsonIgnore
    public Optional<String> getCreatedAt() {
        if (createdAt == null) {
            return Optional.empty();
        }
        return createdAt;
    }

    /**
     * @return Custom consent disclaimer shown before submission. <code>null</code> when the form has none.
     */
    @JsonIgnore
    public Optional<AdLeadFormDisclaimer> getDisclaimer() {
        if (disclaimer == null) {
            return Optional.empty();
        }
        return disclaimer;
    }

    /**
     * @return <code>more_volume</code> is quickest to submit; <code>higher_intent</code> adds a confirmation step before submission.
     */
    @JsonProperty("form_type")
    public SocialAccountLeadFormFormType getFormType() {
        return formType;
    }

    /**
     * @return The ad platform's identifier for the form. Use it as lead_gen_form_id on an ad to reuse the form.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return Intro screen shown before the questions. <code>null</code> when the form has none.
     */
    @JsonIgnore
    public Optional<AdLeadFormIntro> getIntro() {
        if (intro == null) {
            return Optional.empty();
        }
        return intro;
    }

    /**
     * @return Language the form is shown in, such as en_US.
     */
    @JsonIgnore
    public Optional<String> getLocale() {
        if (locale == null) {
            return Optional.empty();
        }
        return locale;
    }

    /**
     * @return Advertiser-facing form name.
     */
    @JsonIgnore
    public Optional<String> getName() {
        if (name == null) {
            return Optional.empty();
        }
        return name;
    }

    /**
     * @return Custom link text for the privacy policy. <code>null</code> when the default is used.
     */
    @JsonIgnore
    public Optional<String> getPrivacyPolicyLinkText() {
        if (privacyPolicyLinkText == null) {
            return Optional.empty();
        }
        return privacyPolicyLinkText;
    }

    /**
     * @return Privacy policy URL configured on the form.
     */
    @JsonIgnore
    public Optional<String> getPrivacyPolicyUrl() {
        if (privacyPolicyUrl == null) {
            return Optional.empty();
        }
        return privacyPolicyUrl;
    }

    @JsonProperty("question_labels")
    public List<String> getQuestionLabels() {
        return questionLabels;
    }

    @JsonProperty("questions")
    public List<AdLeadFormQuestion> getQuestions() {
        return questions;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("completion")
    private Optional<AdLeadFormCompletion> _getCompletion() {
        return completion;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("created_at")
    private Optional<String> _getCreatedAt() {
        return createdAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("disclaimer")
    private Optional<AdLeadFormDisclaimer> _getDisclaimer() {
        return disclaimer;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("intro")
    private Optional<AdLeadFormIntro> _getIntro() {
        return intro;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("locale")
    private Optional<String> _getLocale() {
        return locale;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("name")
    private Optional<String> _getName() {
        return name;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("privacy_policy_link_text")
    private Optional<String> _getPrivacyPolicyLinkText() {
        return privacyPolicyLinkText;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("privacy_policy_url")
    private Optional<String> _getPrivacyPolicyUrl() {
        return privacyPolicyUrl;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SocialAccountLeadForm && equalTo((SocialAccountLeadForm) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SocialAccountLeadForm other) {
        return completion.equals(other.completion)
                && createdAt.equals(other.createdAt)
                && disclaimer.equals(other.disclaimer)
                && formType.equals(other.formType)
                && id.equals(other.id)
                && intro.equals(other.intro)
                && locale.equals(other.locale)
                && name.equals(other.name)
                && privacyPolicyLinkText.equals(other.privacyPolicyLinkText)
                && privacyPolicyUrl.equals(other.privacyPolicyUrl)
                && questionLabels.equals(other.questionLabels)
                && questions.equals(other.questions);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.completion,
                this.createdAt,
                this.disclaimer,
                this.formType,
                this.id,
                this.intro,
                this.locale,
                this.name,
                this.privacyPolicyLinkText,
                this.privacyPolicyUrl,
                this.questionLabels,
                this.questions);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FormTypeStage builder() {
        return new Builder();
    }

    public interface FormTypeStage {
        /**
         * <p><code>more_volume</code> is quickest to submit; <code>higher_intent</code> adds a confirmation step before submission.</p>
         */
        IdStage formType(@NotNull SocialAccountLeadFormFormType formType);

        Builder from(SocialAccountLeadForm other);
    }

    public interface IdStage {
        /**
         * <p>The ad platform's identifier for the form. Use it as lead_gen_form_id on an ad to reuse the form.</p>
         */
        _FinalStage id(@NotNull String id);
    }

    public interface _FinalStage {
        SocialAccountLeadForm build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Screen shown after the form is submitted. <code>null</code> when the form has none.</p>
         */
        _FinalStage completion(Optional<AdLeadFormCompletion> completion);

        _FinalStage completion(AdLeadFormCompletion completion);

        _FinalStage completion(Nullable<AdLeadFormCompletion> completion);

        /**
         * <p>When the form was created, as an ISO 8601 timestamp.</p>
         */
        _FinalStage createdAt(Optional<String> createdAt);

        _FinalStage createdAt(String createdAt);

        _FinalStage createdAt(Nullable<String> createdAt);

        /**
         * <p>Custom consent disclaimer shown before submission. <code>null</code> when the form has none.</p>
         */
        _FinalStage disclaimer(Optional<AdLeadFormDisclaimer> disclaimer);

        _FinalStage disclaimer(AdLeadFormDisclaimer disclaimer);

        _FinalStage disclaimer(Nullable<AdLeadFormDisclaimer> disclaimer);

        /**
         * <p>Intro screen shown before the questions. <code>null</code> when the form has none.</p>
         */
        _FinalStage intro(Optional<AdLeadFormIntro> intro);

        _FinalStage intro(AdLeadFormIntro intro);

        _FinalStage intro(Nullable<AdLeadFormIntro> intro);

        /**
         * <p>Language the form is shown in, such as en_US.</p>
         */
        _FinalStage locale(Optional<String> locale);

        _FinalStage locale(String locale);

        _FinalStage locale(Nullable<String> locale);

        /**
         * <p>Advertiser-facing form name.</p>
         */
        _FinalStage name(Optional<String> name);

        _FinalStage name(String name);

        _FinalStage name(Nullable<String> name);

        /**
         * <p>Custom link text for the privacy policy. <code>null</code> when the default is used.</p>
         */
        _FinalStage privacyPolicyLinkText(Optional<String> privacyPolicyLinkText);

        _FinalStage privacyPolicyLinkText(String privacyPolicyLinkText);

        _FinalStage privacyPolicyLinkText(Nullable<String> privacyPolicyLinkText);

        /**
         * <p>Privacy policy URL configured on the form.</p>
         */
        _FinalStage privacyPolicyUrl(Optional<String> privacyPolicyUrl);

        _FinalStage privacyPolicyUrl(String privacyPolicyUrl);

        _FinalStage privacyPolicyUrl(Nullable<String> privacyPolicyUrl);

        _FinalStage questionLabels(List<String> questionLabels);

        _FinalStage addQuestionLabels(String questionLabels);

        _FinalStage addAllQuestionLabels(List<String> questionLabels);

        _FinalStage questions(List<AdLeadFormQuestion> questions);

        _FinalStage addQuestions(AdLeadFormQuestion questions);

        _FinalStage addAllQuestions(List<AdLeadFormQuestion> questions);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FormTypeStage, IdStage, _FinalStage {
        private SocialAccountLeadFormFormType formType;

        private String id;

        private List<AdLeadFormQuestion> questions = new ArrayList<>();

        private List<String> questionLabels = new ArrayList<>();

        private Optional<String> privacyPolicyUrl = Optional.empty();

        private Optional<String> privacyPolicyLinkText = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<String> locale = Optional.empty();

        private Optional<AdLeadFormIntro> intro = Optional.empty();

        private Optional<AdLeadFormDisclaimer> disclaimer = Optional.empty();

        private Optional<String> createdAt = Optional.empty();

        private Optional<AdLeadFormCompletion> completion = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SocialAccountLeadForm other) {
            completion(other.getCompletion());
            createdAt(other.getCreatedAt());
            disclaimer(other.getDisclaimer());
            formType(other.getFormType());
            id(other.getId());
            intro(other.getIntro());
            locale(other.getLocale());
            name(other.getName());
            privacyPolicyLinkText(other.getPrivacyPolicyLinkText());
            privacyPolicyUrl(other.getPrivacyPolicyUrl());
            questionLabels(other.getQuestionLabels());
            questions(other.getQuestions());
            return this;
        }

        /**
         * <p><code>more_volume</code> is quickest to submit; <code>higher_intent</code> adds a confirmation step before submission.</p>
         * <p><code>more_volume</code> is quickest to submit; <code>higher_intent</code> adds a confirmation step before submission.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("form_type")
        public IdStage formType(@NotNull SocialAccountLeadFormFormType formType) {
            this.formType = Objects.requireNonNull(formType, "formType must not be null");
            return this;
        }

        /**
         * <p>The ad platform's identifier for the form. Use it as lead_gen_form_id on an ad to reuse the form.</p>
         * <p>The ad platform's identifier for the form. Use it as lead_gen_form_id on an ad to reuse the form.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public _FinalStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllQuestions(List<AdLeadFormQuestion> questions) {
            if (questions != null) {
                this.questions.addAll(questions);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addQuestions(AdLeadFormQuestion questions) {
            this.questions.add(questions);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "questions", nulls = Nulls.SKIP)
        public _FinalStage questions(List<AdLeadFormQuestion> questions) {
            this.questions.clear();
            if (questions != null) {
                this.questions.addAll(questions);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllQuestionLabels(List<String> questionLabels) {
            if (questionLabels != null) {
                this.questionLabels.addAll(questionLabels);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addQuestionLabels(String questionLabels) {
            this.questionLabels.add(questionLabels);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "question_labels", nulls = Nulls.SKIP)
        public _FinalStage questionLabels(List<String> questionLabels) {
            this.questionLabels.clear();
            if (questionLabels != null) {
                this.questionLabels.addAll(questionLabels);
            }
            return this;
        }

        /**
         * <p>Privacy policy URL configured on the form.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage privacyPolicyUrl(Nullable<String> privacyPolicyUrl) {
            if (privacyPolicyUrl.isNull()) {
                this.privacyPolicyUrl = null;
            } else if (privacyPolicyUrl.isEmpty()) {
                this.privacyPolicyUrl = Optional.empty();
            } else {
                this.privacyPolicyUrl = Optional.of(privacyPolicyUrl.get());
            }
            return this;
        }

        /**
         * <p>Privacy policy URL configured on the form.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage privacyPolicyUrl(String privacyPolicyUrl) {
            this.privacyPolicyUrl = Optional.ofNullable(privacyPolicyUrl);
            return this;
        }

        /**
         * <p>Privacy policy URL configured on the form.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "privacy_policy_url", nulls = Nulls.SKIP)
        public _FinalStage privacyPolicyUrl(Optional<String> privacyPolicyUrl) {
            this.privacyPolicyUrl = privacyPolicyUrl;
            return this;
        }

        /**
         * <p>Custom link text for the privacy policy. <code>null</code> when the default is used.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage privacyPolicyLinkText(Nullable<String> privacyPolicyLinkText) {
            if (privacyPolicyLinkText.isNull()) {
                this.privacyPolicyLinkText = null;
            } else if (privacyPolicyLinkText.isEmpty()) {
                this.privacyPolicyLinkText = Optional.empty();
            } else {
                this.privacyPolicyLinkText = Optional.of(privacyPolicyLinkText.get());
            }
            return this;
        }

        /**
         * <p>Custom link text for the privacy policy. <code>null</code> when the default is used.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage privacyPolicyLinkText(String privacyPolicyLinkText) {
            this.privacyPolicyLinkText = Optional.ofNullable(privacyPolicyLinkText);
            return this;
        }

        /**
         * <p>Custom link text for the privacy policy. <code>null</code> when the default is used.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "privacy_policy_link_text", nulls = Nulls.SKIP)
        public _FinalStage privacyPolicyLinkText(Optional<String> privacyPolicyLinkText) {
            this.privacyPolicyLinkText = privacyPolicyLinkText;
            return this;
        }

        /**
         * <p>Advertiser-facing form name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage name(Nullable<String> name) {
            if (name.isNull()) {
                this.name = null;
            } else if (name.isEmpty()) {
                this.name = Optional.empty();
            } else {
                this.name = Optional.of(name.get());
            }
            return this;
        }

        /**
         * <p>Advertiser-facing form name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>Advertiser-facing form name.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public _FinalStage name(Optional<String> name) {
            this.name = name;
            return this;
        }

        /**
         * <p>Language the form is shown in, such as en_US.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage locale(Nullable<String> locale) {
            if (locale.isNull()) {
                this.locale = null;
            } else if (locale.isEmpty()) {
                this.locale = Optional.empty();
            } else {
                this.locale = Optional.of(locale.get());
            }
            return this;
        }

        /**
         * <p>Language the form is shown in, such as en_US.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage locale(String locale) {
            this.locale = Optional.ofNullable(locale);
            return this;
        }

        /**
         * <p>Language the form is shown in, such as en_US.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "locale", nulls = Nulls.SKIP)
        public _FinalStage locale(Optional<String> locale) {
            this.locale = locale;
            return this;
        }

        /**
         * <p>Intro screen shown before the questions. <code>null</code> when the form has none.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage intro(Nullable<AdLeadFormIntro> intro) {
            if (intro.isNull()) {
                this.intro = null;
            } else if (intro.isEmpty()) {
                this.intro = Optional.empty();
            } else {
                this.intro = Optional.of(intro.get());
            }
            return this;
        }

        /**
         * <p>Intro screen shown before the questions. <code>null</code> when the form has none.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage intro(AdLeadFormIntro intro) {
            this.intro = Optional.ofNullable(intro);
            return this;
        }

        /**
         * <p>Intro screen shown before the questions. <code>null</code> when the form has none.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "intro", nulls = Nulls.SKIP)
        public _FinalStage intro(Optional<AdLeadFormIntro> intro) {
            this.intro = intro;
            return this;
        }

        /**
         * <p>Custom consent disclaimer shown before submission. <code>null</code> when the form has none.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage disclaimer(Nullable<AdLeadFormDisclaimer> disclaimer) {
            if (disclaimer.isNull()) {
                this.disclaimer = null;
            } else if (disclaimer.isEmpty()) {
                this.disclaimer = Optional.empty();
            } else {
                this.disclaimer = Optional.of(disclaimer.get());
            }
            return this;
        }

        /**
         * <p>Custom consent disclaimer shown before submission. <code>null</code> when the form has none.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage disclaimer(AdLeadFormDisclaimer disclaimer) {
            this.disclaimer = Optional.ofNullable(disclaimer);
            return this;
        }

        /**
         * <p>Custom consent disclaimer shown before submission. <code>null</code> when the form has none.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "disclaimer", nulls = Nulls.SKIP)
        public _FinalStage disclaimer(Optional<AdLeadFormDisclaimer> disclaimer) {
            this.disclaimer = disclaimer;
            return this;
        }

        /**
         * <p>When the form was created, as an ISO 8601 timestamp.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage createdAt(Nullable<String> createdAt) {
            if (createdAt.isNull()) {
                this.createdAt = null;
            } else if (createdAt.isEmpty()) {
                this.createdAt = Optional.empty();
            } else {
                this.createdAt = Optional.of(createdAt.get());
            }
            return this;
        }

        /**
         * <p>When the form was created, as an ISO 8601 timestamp.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage createdAt(String createdAt) {
            this.createdAt = Optional.ofNullable(createdAt);
            return this;
        }

        /**
         * <p>When the form was created, as an ISO 8601 timestamp.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "created_at", nulls = Nulls.SKIP)
        public _FinalStage createdAt(Optional<String> createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * <p>Screen shown after the form is submitted. <code>null</code> when the form has none.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage completion(Nullable<AdLeadFormCompletion> completion) {
            if (completion.isNull()) {
                this.completion = null;
            } else if (completion.isEmpty()) {
                this.completion = Optional.empty();
            } else {
                this.completion = Optional.of(completion.get());
            }
            return this;
        }

        /**
         * <p>Screen shown after the form is submitted. <code>null</code> when the form has none.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage completion(AdLeadFormCompletion completion) {
            this.completion = Optional.ofNullable(completion);
            return this;
        }

        /**
         * <p>Screen shown after the form is submitted. <code>null</code> when the form has none.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "completion", nulls = Nulls.SKIP)
        public _FinalStage completion(Optional<AdLeadFormCompletion> completion) {
            this.completion = completion;
            return this;
        }

        @java.lang.Override
        public SocialAccountLeadForm build() {
            return new SocialAccountLeadForm(
                    completion,
                    createdAt,
                    disclaimer,
                    formType,
                    id,
                    intro,
                    locale,
                    name,
                    privacyPolicyLinkText,
                    privacyPolicyUrl,
                    questionLabels,
                    questions,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
