/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UserBalance.Builder.class)
public final class UserBalance {
    private final List<UserBalanceBusiness> businesses;

    private final String businessesTotalUsd;

    private final List<UserBalanceCash> cash;

    private final String cashUsd;

    private final List<UserBalanceToken> crypto;

    private final String cryptoUsd;

    private final String pendingUsd;

    private final String totalUsd;

    private final String treasuryPendingUsd;

    private final Map<String, Object> additionalProperties;

    private UserBalance(
            List<UserBalanceBusiness> businesses,
            String businessesTotalUsd,
            List<UserBalanceCash> cash,
            String cashUsd,
            List<UserBalanceToken> crypto,
            String cryptoUsd,
            String pendingUsd,
            String totalUsd,
            String treasuryPendingUsd,
            Map<String, Object> additionalProperties) {
        this.businesses = businesses;
        this.businessesTotalUsd = businessesTotalUsd;
        this.cash = cash;
        this.cashUsd = cashUsd;
        this.crypto = crypto;
        this.cryptoUsd = cryptoUsd;
        this.pendingUsd = pendingUsd;
        this.totalUsd = totalUsd;
        this.treasuryPendingUsd = treasuryPendingUsd;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("businesses")
    public List<UserBalanceBusiness> getBusinesses() {
        return businesses;
    }

    /**
     * @return Combined USD balance across every account the user owns.
     */
    @JsonProperty("businesses_total_usd")
    public String getBusinessesTotalUsd() {
        return businessesTotalUsd;
    }

    @JsonProperty("cash")
    public List<UserBalanceCash> getCash() {
        return cash;
    }

    /**
     * @return Fiat cash in USD, including pending, in-transit, and reserve.
     */
    @JsonProperty("cash_usd")
    public String getCashUsd() {
        return cashUsd;
    }

    @JsonProperty("crypto")
    public List<UserBalanceToken> getCrypto() {
        return crypto;
    }

    /**
     * @return Crypto holdings in USD.
     */
    @JsonProperty("crypto_usd")
    public String getCryptoUsd() {
        return cryptoUsd;
    }

    /**
     * @return Fiat pending and in-transit balances, plus in-flight treasury deposits, in USD.
     */
    @JsonProperty("pending_usd")
    public String getPendingUsd() {
        return pendingUsd;
    }

    /**
     * @return The user's personal balance in USD: cash (available + pending + in-transit + reserve) + crypto + in-flight treasury deposits. Excludes account balances (see businesses_total_usd).
     */
    @JsonProperty("total_usd")
    public String getTotalUsd() {
        return totalUsd;
    }

    /**
     * @return Balance-to-wallet USDT0 withdrawals still in flight, in USD.
     */
    @JsonProperty("treasury_pending_usd")
    public String getTreasuryPendingUsd() {
        return treasuryPendingUsd;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UserBalance && equalTo((UserBalance) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UserBalance other) {
        return businesses.equals(other.businesses)
                && businessesTotalUsd.equals(other.businessesTotalUsd)
                && cash.equals(other.cash)
                && cashUsd.equals(other.cashUsd)
                && crypto.equals(other.crypto)
                && cryptoUsd.equals(other.cryptoUsd)
                && pendingUsd.equals(other.pendingUsd)
                && totalUsd.equals(other.totalUsd)
                && treasuryPendingUsd.equals(other.treasuryPendingUsd);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.businesses,
                this.businessesTotalUsd,
                this.cash,
                this.cashUsd,
                this.crypto,
                this.cryptoUsd,
                this.pendingUsd,
                this.totalUsd,
                this.treasuryPendingUsd);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static BusinessesTotalUsdStage builder() {
        return new Builder();
    }

    public interface BusinessesTotalUsdStage {
        /**
         * <p>Combined USD balance across every account the user owns.</p>
         */
        CashUsdStage businessesTotalUsd(@NotNull String businessesTotalUsd);

        Builder from(UserBalance other);
    }

    public interface CashUsdStage {
        /**
         * <p>Fiat cash in USD, including pending, in-transit, and reserve.</p>
         */
        CryptoUsdStage cashUsd(@NotNull String cashUsd);
    }

    public interface CryptoUsdStage {
        /**
         * <p>Crypto holdings in USD.</p>
         */
        PendingUsdStage cryptoUsd(@NotNull String cryptoUsd);
    }

    public interface PendingUsdStage {
        /**
         * <p>Fiat pending and in-transit balances, plus in-flight treasury deposits, in USD.</p>
         */
        TotalUsdStage pendingUsd(@NotNull String pendingUsd);
    }

    public interface TotalUsdStage {
        /**
         * <p>The user's personal balance in USD: cash (available + pending + in-transit + reserve) + crypto + in-flight treasury deposits. Excludes account balances (see businesses_total_usd).</p>
         */
        TreasuryPendingUsdStage totalUsd(@NotNull String totalUsd);
    }

    public interface TreasuryPendingUsdStage {
        /**
         * <p>Balance-to-wallet USDT0 withdrawals still in flight, in USD.</p>
         */
        _FinalStage treasuryPendingUsd(@NotNull String treasuryPendingUsd);
    }

    public interface _FinalStage {
        UserBalance build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage businesses(List<UserBalanceBusiness> businesses);

        _FinalStage addBusinesses(UserBalanceBusiness businesses);

        _FinalStage addAllBusinesses(List<UserBalanceBusiness> businesses);

        _FinalStage cash(List<UserBalanceCash> cash);

        _FinalStage addCash(UserBalanceCash cash);

        _FinalStage addAllCash(List<UserBalanceCash> cash);

        _FinalStage crypto(List<UserBalanceToken> crypto);

        _FinalStage addCrypto(UserBalanceToken crypto);

        _FinalStage addAllCrypto(List<UserBalanceToken> crypto);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements BusinessesTotalUsdStage,
                    CashUsdStage,
                    CryptoUsdStage,
                    PendingUsdStage,
                    TotalUsdStage,
                    TreasuryPendingUsdStage,
                    _FinalStage {
        private String businessesTotalUsd;

        private String cashUsd;

        private String cryptoUsd;

        private String pendingUsd;

        private String totalUsd;

        private String treasuryPendingUsd;

        private List<UserBalanceToken> crypto = new ArrayList<>();

        private List<UserBalanceCash> cash = new ArrayList<>();

        private List<UserBalanceBusiness> businesses = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UserBalance other) {
            businesses(other.getBusinesses());
            businessesTotalUsd(other.getBusinessesTotalUsd());
            cash(other.getCash());
            cashUsd(other.getCashUsd());
            crypto(other.getCrypto());
            cryptoUsd(other.getCryptoUsd());
            pendingUsd(other.getPendingUsd());
            totalUsd(other.getTotalUsd());
            treasuryPendingUsd(other.getTreasuryPendingUsd());
            return this;
        }

        /**
         * <p>Combined USD balance across every account the user owns.</p>
         * <p>Combined USD balance across every account the user owns.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("businesses_total_usd")
        public CashUsdStage businessesTotalUsd(@NotNull String businessesTotalUsd) {
            this.businessesTotalUsd = Objects.requireNonNull(businessesTotalUsd, "businessesTotalUsd must not be null");
            return this;
        }

        /**
         * <p>Fiat cash in USD, including pending, in-transit, and reserve.</p>
         * <p>Fiat cash in USD, including pending, in-transit, and reserve.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("cash_usd")
        public CryptoUsdStage cashUsd(@NotNull String cashUsd) {
            this.cashUsd = Objects.requireNonNull(cashUsd, "cashUsd must not be null");
            return this;
        }

        /**
         * <p>Crypto holdings in USD.</p>
         * <p>Crypto holdings in USD.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("crypto_usd")
        public PendingUsdStage cryptoUsd(@NotNull String cryptoUsd) {
            this.cryptoUsd = Objects.requireNonNull(cryptoUsd, "cryptoUsd must not be null");
            return this;
        }

        /**
         * <p>Fiat pending and in-transit balances, plus in-flight treasury deposits, in USD.</p>
         * <p>Fiat pending and in-transit balances, plus in-flight treasury deposits, in USD.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("pending_usd")
        public TotalUsdStage pendingUsd(@NotNull String pendingUsd) {
            this.pendingUsd = Objects.requireNonNull(pendingUsd, "pendingUsd must not be null");
            return this;
        }

        /**
         * <p>The user's personal balance in USD: cash (available + pending + in-transit + reserve) + crypto + in-flight treasury deposits. Excludes account balances (see businesses_total_usd).</p>
         * <p>The user's personal balance in USD: cash (available + pending + in-transit + reserve) + crypto + in-flight treasury deposits. Excludes account balances (see businesses_total_usd).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("total_usd")
        public TreasuryPendingUsdStage totalUsd(@NotNull String totalUsd) {
            this.totalUsd = Objects.requireNonNull(totalUsd, "totalUsd must not be null");
            return this;
        }

        /**
         * <p>Balance-to-wallet USDT0 withdrawals still in flight, in USD.</p>
         * <p>Balance-to-wallet USDT0 withdrawals still in flight, in USD.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("treasury_pending_usd")
        public _FinalStage treasuryPendingUsd(@NotNull String treasuryPendingUsd) {
            this.treasuryPendingUsd = Objects.requireNonNull(treasuryPendingUsd, "treasuryPendingUsd must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllCrypto(List<UserBalanceToken> crypto) {
            if (crypto != null) {
                this.crypto.addAll(crypto);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addCrypto(UserBalanceToken crypto) {
            this.crypto.add(crypto);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "crypto", nulls = Nulls.SKIP)
        public _FinalStage crypto(List<UserBalanceToken> crypto) {
            this.crypto.clear();
            if (crypto != null) {
                this.crypto.addAll(crypto);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllCash(List<UserBalanceCash> cash) {
            if (cash != null) {
                this.cash.addAll(cash);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addCash(UserBalanceCash cash) {
            this.cash.add(cash);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "cash", nulls = Nulls.SKIP)
        public _FinalStage cash(List<UserBalanceCash> cash) {
            this.cash.clear();
            if (cash != null) {
                this.cash.addAll(cash);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllBusinesses(List<UserBalanceBusiness> businesses) {
            if (businesses != null) {
                this.businesses.addAll(businesses);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addBusinesses(UserBalanceBusiness businesses) {
            this.businesses.add(businesses);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "businesses", nulls = Nulls.SKIP)
        public _FinalStage businesses(List<UserBalanceBusiness> businesses) {
            this.businesses.clear();
            if (businesses != null) {
                this.businesses.addAll(businesses);
            }
            return this;
        }

        @java.lang.Override
        public UserBalance build() {
            return new UserBalance(
                    businesses,
                    businessesTotalUsd,
                    cash,
                    cashUsd,
                    crypto,
                    cryptoUsd,
                    pendingUsd,
                    totalUsd,
                    treasuryPendingUsd,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
