/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.users.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.Nullable;
import com.whop.api.core.NullableNonemptyFilter;
import com.whop.api.core.ObjectMappers;
import com.whop.api.resources.users.types.UpdateMeUsersRequestBanner;
import com.whop.api.resources.users.types.UpdateMeUsersRequestProfilePicture;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateMeUsersRequest.Builder.class)
public final class UpdateMeUsersRequest {
    private final Optional<String> accountId;

    private final Optional<UpdateMeUsersRequestBanner> banner;

    private final Optional<String> bio;

    private final Optional<String> name;

    private final Optional<UpdateMeUsersRequestProfilePicture> profilePicture;

    private final Optional<String> username;

    private final Map<String, Object> additionalProperties;

    private UpdateMeUsersRequest(
            Optional<String> accountId,
            Optional<UpdateMeUsersRequestBanner> banner,
            Optional<String> bio,
            Optional<String> name,
            Optional<UpdateMeUsersRequestProfilePicture> profilePicture,
            Optional<String> username,
            Map<String, Object> additionalProperties) {
        this.accountId = accountId;
        this.banner = banner;
        this.bio = bio;
        this.name = name;
        this.profilePicture = profilePicture;
        this.username = username;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return When set, updates the authenticated user's profile override for this account instead of their global profile.
     */
    @JsonIgnore
    public Optional<String> getAccountId() {
        return accountId;
    }

    @JsonIgnore
    public Optional<UpdateMeUsersRequestBanner> getBanner() {
        if (banner == null) {
            return Optional.empty();
        }
        return banner;
    }

    @JsonProperty("bio")
    public Optional<String> getBio() {
        return bio;
    }

    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    @JsonProperty("profile_picture")
    public Optional<UpdateMeUsersRequestProfilePicture> getProfilePicture() {
        return profilePicture;
    }

    @JsonProperty("username")
    public Optional<String> getUsername() {
        return username;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("banner")
    private Optional<UpdateMeUsersRequestBanner> _getBanner() {
        return banner;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateMeUsersRequest && equalTo((UpdateMeUsersRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateMeUsersRequest other) {
        return accountId.equals(other.accountId)
                && banner.equals(other.banner)
                && bio.equals(other.bio)
                && name.equals(other.name)
                && profilePicture.equals(other.profilePicture)
                && username.equals(other.username);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.accountId, this.banner, this.bio, this.name, this.profilePicture, this.username);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> accountId = Optional.empty();

        private Optional<UpdateMeUsersRequestBanner> banner = Optional.empty();

        private Optional<String> bio = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<UpdateMeUsersRequestProfilePicture> profilePicture = Optional.empty();

        private Optional<String> username = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateMeUsersRequest other) {
            accountId(other.getAccountId());
            banner(other.getBanner());
            bio(other.getBio());
            name(other.getName());
            profilePicture(other.getProfilePicture());
            username(other.getUsername());
            return this;
        }

        /**
         * <p>When set, updates the authenticated user's profile override for this account instead of their global profile.</p>
         */
        @JsonSetter(value = "account_id", nulls = Nulls.SKIP)
        public Builder accountId(Optional<String> accountId) {
            this.accountId = accountId;
            return this;
        }

        public Builder accountId(String accountId) {
            this.accountId = Optional.ofNullable(accountId);
            return this;
        }

        @JsonSetter(value = "banner", nulls = Nulls.SKIP)
        public Builder banner(Optional<UpdateMeUsersRequestBanner> banner) {
            this.banner = banner;
            return this;
        }

        public Builder banner(UpdateMeUsersRequestBanner banner) {
            this.banner = Optional.ofNullable(banner);
            return this;
        }

        public Builder banner(Nullable<UpdateMeUsersRequestBanner> banner) {
            if (banner.isNull()) {
                this.banner = null;
            } else if (banner.isEmpty()) {
                this.banner = Optional.empty();
            } else {
                this.banner = Optional.of(banner.get());
            }
            return this;
        }

        @JsonSetter(value = "bio", nulls = Nulls.SKIP)
        public Builder bio(Optional<String> bio) {
            this.bio = bio;
            return this;
        }

        public Builder bio(String bio) {
            this.bio = Optional.ofNullable(bio);
            return this;
        }

        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        @JsonSetter(value = "profile_picture", nulls = Nulls.SKIP)
        public Builder profilePicture(Optional<UpdateMeUsersRequestProfilePicture> profilePicture) {
            this.profilePicture = profilePicture;
            return this;
        }

        public Builder profilePicture(UpdateMeUsersRequestProfilePicture profilePicture) {
            this.profilePicture = Optional.ofNullable(profilePicture);
            return this;
        }

        @JsonSetter(value = "username", nulls = Nulls.SKIP)
        public Builder username(Optional<String> username) {
            this.username = username;
            return this;
        }

        public Builder username(String username) {
            this.username = Optional.ofNullable(username);
            return this;
        }

        public UpdateMeUsersRequest build() {
            return new UpdateMeUsersRequest(
                    accountId, banner, bio, name, profilePicture, username, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
