/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.people.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ListPeopleResponseDataItemFirstSourceType {
    public static final ListPeopleResponseDataItemFirstSourceType UTM =
            new ListPeopleResponseDataItemFirstSourceType(Value.UTM, "utm");

    public static final ListPeopleResponseDataItemFirstSourceType REFERRER =
            new ListPeopleResponseDataItemFirstSourceType(Value.REFERRER, "referrer");

    public static final ListPeopleResponseDataItemFirstSourceType LEAD_FORM =
            new ListPeopleResponseDataItemFirstSourceType(Value.LEAD_FORM, "lead_form");

    public static final ListPeopleResponseDataItemFirstSourceType EXTERNAL_AD_CLICK =
            new ListPeopleResponseDataItemFirstSourceType(Value.EXTERNAL_AD_CLICK, "external_ad_click");

    public static final ListPeopleResponseDataItemFirstSourceType AD_CLICK =
            new ListPeopleResponseDataItemFirstSourceType(Value.AD_CLICK, "ad_click");

    private final Value value;

    private final String string;

    ListPeopleResponseDataItemFirstSourceType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ListPeopleResponseDataItemFirstSourceType
                        && this.string.equals(((ListPeopleResponseDataItemFirstSourceType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case UTM:
                return visitor.visitUtm();
            case REFERRER:
                return visitor.visitReferrer();
            case LEAD_FORM:
                return visitor.visitLeadForm();
            case EXTERNAL_AD_CLICK:
                return visitor.visitExternalAdClick();
            case AD_CLICK:
                return visitor.visitAdClick();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ListPeopleResponseDataItemFirstSourceType valueOf(String value) {
        switch (value) {
            case "utm":
                return UTM;
            case "referrer":
                return REFERRER;
            case "lead_form":
                return LEAD_FORM;
            case "external_ad_click":
                return EXTERNAL_AD_CLICK;
            case "ad_click":
                return AD_CLICK;
            default:
                return new ListPeopleResponseDataItemFirstSourceType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        AD_CLICK,

        LEAD_FORM,

        EXTERNAL_AD_CLICK,

        REFERRER,

        UTM,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAdClick();

        T visitLeadForm();

        T visitExternalAdClick();

        T visitReferrer();

        T visitUtm();

        T visitUnknown(String unknownType);
    }
}
