/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.users.preferences.notifications.experiences.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.ObjectMappers;
import com.whop.api.types.ExperienceNotificationPreference;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListExperiencesResponse.Builder.class)
public final class ListExperiencesResponse {
    private final List<ExperienceNotificationPreference> data;

    private final ListExperiencesResponsePageInfo pageInfo;

    private final Map<String, Object> additionalProperties;

    private ListExperiencesResponse(
            List<ExperienceNotificationPreference> data,
            ListExperiencesResponsePageInfo pageInfo,
            Map<String, Object> additionalProperties) {
        this.data = data;
        this.pageInfo = pageInfo;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("data")
    public List<ExperienceNotificationPreference> getData() {
        return data;
    }

    @JsonProperty("page_info")
    public ListExperiencesResponsePageInfo getPageInfo() {
        return pageInfo;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListExperiencesResponse && equalTo((ListExperiencesResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListExperiencesResponse other) {
        return data.equals(other.data) && pageInfo.equals(other.pageInfo);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.data, this.pageInfo);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PageInfoStage builder() {
        return new Builder();
    }

    public interface PageInfoStage {
        _FinalStage pageInfo(@NotNull ListExperiencesResponsePageInfo pageInfo);

        Builder from(ListExperiencesResponse other);
    }

    public interface _FinalStage {
        ListExperiencesResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage data(List<ExperienceNotificationPreference> data);

        _FinalStage addData(ExperienceNotificationPreference data);

        _FinalStage addAllData(List<ExperienceNotificationPreference> data);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PageInfoStage, _FinalStage {
        private ListExperiencesResponsePageInfo pageInfo;

        private List<ExperienceNotificationPreference> data = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ListExperiencesResponse other) {
            data(other.getData());
            pageInfo(other.getPageInfo());
            return this;
        }

        @java.lang.Override
        @JsonSetter("page_info")
        public _FinalStage pageInfo(@NotNull ListExperiencesResponsePageInfo pageInfo) {
            this.pageInfo = Objects.requireNonNull(pageInfo, "pageInfo must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllData(List<ExperienceNotificationPreference> data) {
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addData(ExperienceNotificationPreference data) {
            this.data.add(data);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public _FinalStage data(List<ExperienceNotificationPreference> data) {
            this.data.clear();
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        @java.lang.Override
        public ListExperiencesResponse build() {
            return new ListExperiencesResponse(data, pageInfo, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
