/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.partners.businesses.earnings.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.whop.api.core.ObjectMappers;
import java.io.IOException;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonDeserialize(using = ListEarningsResponseDataItemResource.Deserializer.class)
public final class ListEarningsResponseDataItemResource {
    private final Object value;

    private final int type;

    private ListEarningsResponseDataItemResource(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((Optional<ListEarningsResponseDataItemResourceAlternativePaymentMethod>) this.value);
        } else if (this.type == 1) {
            return visitor.visit((ListEarningsResponseDataItemResourceOne) this.value);
        } else if (this.type == 2) {
            return visitor.visit((ListEarningsResponseDataItemResourceCreatedAt) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListEarningsResponseDataItemResource
                && equalTo((ListEarningsResponseDataItemResource) other);
    }

    private boolean equalTo(ListEarningsResponseDataItemResource other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static ListEarningsResponseDataItemResource of(
            Optional<ListEarningsResponseDataItemResourceAlternativePaymentMethod> value) {
        return new ListEarningsResponseDataItemResource(value, 0);
    }

    public static ListEarningsResponseDataItemResource of(ListEarningsResponseDataItemResourceOne value) {
        return new ListEarningsResponseDataItemResource(value, 1);
    }

    public static ListEarningsResponseDataItemResource of(ListEarningsResponseDataItemResourceCreatedAt value) {
        return new ListEarningsResponseDataItemResource(value, 2);
    }

    public interface Visitor<T> {
        T visit(Optional<ListEarningsResponseDataItemResourceAlternativePaymentMethod> value);

        T visit(ListEarningsResponseDataItemResourceOne value);

        T visit(ListEarningsResponseDataItemResourceCreatedAt value);
    }

    static final class Deserializer extends StdDeserializer<ListEarningsResponseDataItemResource> {
        Deserializer() {
            super(ListEarningsResponseDataItemResource.class);
        }

        @java.lang.Override
        public ListEarningsResponseDataItemResource deserialize(JsonParser p, DeserializationContext context)
                throws IOException {
            Object value = p.readValueAs(Object.class);
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("created_at")
                    && ((Map<?, ?>) value).containsKey("currency")
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("object")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, ListEarningsResponseDataItemResourceOne.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("created_at")
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("object")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, ListEarningsResponseDataItemResourceCreatedAt.class));
                } catch (RuntimeException e) {
                }
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(
                        value,
                        new TypeReference<
                                Optional<ListEarningsResponseDataItemResourceAlternativePaymentMethod>>() {}));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
