/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.accesstokens.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.Nullable;
import com.whop.api.core.NullableNonemptyFilter;
import com.whop.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateAccessTokensRequest.Builder.class)
public final class CreateAccessTokensRequest {
    private final Optional<String> companyId;

    private final Optional<OffsetDateTime> expiresAt;

    private final Optional<List<String>> scopedActions;

    private final Optional<String> userId;

    private final Map<String, Object> additionalProperties;

    private CreateAccessTokensRequest(
            Optional<String> companyId,
            Optional<OffsetDateTime> expiresAt,
            Optional<List<String>> scopedActions,
            Optional<String> userId,
            Map<String, Object> additionalProperties) {
        this.companyId = companyId;
        this.expiresAt = expiresAt;
        this.scopedActions = scopedActions;
        this.userId = userId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique identifier of the company to generate the token for, starting with 'biz_'. The API key must have permission to access this company.
     */
    @JsonIgnore
    public Optional<String> getCompanyId() {
        if (companyId == null) {
            return Optional.empty();
        }
        return companyId;
    }

    /**
     * @return The expiration timestamp for the access token. Defaults to 1 hour from now, with a maximum of 3 hours.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getExpiresAt() {
        if (expiresAt == null) {
            return Optional.empty();
        }
        return expiresAt;
    }

    /**
     * @return An array of permission scopes to grant to the access token. If empty or omitted, all permissions from the authenticating credential are inherited. Must be a subset of the credential's permissions.
     */
    @JsonIgnore
    public Optional<List<String>> getScopedActions() {
        if (scopedActions == null) {
            return Optional.empty();
        }
        return scopedActions;
    }

    /**
     * @return The unique identifier of the user to generate the token for, starting with 'user_'. The API key must have permission to access this user.
     */
    @JsonIgnore
    public Optional<String> getUserId() {
        if (userId == null) {
            return Optional.empty();
        }
        return userId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("company_id")
    private Optional<String> _getCompanyId() {
        return companyId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("expires_at")
    private Optional<OffsetDateTime> _getExpiresAt() {
        return expiresAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("scoped_actions")
    private Optional<List<String>> _getScopedActions() {
        return scopedActions;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("user_id")
    private Optional<String> _getUserId() {
        return userId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateAccessTokensRequest && equalTo((CreateAccessTokensRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateAccessTokensRequest other) {
        return companyId.equals(other.companyId)
                && expiresAt.equals(other.expiresAt)
                && scopedActions.equals(other.scopedActions)
                && userId.equals(other.userId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.companyId, this.expiresAt, this.scopedActions, this.userId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> companyId = Optional.empty();

        private Optional<OffsetDateTime> expiresAt = Optional.empty();

        private Optional<List<String>> scopedActions = Optional.empty();

        private Optional<String> userId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CreateAccessTokensRequest other) {
            companyId(other.getCompanyId());
            expiresAt(other.getExpiresAt());
            scopedActions(other.getScopedActions());
            userId(other.getUserId());
            return this;
        }

        /**
         * <p>The unique identifier of the company to generate the token for, starting with 'biz_'. The API key must have permission to access this company.</p>
         */
        @JsonSetter(value = "company_id", nulls = Nulls.SKIP)
        public Builder companyId(Optional<String> companyId) {
            this.companyId = companyId;
            return this;
        }

        public Builder companyId(String companyId) {
            this.companyId = Optional.ofNullable(companyId);
            return this;
        }

        public Builder companyId(Nullable<String> companyId) {
            if (companyId.isNull()) {
                this.companyId = null;
            } else if (companyId.isEmpty()) {
                this.companyId = Optional.empty();
            } else {
                this.companyId = Optional.of(companyId.get());
            }
            return this;
        }

        /**
         * <p>The expiration timestamp for the access token. Defaults to 1 hour from now, with a maximum of 3 hours.</p>
         */
        @JsonSetter(value = "expires_at", nulls = Nulls.SKIP)
        public Builder expiresAt(Optional<OffsetDateTime> expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        public Builder expiresAt(OffsetDateTime expiresAt) {
            this.expiresAt = Optional.ofNullable(expiresAt);
            return this;
        }

        public Builder expiresAt(Nullable<OffsetDateTime> expiresAt) {
            if (expiresAt.isNull()) {
                this.expiresAt = null;
            } else if (expiresAt.isEmpty()) {
                this.expiresAt = Optional.empty();
            } else {
                this.expiresAt = Optional.of(expiresAt.get());
            }
            return this;
        }

        /**
         * <p>An array of permission scopes to grant to the access token. If empty or omitted, all permissions from the authenticating credential are inherited. Must be a subset of the credential's permissions.</p>
         */
        @JsonSetter(value = "scoped_actions", nulls = Nulls.SKIP)
        public Builder scopedActions(Optional<List<String>> scopedActions) {
            this.scopedActions = scopedActions;
            return this;
        }

        public Builder scopedActions(List<String> scopedActions) {
            this.scopedActions = Optional.ofNullable(scopedActions);
            return this;
        }

        public Builder scopedActions(Nullable<List<String>> scopedActions) {
            if (scopedActions.isNull()) {
                this.scopedActions = null;
            } else if (scopedActions.isEmpty()) {
                this.scopedActions = Optional.empty();
            } else {
                this.scopedActions = Optional.of(scopedActions.get());
            }
            return this;
        }

        /**
         * <p>The unique identifier of the user to generate the token for, starting with 'user_'. The API key must have permission to access this user.</p>
         */
        @JsonSetter(value = "user_id", nulls = Nulls.SKIP)
        public Builder userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        public Builder userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        public Builder userId(Nullable<String> userId) {
            if (userId.isNull()) {
                this.userId = null;
            } else if (userId.isEmpty()) {
                this.userId = Optional.empty();
            } else {
                this.userId = Optional.of(userId.get());
            }
            return this;
        }

        public CreateAccessTokensRequest build() {
            return new CreateAccessTokensRequest(companyId, expiresAt, scopedActions, userId, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
