/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.transfers.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PostTransferCreatedPayloadDataObject {
    public static final PostTransferCreatedPayloadDataObject TRANSFER =
            new PostTransferCreatedPayloadDataObject(Value.TRANSFER, "transfer");

    private final Value value;

    private final String string;

    PostTransferCreatedPayloadDataObject(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PostTransferCreatedPayloadDataObject
                        && this.string.equals(((PostTransferCreatedPayloadDataObject) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case TRANSFER:
                return visitor.visitTransfer();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PostTransferCreatedPayloadDataObject valueOf(String value) {
        switch (value) {
            case "transfer":
                return TRANSFER;
            default:
                return new PostTransferCreatedPayloadDataObject(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        TRANSFER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitTransfer();

        T visitUnknown(String unknownType);
    }
}
