/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.users;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.whop.api.core.ClientOptions;
import com.whop.api.core.MediaTypes;
import com.whop.api.core.ObjectMappers;
import com.whop.api.core.QueryStringMapper;
import com.whop.api.core.RequestOptions;
import com.whop.api.core.WhopApiApiException;
import com.whop.api.core.WhopApiException;
import com.whop.api.core.WhopApiHttpResponse;
import com.whop.api.core.pagination.SyncPagingIterable;
import com.whop.api.errors.BadRequestError;
import com.whop.api.errors.ForbiddenError;
import com.whop.api.errors.NotFoundError;
import com.whop.api.errors.UnauthorizedError;
import com.whop.api.resources.users.requests.CheckAccessUsersRequest;
import com.whop.api.resources.users.requests.ListUsersRequest;
import com.whop.api.resources.users.requests.MeUsersRequest;
import com.whop.api.resources.users.requests.RecommendActionsUsersRequest;
import com.whop.api.resources.users.requests.RetrieveUsersRequest;
import com.whop.api.resources.users.requests.UpdateMeUsersRequest;
import com.whop.api.resources.users.requests.UpdateUsersRequest;
import com.whop.api.resources.users.types.CheckAccessUsersResponse;
import com.whop.api.resources.users.types.ListUsersResponse;
import com.whop.api.resources.users.types.RecommendActionsUsersResponse;
import com.whop.api.types.User;
import java.io.IOException;
import java.util.List;
import java.util.Optional;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawUsersClient {
    protected final ClientOptions clientOptions;

    public RawUsersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Search for users by name or username, ranked by social proximity to the authenticated user. Returns the user's most recently followed users when no query is given.
     */
    public WhopApiHttpResponse<SyncPagingIterable<User>> list() {
        return list(ListUsersRequest.builder().build());
    }

    /**
     * Search for users by name or username, ranked by social proximity to the authenticated user. Returns the user's most recently followed users when no query is given.
     */
    public WhopApiHttpResponse<SyncPagingIterable<User>> list(RequestOptions requestOptions) {
        return list(ListUsersRequest.builder().build(), requestOptions);
    }

    /**
     * Search for users by name or username, ranked by social proximity to the authenticated user. Returns the user's most recently followed users when no query is given.
     */
    public WhopApiHttpResponse<SyncPagingIterable<User>> list(ListUsersRequest request) {
        return list(request, null);
    }

    /**
     * Search for users by name or username, ranked by social proximity to the authenticated user. Returns the user's most recently followed users when no query is given.
     */
    public WhopApiHttpResponse<SyncPagingIterable<User>> list(ListUsersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users");
        if (request.getQuery().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "query", request.getQuery().get(), false);
        }
        if (request.getFirst().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "first", request.getFirst().get(), false);
        }
        if (request.getAfter().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "after", request.getAfter().get(), false);
        }
        if (request.getLast().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "last", request.getLast().get(), false);
        }
        if (request.getBefore().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "before", request.getBefore().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                ListUsersResponse parsedResponse =
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListUsersResponse.class);
                Optional<String> startingAfter = parsedResponse.getPageInfo().getEndCursor();
                ListUsersRequest nextRequest = ListUsersRequest.builder()
                        .from(request)
                        .after(startingAfter)
                        .build();
                List<User> result = parsedResponse.getData();
                return new WhopApiHttpResponse<>(
                        new SyncPagingIterable<User>(
                                startingAfter != null, result, parsedResponse, () -> list(nextRequest, requestOptions)
                                        .body()),
                        response);
            }
            try {
                if (response.code() == 401) {
                    throw new UnauthorizedError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new WhopApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new WhopApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Retrieves the authenticated user — the self view of the user object. Same shape as <code>GET /users/{id}</code>, with the self-only fields populated: <code>email</code> (email-read scope), <code>staff</code> (Whop staff only, staff-read scope), <code>balance</code> and <code>earnings_usd</code> (balance-read scope), the opt-in <code>balance_history</code>, and every linked social account.
     */
    public WhopApiHttpResponse<User> me() {
        return me(MeUsersRequest.builder().build());
    }

    /**
     * Retrieves the authenticated user — the self view of the user object. Same shape as <code>GET /users/{id}</code>, with the self-only fields populated: <code>email</code> (email-read scope), <code>staff</code> (Whop staff only, staff-read scope), <code>balance</code> and <code>earnings_usd</code> (balance-read scope), the opt-in <code>balance_history</code>, and every linked social account.
     */
    public WhopApiHttpResponse<User> me(RequestOptions requestOptions) {
        return me(MeUsersRequest.builder().build(), requestOptions);
    }

    /**
     * Retrieves the authenticated user — the self view of the user object. Same shape as <code>GET /users/{id}</code>, with the self-only fields populated: <code>email</code> (email-read scope), <code>staff</code> (Whop staff only, staff-read scope), <code>balance</code> and <code>earnings_usd</code> (balance-read scope), the opt-in <code>balance_history</code>, and every linked social account.
     */
    public WhopApiHttpResponse<User> me(MeUsersRequest request) {
        return me(request, null);
    }

    /**
     * Retrieves the authenticated user — the self view of the user object. Same shape as <code>GET /users/{id}</code>, with the self-only fields populated: <code>email</code> (email-read scope), <code>staff</code> (Whop staff only, staff-read scope), <code>balance</code> and <code>earnings_usd</code> (balance-read scope), the opt-in <code>balance_history</code>, and every linked social account.
     */
    public WhopApiHttpResponse<User> me(MeUsersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users/me");
        if (request.getAccountId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "account_id", request.getAccountId().get(), false);
        }
        if (request.getIncludeBalanceHistory().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "include_balance_history",
                    request.getIncludeBalanceHistory().get(),
                    false);
        }
        if (request.getFrom().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "from", request.getFrom().get(), false);
        }
        if (request.getTo().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "to", request.getTo().get(), false);
        }
        if (request.getInterval().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "interval", request.getInterval().get(), false);
        }
        if (request.getTimeZone().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "time_zone", request.getTimeZone().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new WhopApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, User.class), response);
            }
            try {
                if (response.code() == 404) {
                    throw new NotFoundError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new WhopApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new WhopApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Updates the authenticated user's global profile, or their profile override for an account when account_id is given. Not available to API keys.
     */
    public WhopApiHttpResponse<User> updateMe() {
        return updateMe(UpdateMeUsersRequest.builder().build());
    }

    /**
     * Updates the authenticated user's global profile, or their profile override for an account when account_id is given. Not available to API keys.
     */
    public WhopApiHttpResponse<User> updateMe(RequestOptions requestOptions) {
        return updateMe(UpdateMeUsersRequest.builder().build(), requestOptions);
    }

    /**
     * Updates the authenticated user's global profile, or their profile override for an account when account_id is given. Not available to API keys.
     */
    public WhopApiHttpResponse<User> updateMe(UpdateMeUsersRequest request) {
        return updateMe(request, null);
    }

    /**
     * Updates the authenticated user's global profile, or their profile override for an account when account_id is given. Not available to API keys.
     */
    public WhopApiHttpResponse<User> updateMe(UpdateMeUsersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users/me");
        if (request.getAccountId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "account_id", request.getAccountId().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new WhopApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, User.class), response);
            }
            try {
                if (response.code() == 400) {
                    throw new BadRequestError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new WhopApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new WhopApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Retrieves a user by <code>user_</code> tag or username, or the authenticated user with the reserved id <code>me</code>. Profiles include linked social accounts — reading your own profile returns every linked account, other profiles only what is public on Whop (the primary Discord and the X account). The self-only fields are populated only when the id is <code>me</code>: <code>email</code> (email-read scope), <code>staff</code> (Whop staff only, staff-read scope), <code>balance</code> and <code>earnings_usd</code> (balance-read scope), and the opt-in <code>balance_history</code>. They are always <code>null</code> when addressing a user by tag or username.
     */
    public WhopApiHttpResponse<User> retrieve(String id) {
        return retrieve(id, RetrieveUsersRequest.builder().build());
    }

    /**
     * Retrieves a user by <code>user_</code> tag or username, or the authenticated user with the reserved id <code>me</code>. Profiles include linked social accounts — reading your own profile returns every linked account, other profiles only what is public on Whop (the primary Discord and the X account). The self-only fields are populated only when the id is <code>me</code>: <code>email</code> (email-read scope), <code>staff</code> (Whop staff only, staff-read scope), <code>balance</code> and <code>earnings_usd</code> (balance-read scope), and the opt-in <code>balance_history</code>. They are always <code>null</code> when addressing a user by tag or username.
     */
    public WhopApiHttpResponse<User> retrieve(String id, RequestOptions requestOptions) {
        return retrieve(id, RetrieveUsersRequest.builder().build(), requestOptions);
    }

    /**
     * Retrieves a user by <code>user_</code> tag or username, or the authenticated user with the reserved id <code>me</code>. Profiles include linked social accounts — reading your own profile returns every linked account, other profiles only what is public on Whop (the primary Discord and the X account). The self-only fields are populated only when the id is <code>me</code>: <code>email</code> (email-read scope), <code>staff</code> (Whop staff only, staff-read scope), <code>balance</code> and <code>earnings_usd</code> (balance-read scope), and the opt-in <code>balance_history</code>. They are always <code>null</code> when addressing a user by tag or username.
     */
    public WhopApiHttpResponse<User> retrieve(String id, RetrieveUsersRequest request) {
        return retrieve(id, request, null);
    }

    /**
     * Retrieves a user by <code>user_</code> tag or username, or the authenticated user with the reserved id <code>me</code>. Profiles include linked social accounts — reading your own profile returns every linked account, other profiles only what is public on Whop (the primary Discord and the X account). The self-only fields are populated only when the id is <code>me</code>: <code>email</code> (email-read scope), <code>staff</code> (Whop staff only, staff-read scope), <code>balance</code> and <code>earnings_usd</code> (balance-read scope), and the opt-in <code>balance_history</code>. They are always <code>null</code> when addressing a user by tag or username.
     */
    public WhopApiHttpResponse<User> retrieve(String id, RetrieveUsersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(id);
        if (request.getAccountId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "account_id", request.getAccountId().get(), false);
        }
        if (request.getIncludeBalanceHistory().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "include_balance_history",
                    request.getIncludeBalanceHistory().get(),
                    false);
        }
        if (request.getFrom().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "from", request.getFrom().get(), false);
        }
        if (request.getTo().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "to", request.getTo().get(), false);
        }
        if (request.getInterval().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "interval", request.getInterval().get(), false);
        }
        if (request.getTimeZone().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "time_zone", request.getTimeZone().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new WhopApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, User.class), response);
            }
            try {
                if (response.code() == 404) {
                    throw new NotFoundError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new WhopApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new WhopApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Updates a user, addressed by <code>user_</code> tag, username, or the reserved id <code>me</code> for the authenticated user. A user token updates their own global profile; an API key updates the user's account-specific profile override (account_id required).
     */
    public WhopApiHttpResponse<User> update(String id) {
        return update(id, UpdateUsersRequest.builder().build());
    }

    /**
     * Updates a user, addressed by <code>user_</code> tag, username, or the reserved id <code>me</code> for the authenticated user. A user token updates their own global profile; an API key updates the user's account-specific profile override (account_id required).
     */
    public WhopApiHttpResponse<User> update(String id, RequestOptions requestOptions) {
        return update(id, UpdateUsersRequest.builder().build(), requestOptions);
    }

    /**
     * Updates a user, addressed by <code>user_</code> tag, username, or the reserved id <code>me</code> for the authenticated user. A user token updates their own global profile; an API key updates the user's account-specific profile override (account_id required).
     */
    public WhopApiHttpResponse<User> update(String id, UpdateUsersRequest request) {
        return update(id, request, null);
    }

    /**
     * Updates a user, addressed by <code>user_</code> tag, username, or the reserved id <code>me</code> for the authenticated user. A user token updates their own global profile; an API key updates the user's account-specific profile override (account_id required).
     */
    public WhopApiHttpResponse<User> update(String id, UpdateUsersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(id);
        if (request.getAccountId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "account_id", request.getAccountId().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new WhopApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, User.class), response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new WhopApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new WhopApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Checks whether a user has access to an account, product, or experience the caller can reach.
     */
    public WhopApiHttpResponse<CheckAccessUsersResponse> checkAccess(String id, String resourceId) {
        return checkAccess(id, resourceId, CheckAccessUsersRequest.builder().build());
    }

    /**
     * Checks whether a user has access to an account, product, or experience the caller can reach.
     */
    public WhopApiHttpResponse<CheckAccessUsersResponse> checkAccess(
            String id, String resourceId, RequestOptions requestOptions) {
        return checkAccess(id, resourceId, CheckAccessUsersRequest.builder().build(), requestOptions);
    }

    /**
     * Checks whether a user has access to an account, product, or experience the caller can reach.
     */
    public WhopApiHttpResponse<CheckAccessUsersResponse> checkAccess(
            String id, String resourceId, CheckAccessUsersRequest request) {
        return checkAccess(id, resourceId, request, null);
    }

    /**
     * Checks whether a user has access to an account, product, or experience the caller can reach.
     */
    public WhopApiHttpResponse<CheckAccessUsersResponse> checkAccess(
            String id, String resourceId, CheckAccessUsersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(id)
                .addPathSegments("access")
                .addPathSegment(resourceId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new WhopApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CheckAccessUsersResponse.class),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new WhopApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new WhopApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Lists the recommended actions computed for the user: personal suggestions (e.g. start a business or become an affiliate) pooled with the highest-impact actions across the accounts the user owns. Business actions are tagged with their <code>account_id</code>/<code>account_name</code>; personal actions leave those <code>null</code>. Self-only: <code>id</code> must be <code>me</code> or the authenticated user's own tag/username.
     */
    public WhopApiHttpResponse<RecommendActionsUsersResponse> recommendActions(String id) {
        return recommendActions(id, RecommendActionsUsersRequest.builder().build());
    }

    /**
     * Lists the recommended actions computed for the user: personal suggestions (e.g. start a business or become an affiliate) pooled with the highest-impact actions across the accounts the user owns. Business actions are tagged with their <code>account_id</code>/<code>account_name</code>; personal actions leave those <code>null</code>. Self-only: <code>id</code> must be <code>me</code> or the authenticated user's own tag/username.
     */
    public WhopApiHttpResponse<RecommendActionsUsersResponse> recommendActions(
            String id, RequestOptions requestOptions) {
        return recommendActions(id, RecommendActionsUsersRequest.builder().build(), requestOptions);
    }

    /**
     * Lists the recommended actions computed for the user: personal suggestions (e.g. start a business or become an affiliate) pooled with the highest-impact actions across the accounts the user owns. Business actions are tagged with their <code>account_id</code>/<code>account_name</code>; personal actions leave those <code>null</code>. Self-only: <code>id</code> must be <code>me</code> or the authenticated user's own tag/username.
     */
    public WhopApiHttpResponse<RecommendActionsUsersResponse> recommendActions(
            String id, RecommendActionsUsersRequest request) {
        return recommendActions(id, request, null);
    }

    /**
     * Lists the recommended actions computed for the user: personal suggestions (e.g. start a business or become an affiliate) pooled with the highest-impact actions across the accounts the user owns. Business actions are tagged with their <code>account_id</code>/<code>account_name</code>; personal actions leave those <code>null</code>. Self-only: <code>id</code> must be <code>me</code> or the authenticated user's own tag/username.
     */
    public WhopApiHttpResponse<RecommendActionsUsersResponse> recommendActions(
            String id, RecommendActionsUsersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(id)
                .addPathSegments("recommend_actions");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new WhopApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RecommendActionsUsersResponse.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new WhopApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new WhopApiException("Network error executing HTTP request", e);
        }
    }
}
