/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.users.passkeys.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeletePasskeysRequest.Builder.class)
public final class DeletePasskeysRequest {
    private final String authenticatorData;

    private final String clientDataJson;

    private final String signature;

    private final Map<String, Object> additionalProperties;

    private DeletePasskeysRequest(
            String authenticatorData,
            String clientDataJson,
            String signature,
            Map<String, Object> additionalProperties) {
        this.authenticatorData = authenticatorData;
        this.clientDataJson = clientDataJson;
        this.signature = signature;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The <code>authenticatorData</code> from the WebAuthn assertion, base64url-encoded.
     */
    @JsonProperty("authenticator_data")
    public String getAuthenticatorData() {
        return authenticatorData;
    }

    /**
     * @return The <code>clientDataJSON</code> from the WebAuthn assertion, base64url-encoded.
     */
    @JsonProperty("client_data_json")
    public String getClientDataJson() {
        return clientDataJson;
    }

    /**
     * @return The <code>signature</code> from the WebAuthn assertion, base64url-encoded.
     */
    @JsonProperty("signature")
    public String getSignature() {
        return signature;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeletePasskeysRequest && equalTo((DeletePasskeysRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeletePasskeysRequest other) {
        return authenticatorData.equals(other.authenticatorData)
                && clientDataJson.equals(other.clientDataJson)
                && signature.equals(other.signature);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.authenticatorData, this.clientDataJson, this.signature);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AuthenticatorDataStage builder() {
        return new Builder();
    }

    public interface AuthenticatorDataStage {
        /**
         * <p>The <code>authenticatorData</code> from the WebAuthn assertion, base64url-encoded.</p>
         */
        ClientDataJsonStage authenticatorData(@NotNull String authenticatorData);

        Builder from(DeletePasskeysRequest other);
    }

    public interface ClientDataJsonStage {
        /**
         * <p>The <code>clientDataJSON</code> from the WebAuthn assertion, base64url-encoded.</p>
         */
        SignatureStage clientDataJson(@NotNull String clientDataJson);
    }

    public interface SignatureStage {
        /**
         * <p>The <code>signature</code> from the WebAuthn assertion, base64url-encoded.</p>
         */
        _FinalStage signature(@NotNull String signature);
    }

    public interface _FinalStage {
        DeletePasskeysRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements AuthenticatorDataStage, ClientDataJsonStage, SignatureStage, _FinalStage {
        private String authenticatorData;

        private String clientDataJson;

        private String signature;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DeletePasskeysRequest other) {
            authenticatorData(other.getAuthenticatorData());
            clientDataJson(other.getClientDataJson());
            signature(other.getSignature());
            return this;
        }

        /**
         * <p>The <code>authenticatorData</code> from the WebAuthn assertion, base64url-encoded.</p>
         * <p>The <code>authenticatorData</code> from the WebAuthn assertion, base64url-encoded.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("authenticator_data")
        public ClientDataJsonStage authenticatorData(@NotNull String authenticatorData) {
            this.authenticatorData = Objects.requireNonNull(authenticatorData, "authenticatorData must not be null");
            return this;
        }

        /**
         * <p>The <code>clientDataJSON</code> from the WebAuthn assertion, base64url-encoded.</p>
         * <p>The <code>clientDataJSON</code> from the WebAuthn assertion, base64url-encoded.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("client_data_json")
        public SignatureStage clientDataJson(@NotNull String clientDataJson) {
            this.clientDataJson = Objects.requireNonNull(clientDataJson, "clientDataJson must not be null");
            return this;
        }

        /**
         * <p>The <code>signature</code> from the WebAuthn assertion, base64url-encoded.</p>
         * <p>The <code>signature</code> from the WebAuthn assertion, base64url-encoded.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("signature")
        public _FinalStage signature(@NotNull String signature) {
            this.signature = Objects.requireNonNull(signature, "signature must not be null");
            return this;
        }

        @java.lang.Override
        public DeletePasskeysRequest build() {
            return new DeletePasskeysRequest(authenticatorData, clientDataJson, signature, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
