/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.invoices.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.whop.api.core.ObjectMappers;
import java.io.IOException;
import java.util.Map;
import java.util.Objects;

@JsonDeserialize(using = CreateInvoicesRequest.Deserializer.class)
public final class CreateInvoicesRequest {
    private final Object value;

    private final int type;

    private CreateInvoicesRequest(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((CreateInvoicesRequestProduct) this.value);
        } else if (this.type == 1) {
            return visitor.visit((CreateInvoicesRequestProductId) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateInvoicesRequest && equalTo((CreateInvoicesRequest) other);
    }

    private boolean equalTo(CreateInvoicesRequest other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static CreateInvoicesRequest of(CreateInvoicesRequestProduct value) {
        return new CreateInvoicesRequest(value, 0);
    }

    public static CreateInvoicesRequest of(CreateInvoicesRequestProductId value) {
        return new CreateInvoicesRequest(value, 1);
    }

    public interface Visitor<T> {
        T visit(CreateInvoicesRequestProduct value);

        T visit(CreateInvoicesRequestProductId value);
    }

    static final class Deserializer extends StdDeserializer<CreateInvoicesRequest> {
        Deserializer() {
            super(CreateInvoicesRequest.class);
        }

        @java.lang.Override
        public CreateInvoicesRequest deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("collection_method")
                    && ((Map<?, ?>) value).containsKey("company_id")
                    && ((Map<?, ?>) value).containsKey("plan")
                    && ((Map<?, ?>) value).containsKey("product")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, CreateInvoicesRequestProduct.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("collection_method")
                    && ((Map<?, ?>) value).containsKey("company_id")
                    && ((Map<?, ?>) value).containsKey("plan")
                    && ((Map<?, ?>) value).containsKey("product_id")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, CreateInvoicesRequestProductId.class));
                } catch (RuntimeException e) {
                }
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
