/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.apikeys;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.whop.api.core.ClientOptions;
import com.whop.api.core.MediaTypes;
import com.whop.api.core.ObjectMappers;
import com.whop.api.core.QueryStringMapper;
import com.whop.api.core.RequestOptions;
import com.whop.api.core.WhopApiApiException;
import com.whop.api.core.WhopApiException;
import com.whop.api.core.WhopApiHttpResponse;
import com.whop.api.core.pagination.SyncPagingIterable;
import com.whop.api.errors.BadRequestError;
import com.whop.api.errors.ConflictError;
import com.whop.api.errors.ForbiddenError;
import com.whop.api.errors.NotFoundError;
import com.whop.api.errors.UnauthorizedError;
import com.whop.api.resources.apikeys.requests.CreateApiKeysRequest;
import com.whop.api.resources.apikeys.requests.DeleteApiKeysRequest;
import com.whop.api.resources.apikeys.requests.ListApiKeysRequest;
import com.whop.api.resources.apikeys.requests.RetrieveApiKeysRequest;
import com.whop.api.resources.apikeys.requests.RotateApiKeysRequest;
import com.whop.api.resources.apikeys.requests.UpdateApiKeysRequest;
import com.whop.api.resources.apikeys.types.DeleteApiKeysResponse;
import com.whop.api.resources.apikeys.types.ListApiKeysResponse;
import com.whop.api.resources.apikeys.types.ListPermissionsApiKeysResponse;
import com.whop.api.types.ApiKey;
import com.whop.api.types.V1ErrorResponse;
import java.io.IOException;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawApiKeysClient {
    protected final ClientOptions clientOptions;

    public AsyncRawApiKeysClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Lists the API keys of an account or app, newest first. Responses never include the full secret — only its obfuscated form.
     */
    public CompletableFuture<WhopApiHttpResponse<SyncPagingIterable<ApiKey>>> list(ListApiKeysRequest request) {
        return list(request, null);
    }

    /**
     * Lists the API keys of an account or app, newest first. Responses never include the full secret — only its obfuscated form.
     */
    public CompletableFuture<WhopApiHttpResponse<SyncPagingIterable<ApiKey>>> list(
            ListApiKeysRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api_keys");
        QueryStringMapper.addQueryParameter(httpUrl, "resource_id", request.getResourceId(), false);
        QueryStringMapper.addQueryParameter(httpUrl, "resource_type", request.getResourceType(), false);
        if (request.getCreatedBefore().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "created_before", request.getCreatedBefore().get(), false);
        }
        if (request.getCreatedAfter().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "created_after", request.getCreatedAfter().get(), false);
        }
        if (request.getFirst().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "first", request.getFirst().get(), false);
        }
        if (request.getAfter().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "after", request.getAfter().get(), false);
        }
        if (request.getLast().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "last", request.getLast().get(), false);
        }
        if (request.getBefore().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "before", request.getBefore().get(), false);
        }
        if (request.getOrder().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "order", request.getOrder().get(), false);
        }
        if (request.getDirection().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "direction", request.getDirection().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<WhopApiHttpResponse<SyncPagingIterable<ApiKey>>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        ListApiKeysResponse parsedResponse =
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListApiKeysResponse.class);
                        Optional<String> startingAfter =
                                parsedResponse.getPageInfo().getEndCursor();
                        ListApiKeysRequest nextRequest = ListApiKeysRequest.builder()
                                .from(request)
                                .after(startingAfter)
                                .build();
                        List<ApiKey> result = parsedResponse.getData();
                        future.complete(new WhopApiHttpResponse<>(
                                new SyncPagingIterable<ApiKey>(startingAfter != null, result, parsedResponse, () -> {
                                    try {
                                        return list(nextRequest, requestOptions)
                                                .get()
                                                .body();
                                    } catch (InterruptedException | ExecutionException e) {
                                        throw new RuntimeException(e);
                                    }
                                }),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new WhopApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new WhopApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new WhopApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Creates an API key for an account or app. The response is the only place the full <code>secret_key</code> is returned — store it immediately. Requires a user session; API keys cannot manage API keys.
     */
    public CompletableFuture<WhopApiHttpResponse<ApiKey>> create(CreateApiKeysRequest request) {
        return create(request, null);
    }

    /**
     * Creates an API key for an account or app. The response is the only place the full <code>secret_key</code> is returned — store it immediately. Requires a user session; API keys cannot manage API keys.
     */
    public CompletableFuture<WhopApiHttpResponse<ApiKey>> create(
            CreateApiKeysRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api_keys");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new WhopApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<WhopApiHttpResponse<ApiKey>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new WhopApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiKey.class), response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 409:
                                future.completeExceptionally(new ConflictError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, V1ErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new WhopApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new WhopApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new WhopApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Lists the catalog of permission actions that can be granted to users, apps, and API keys — the source for the dashboard's permission pickers. Small and returned in full on one page.
     */
    public CompletableFuture<WhopApiHttpResponse<ListPermissionsApiKeysResponse>> listPermissions() {
        return listPermissions(null);
    }

    /**
     * Lists the catalog of permission actions that can be granted to users, apps, and API keys — the source for the dashboard's permission pickers. Small and returned in full on one page.
     */
    public CompletableFuture<WhopApiHttpResponse<ListPermissionsApiKeysResponse>> listPermissions(
            RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api_keys/permissions");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<WhopApiHttpResponse<ListPermissionsApiKeysResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new WhopApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, ListPermissionsApiKeysResponse.class),
                                response));
                        return;
                    }
                    try {
                        if (response.code() == 401) {
                            future.completeExceptionally(new UnauthorizedError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new WhopApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new WhopApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new WhopApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Retrieves an API key with its effective permission grants. The full secret is never returned — rotate the key if it was lost.
     */
    public CompletableFuture<WhopApiHttpResponse<ApiKey>> retrieve(String id) {
        return retrieve(id, RetrieveApiKeysRequest.builder().build());
    }

    /**
     * Retrieves an API key with its effective permission grants. The full secret is never returned — rotate the key if it was lost.
     */
    public CompletableFuture<WhopApiHttpResponse<ApiKey>> retrieve(String id, RequestOptions requestOptions) {
        return retrieve(id, RetrieveApiKeysRequest.builder().build(), requestOptions);
    }

    /**
     * Retrieves an API key with its effective permission grants. The full secret is never returned — rotate the key if it was lost.
     */
    public CompletableFuture<WhopApiHttpResponse<ApiKey>> retrieve(String id, RetrieveApiKeysRequest request) {
        return retrieve(id, request, null);
    }

    /**
     * Retrieves an API key with its effective permission grants. The full secret is never returned — rotate the key if it was lost.
     */
    public CompletableFuture<WhopApiHttpResponse<ApiKey>> retrieve(
            String id, RetrieveApiKeysRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api_keys")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<WhopApiHttpResponse<ApiKey>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new WhopApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiKey.class), response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new WhopApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new WhopApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new WhopApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Permanently revokes an API key; requests using its secret stop authenticating immediately. Default and agent-backend keys cannot be deleted.
     */
    public CompletableFuture<WhopApiHttpResponse<DeleteApiKeysResponse>> delete(String id) {
        return delete(id, DeleteApiKeysRequest.builder().build());
    }

    /**
     * Permanently revokes an API key; requests using its secret stop authenticating immediately. Default and agent-backend keys cannot be deleted.
     */
    public CompletableFuture<WhopApiHttpResponse<DeleteApiKeysResponse>> delete(
            String id, RequestOptions requestOptions) {
        return delete(id, DeleteApiKeysRequest.builder().build(), requestOptions);
    }

    /**
     * Permanently revokes an API key; requests using its secret stop authenticating immediately. Default and agent-backend keys cannot be deleted.
     */
    public CompletableFuture<WhopApiHttpResponse<DeleteApiKeysResponse>> delete(
            String id, DeleteApiKeysRequest request) {
        return delete(id, request, null);
    }

    /**
     * Permanently revokes an API key; requests using its secret stop authenticating immediately. Default and agent-backend keys cannot be deleted.
     */
    public CompletableFuture<WhopApiHttpResponse<DeleteApiKeysResponse>> delete(
            String id, DeleteApiKeysRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api_keys")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<WhopApiHttpResponse<DeleteApiKeysResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new WhopApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, DeleteApiKeysResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new WhopApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new WhopApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new WhopApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Updates an API key's name, permissions, API version, expiration, or IP allowlist. Fields that are omitted keep their current value; default keys cannot be modified.
     */
    public CompletableFuture<WhopApiHttpResponse<ApiKey>> update(String id) {
        return update(id, UpdateApiKeysRequest.builder().build());
    }

    /**
     * Updates an API key's name, permissions, API version, expiration, or IP allowlist. Fields that are omitted keep their current value; default keys cannot be modified.
     */
    public CompletableFuture<WhopApiHttpResponse<ApiKey>> update(String id, RequestOptions requestOptions) {
        return update(id, UpdateApiKeysRequest.builder().build(), requestOptions);
    }

    /**
     * Updates an API key's name, permissions, API version, expiration, or IP allowlist. Fields that are omitted keep their current value; default keys cannot be modified.
     */
    public CompletableFuture<WhopApiHttpResponse<ApiKey>> update(String id, UpdateApiKeysRequest request) {
        return update(id, request, null);
    }

    /**
     * Updates an API key's name, permissions, API version, expiration, or IP allowlist. Fields that are omitted keep their current value; default keys cannot be modified.
     */
    public CompletableFuture<WhopApiHttpResponse<ApiKey>> update(
            String id, UpdateApiKeysRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api_keys")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new WhopApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<WhopApiHttpResponse<ApiKey>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new WhopApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiKey.class), response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new WhopApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new WhopApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new WhopApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Rotates the API key's secret, invalidating the previous secret immediately. The response is the only place the new <code>secret_key</code> is returned.
     */
    public CompletableFuture<WhopApiHttpResponse<ApiKey>> rotate(String id) {
        return rotate(id, RotateApiKeysRequest.builder().build());
    }

    /**
     * Rotates the API key's secret, invalidating the previous secret immediately. The response is the only place the new <code>secret_key</code> is returned.
     */
    public CompletableFuture<WhopApiHttpResponse<ApiKey>> rotate(String id, RequestOptions requestOptions) {
        return rotate(id, RotateApiKeysRequest.builder().build(), requestOptions);
    }

    /**
     * Rotates the API key's secret, invalidating the previous secret immediately. The response is the only place the new <code>secret_key</code> is returned.
     */
    public CompletableFuture<WhopApiHttpResponse<ApiKey>> rotate(String id, RotateApiKeysRequest request) {
        return rotate(id, request, null);
    }

    /**
     * Rotates the API key's secret, invalidating the previous secret immediately. The response is the only place the new <code>secret_key</code> is returned.
     */
    public CompletableFuture<WhopApiHttpResponse<ApiKey>> rotate(
            String id, RotateApiKeysRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api_keys")
                .addPathSegment(id)
                .addPathSegments("rotate");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", RequestBody.create("", null))
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<WhopApiHttpResponse<ApiKey>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new WhopApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiKey.class), response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 409:
                                future.completeExceptionally(new ConflictError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, V1ErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new WhopApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new WhopApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new WhopApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
