/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.plans.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PostPlanCreatedPayloadType {
    public static final PostPlanCreatedPayloadType PLAN_CREATED =
            new PostPlanCreatedPayloadType(Value.PLAN_CREATED, "plan.created");

    private final Value value;

    private final String string;

    PostPlanCreatedPayloadType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PostPlanCreatedPayloadType
                        && this.string.equals(((PostPlanCreatedPayloadType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PLAN_CREATED:
                return visitor.visitPlanCreated();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PostPlanCreatedPayloadType valueOf(String value) {
        switch (value) {
            case "plan.created":
                return PLAN_CREATED;
            default:
                return new PostPlanCreatedPayloadType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PLAN_CREATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPlanCreated();

        T visitUnknown(String unknownType);
    }
}
