/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.exports.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CreateExportsRequestResource {
    public static final CreateExportsRequestResource RECEIPTS =
            new CreateExportsRequestResource(Value.RECEIPTS, "receipts");

    public static final CreateExportsRequestResource AD_GROUPS =
            new CreateExportsRequestResource(Value.AD_GROUPS, "ad_groups");

    public static final CreateExportsRequestResource MEMBERS =
            new CreateExportsRequestResource(Value.MEMBERS, "members");

    public static final CreateExportsRequestResource PEOPLE = new CreateExportsRequestResource(Value.PEOPLE, "people");

    public static final CreateExportsRequestResource TEAM_MEMBERS =
            new CreateExportsRequestResource(Value.TEAM_MEMBERS, "team_members");

    public static final CreateExportsRequestResource PROMO_CODES =
            new CreateExportsRequestResource(Value.PROMO_CODES, "promo_codes");

    public static final CreateExportsRequestResource CARD_TRANSACTIONS =
            new CreateExportsRequestResource(Value.CARD_TRANSACTIONS, "card_transactions");

    public static final CreateExportsRequestResource PAYOUTS =
            new CreateExportsRequestResource(Value.PAYOUTS, "payouts");

    public static final CreateExportsRequestResource FINANCIAL_ACTIVITY =
            new CreateExportsRequestResource(Value.FINANCIAL_ACTIVITY, "financial-activity");

    public static final CreateExportsRequestResource CONTENT_REWARDS_SUBMISSIONS =
            new CreateExportsRequestResource(Value.CONTENT_REWARDS_SUBMISSIONS, "content_rewards_submissions");

    public static final CreateExportsRequestResource LEADS = new CreateExportsRequestResource(Value.LEADS, "leads");

    public static final CreateExportsRequestResource TRACKING_LINKS =
            new CreateExportsRequestResource(Value.TRACKING_LINKS, "tracking_links");

    public static final CreateExportsRequestResource AUDIENCES =
            new CreateExportsRequestResource(Value.AUDIENCES, "audiences");

    public static final CreateExportsRequestResource BOUNTY_SUBMISSIONS =
            new CreateExportsRequestResource(Value.BOUNTY_SUBMISSIONS, "bounty_submissions");

    public static final CreateExportsRequestResource SHIPMENTS =
            new CreateExportsRequestResource(Value.SHIPMENTS, "shipments");

    public static final CreateExportsRequestResource ENTRIES =
            new CreateExportsRequestResource(Value.ENTRIES, "entries");

    public static final CreateExportsRequestResource MEMBERSHIPS =
            new CreateExportsRequestResource(Value.MEMBERSHIPS, "memberships");

    public static final CreateExportsRequestResource TRANSFERS =
            new CreateExportsRequestResource(Value.TRANSFERS, "transfers");

    public static final CreateExportsRequestResource CHILD_COMPANIES =
            new CreateExportsRequestResource(Value.CHILD_COMPANIES, "child_companies");

    public static final CreateExportsRequestResource CHECKOUT_CONFIGURATIONS =
            new CreateExportsRequestResource(Value.CHECKOUT_CONFIGURATIONS, "checkout_configurations");

    public static final CreateExportsRequestResource PAYOUT_METHODS =
            new CreateExportsRequestResource(Value.PAYOUT_METHODS, "payout_methods");

    public static final CreateExportsRequestResource CANCELATION_REASONS =
            new CreateExportsRequestResource(Value.CANCELATION_REASONS, "cancelation_reasons");

    public static final CreateExportsRequestResource BOUNTIES =
            new CreateExportsRequestResource(Value.BOUNTIES, "bounties");

    public static final CreateExportsRequestResource UNCLAIMED_MEMBERSHIPS =
            new CreateExportsRequestResource(Value.UNCLAIMED_MEMBERSHIPS, "unclaimed_memberships");

    public static final CreateExportsRequestResource INVOICES =
            new CreateExportsRequestResource(Value.INVOICES, "invoices");

    public static final CreateExportsRequestResource DISPUTES =
            new CreateExportsRequestResource(Value.DISPUTES, "disputes");

    public static final CreateExportsRequestResource WEBHOOKS =
            new CreateExportsRequestResource(Value.WEBHOOKS, "webhooks");

    public static final CreateExportsRequestResource RESOLUTION_CENTER_CASES =
            new CreateExportsRequestResource(Value.RESOLUTION_CENTER_CASES, "resolution_center_cases");

    public static final CreateExportsRequestResource PLANS = new CreateExportsRequestResource(Value.PLANS, "plans");

    public static final CreateExportsRequestResource RESOLUTIONS =
            new CreateExportsRequestResource(Value.RESOLUTIONS, "resolutions");

    public static final CreateExportsRequestResource PRODUCTS =
            new CreateExportsRequestResource(Value.PRODUCTS, "products");

    public static final CreateExportsRequestResource EVENTS = new CreateExportsRequestResource(Value.EVENTS, "events");

    public static final CreateExportsRequestResource APPS = new CreateExportsRequestResource(Value.APPS, "apps");

    public static final CreateExportsRequestResource SOCIAL_ACCOUNTS =
            new CreateExportsRequestResource(Value.SOCIAL_ACCOUNTS, "social_accounts");

    public static final CreateExportsRequestResource ADS = new CreateExportsRequestResource(Value.ADS, "ads");

    public static final CreateExportsRequestResource AD_CAMPAIGNS =
            new CreateExportsRequestResource(Value.AD_CAMPAIGNS, "ad_campaigns");

    private final Value value;

    private final String string;

    CreateExportsRequestResource(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CreateExportsRequestResource
                        && this.string.equals(((CreateExportsRequestResource) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case RECEIPTS:
                return visitor.visitReceipts();
            case AD_GROUPS:
                return visitor.visitAdGroups();
            case MEMBERS:
                return visitor.visitMembers();
            case PEOPLE:
                return visitor.visitPeople();
            case TEAM_MEMBERS:
                return visitor.visitTeamMembers();
            case PROMO_CODES:
                return visitor.visitPromoCodes();
            case CARD_TRANSACTIONS:
                return visitor.visitCardTransactions();
            case PAYOUTS:
                return visitor.visitPayouts();
            case FINANCIAL_ACTIVITY:
                return visitor.visitFinancialActivity();
            case CONTENT_REWARDS_SUBMISSIONS:
                return visitor.visitContentRewardsSubmissions();
            case LEADS:
                return visitor.visitLeads();
            case TRACKING_LINKS:
                return visitor.visitTrackingLinks();
            case AUDIENCES:
                return visitor.visitAudiences();
            case BOUNTY_SUBMISSIONS:
                return visitor.visitBountySubmissions();
            case SHIPMENTS:
                return visitor.visitShipments();
            case ENTRIES:
                return visitor.visitEntries();
            case MEMBERSHIPS:
                return visitor.visitMemberships();
            case TRANSFERS:
                return visitor.visitTransfers();
            case CHILD_COMPANIES:
                return visitor.visitChildCompanies();
            case CHECKOUT_CONFIGURATIONS:
                return visitor.visitCheckoutConfigurations();
            case PAYOUT_METHODS:
                return visitor.visitPayoutMethods();
            case CANCELATION_REASONS:
                return visitor.visitCancelationReasons();
            case BOUNTIES:
                return visitor.visitBounties();
            case UNCLAIMED_MEMBERSHIPS:
                return visitor.visitUnclaimedMemberships();
            case INVOICES:
                return visitor.visitInvoices();
            case DISPUTES:
                return visitor.visitDisputes();
            case WEBHOOKS:
                return visitor.visitWebhooks();
            case RESOLUTION_CENTER_CASES:
                return visitor.visitResolutionCenterCases();
            case PLANS:
                return visitor.visitPlans();
            case RESOLUTIONS:
                return visitor.visitResolutions();
            case PRODUCTS:
                return visitor.visitProducts();
            case EVENTS:
                return visitor.visitEvents();
            case APPS:
                return visitor.visitApps();
            case SOCIAL_ACCOUNTS:
                return visitor.visitSocialAccounts();
            case ADS:
                return visitor.visitAds();
            case AD_CAMPAIGNS:
                return visitor.visitAdCampaigns();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CreateExportsRequestResource valueOf(String value) {
        switch (value) {
            case "receipts":
                return RECEIPTS;
            case "ad_groups":
                return AD_GROUPS;
            case "members":
                return MEMBERS;
            case "people":
                return PEOPLE;
            case "team_members":
                return TEAM_MEMBERS;
            case "promo_codes":
                return PROMO_CODES;
            case "card_transactions":
                return CARD_TRANSACTIONS;
            case "payouts":
                return PAYOUTS;
            case "financial-activity":
                return FINANCIAL_ACTIVITY;
            case "content_rewards_submissions":
                return CONTENT_REWARDS_SUBMISSIONS;
            case "leads":
                return LEADS;
            case "tracking_links":
                return TRACKING_LINKS;
            case "audiences":
                return AUDIENCES;
            case "bounty_submissions":
                return BOUNTY_SUBMISSIONS;
            case "shipments":
                return SHIPMENTS;
            case "entries":
                return ENTRIES;
            case "memberships":
                return MEMBERSHIPS;
            case "transfers":
                return TRANSFERS;
            case "child_companies":
                return CHILD_COMPANIES;
            case "checkout_configurations":
                return CHECKOUT_CONFIGURATIONS;
            case "payout_methods":
                return PAYOUT_METHODS;
            case "cancelation_reasons":
                return CANCELATION_REASONS;
            case "bounties":
                return BOUNTIES;
            case "unclaimed_memberships":
                return UNCLAIMED_MEMBERSHIPS;
            case "invoices":
                return INVOICES;
            case "disputes":
                return DISPUTES;
            case "webhooks":
                return WEBHOOKS;
            case "resolution_center_cases":
                return RESOLUTION_CENTER_CASES;
            case "plans":
                return PLANS;
            case "resolutions":
                return RESOLUTIONS;
            case "products":
                return PRODUCTS;
            case "events":
                return EVENTS;
            case "apps":
                return APPS;
            case "social_accounts":
                return SOCIAL_ACCOUNTS;
            case "ads":
                return ADS;
            case "ad_campaigns":
                return AD_CAMPAIGNS;
            default:
                return new CreateExportsRequestResource(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        AD_CAMPAIGNS,

        AD_GROUPS,

        ADS,

        APPS,

        AUDIENCES,

        BOUNTIES,

        BOUNTY_SUBMISSIONS,

        CARD_TRANSACTIONS,

        CHECKOUT_CONFIGURATIONS,

        DISPUTES,

        EVENTS,

        FINANCIAL_ACTIVITY,

        MEMBERS,

        MEMBERSHIPS,

        PAYOUT_METHODS,

        PAYOUTS,

        PEOPLE,

        PLANS,

        PRODUCTS,

        RESOLUTION_CENTER_CASES,

        SHIPMENTS,

        SOCIAL_ACCOUNTS,

        TEAM_MEMBERS,

        TRANSFERS,

        WEBHOOKS,

        RECEIPTS,

        UNCLAIMED_MEMBERSHIPS,

        TRACKING_LINKS,

        PROMO_CODES,

        RESOLUTIONS,

        ENTRIES,

        LEADS,

        CONTENT_REWARDS_SUBMISSIONS,

        INVOICES,

        CANCELATION_REASONS,

        CHILD_COMPANIES,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAdCampaigns();

        T visitAdGroups();

        T visitAds();

        T visitApps();

        T visitAudiences();

        T visitBounties();

        T visitBountySubmissions();

        T visitCardTransactions();

        T visitCheckoutConfigurations();

        T visitDisputes();

        T visitEvents();

        T visitFinancialActivity();

        T visitMembers();

        T visitMemberships();

        T visitPayoutMethods();

        T visitPayouts();

        T visitPeople();

        T visitPlans();

        T visitProducts();

        T visitResolutionCenterCases();

        T visitShipments();

        T visitSocialAccounts();

        T visitTeamMembers();

        T visitTransfers();

        T visitWebhooks();

        T visitReceipts();

        T visitUnclaimedMemberships();

        T visitTrackingLinks();

        T visitPromoCodes();

        T visitResolutions();

        T visitEntries();

        T visitLeads();

        T visitContentRewardsSubmissions();

        T visitInvoices();

        T visitCancelationReasons();

        T visitChildCompanies();

        T visitUnknown(String unknownType);
    }
}
