/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.apps.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.ObjectMappers;
import com.whop.api.resources.apps.types.ListAppsRequestAppType;
import com.whop.api.resources.apps.types.ListAppsRequestDirection;
import com.whop.api.resources.apps.types.ListAppsRequestOrder;
import com.whop.api.resources.apps.types.ListAppsRequestViewType;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListAppsRequest.Builder.class)
public final class ListAppsRequest {
    private final Optional<String> accountId;

    private final Optional<ListAppsRequestAppType> appType;

    private final Optional<ListAppsRequestViewType> viewType;

    private final Optional<Boolean> verifiedAppsOnly;

    private final Optional<String> query;

    private final Optional<ListAppsRequestOrder> order;

    private final Optional<ListAppsRequestDirection> direction;

    private final Optional<Integer> first;

    private final Optional<String> after;

    private final Optional<Integer> last;

    private final Optional<String> before;

    private final Map<String, Object> additionalProperties;

    private ListAppsRequest(
            Optional<String> accountId,
            Optional<ListAppsRequestAppType> appType,
            Optional<ListAppsRequestViewType> viewType,
            Optional<Boolean> verifiedAppsOnly,
            Optional<String> query,
            Optional<ListAppsRequestOrder> order,
            Optional<ListAppsRequestDirection> direction,
            Optional<Integer> first,
            Optional<String> after,
            Optional<Integer> last,
            Optional<String> before,
            Map<String, Object> additionalProperties) {
        this.accountId = accountId;
        this.appType = appType;
        this.viewType = viewType;
        this.verifiedAppsOnly = verifiedAppsOnly;
        this.query = query;
        this.order = order;
        this.direction = direction;
        this.first = first;
        this.after = after;
        this.last = last;
        this.before = before;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Only return apps created by this account (<code>biz_</code> tag). With developer access to the account this includes its unlisted and hidden apps.
     */
    @JsonProperty("account_id")
    public Optional<String> getAccountId() {
        return accountId;
    }

    /**
     * @return Filter apps by the type of end-user they are built for. Apps of type <code>website</code> are left out unless you ask for them by name.
     */
    @JsonProperty("app_type")
    public Optional<ListAppsRequestAppType> getAppType() {
        return appType;
    }

    /**
     * @return Only return apps supporting this view type, such as <code>dashboard</code> or <code>hub</code>.
     */
    @JsonProperty("view_type")
    public Optional<ListAppsRequestViewType> getViewType() {
        return viewType;
    }

    /**
     * @return Whether to only return apps verified by Whop. Verified website templates — websites with a published web build — are included, even though websites are otherwise left out of app lists.
     */
    @JsonProperty("verified_apps_only")
    public Optional<Boolean> getVerifiedAppsOnly() {
        return verifiedAppsOnly;
    }

    /**
     * @return A search string matched against app names.
     */
    @JsonProperty("query")
    public Optional<String> getQuery() {
        return query;
    }

    /**
     * @return The field to sort apps by. Defaults to discoverable_at, showing the most recently published apps first. <code>template_usage</code> ranks Whop-verified apps first, then apps with a banner image, then by how many apps were created from each app as a template.
     */
    @JsonProperty("order")
    public Optional<ListAppsRequestOrder> getOrder() {
        return order;
    }

    /**
     * @return Sort direction.
     */
    @JsonProperty("direction")
    public Optional<ListAppsRequestDirection> getDirection() {
        return direction;
    }

    /**
     * @return The number of apps to return (default 20, max 100).
     */
    @JsonProperty("first")
    public Optional<Integer> getFirst() {
        return first;
    }

    /**
     * @return A cursor; returns apps after this position.
     */
    @JsonProperty("after")
    public Optional<String> getAfter() {
        return after;
    }

    /**
     * @return The number of apps to return from the end of the range.
     */
    @JsonProperty("last")
    public Optional<Integer> getLast() {
        return last;
    }

    /**
     * @return A cursor; returns apps before this position.
     */
    @JsonProperty("before")
    public Optional<String> getBefore() {
        return before;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListAppsRequest && equalTo((ListAppsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListAppsRequest other) {
        return accountId.equals(other.accountId)
                && appType.equals(other.appType)
                && viewType.equals(other.viewType)
                && verifiedAppsOnly.equals(other.verifiedAppsOnly)
                && query.equals(other.query)
                && order.equals(other.order)
                && direction.equals(other.direction)
                && first.equals(other.first)
                && after.equals(other.after)
                && last.equals(other.last)
                && before.equals(other.before);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.accountId,
                this.appType,
                this.viewType,
                this.verifiedAppsOnly,
                this.query,
                this.order,
                this.direction,
                this.first,
                this.after,
                this.last,
                this.before);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> accountId = Optional.empty();

        private Optional<ListAppsRequestAppType> appType = Optional.empty();

        private Optional<ListAppsRequestViewType> viewType = Optional.empty();

        private Optional<Boolean> verifiedAppsOnly = Optional.empty();

        private Optional<String> query = Optional.empty();

        private Optional<ListAppsRequestOrder> order = Optional.empty();

        private Optional<ListAppsRequestDirection> direction = Optional.empty();

        private Optional<Integer> first = Optional.empty();

        private Optional<String> after = Optional.empty();

        private Optional<Integer> last = Optional.empty();

        private Optional<String> before = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListAppsRequest other) {
            accountId(other.getAccountId());
            appType(other.getAppType());
            viewType(other.getViewType());
            verifiedAppsOnly(other.getVerifiedAppsOnly());
            query(other.getQuery());
            order(other.getOrder());
            direction(other.getDirection());
            first(other.getFirst());
            after(other.getAfter());
            last(other.getLast());
            before(other.getBefore());
            return this;
        }

        /**
         * <p>Only return apps created by this account (<code>biz_</code> tag). With developer access to the account this includes its unlisted and hidden apps.</p>
         */
        @JsonSetter(value = "account_id", nulls = Nulls.SKIP)
        public Builder accountId(Optional<String> accountId) {
            this.accountId = accountId;
            return this;
        }

        public Builder accountId(String accountId) {
            this.accountId = Optional.ofNullable(accountId);
            return this;
        }

        /**
         * <p>Filter apps by the type of end-user they are built for. Apps of type <code>website</code> are left out unless you ask for them by name.</p>
         */
        @JsonSetter(value = "app_type", nulls = Nulls.SKIP)
        public Builder appType(Optional<ListAppsRequestAppType> appType) {
            this.appType = appType;
            return this;
        }

        public Builder appType(ListAppsRequestAppType appType) {
            this.appType = Optional.ofNullable(appType);
            return this;
        }

        /**
         * <p>Only return apps supporting this view type, such as <code>dashboard</code> or <code>hub</code>.</p>
         */
        @JsonSetter(value = "view_type", nulls = Nulls.SKIP)
        public Builder viewType(Optional<ListAppsRequestViewType> viewType) {
            this.viewType = viewType;
            return this;
        }

        public Builder viewType(ListAppsRequestViewType viewType) {
            this.viewType = Optional.ofNullable(viewType);
            return this;
        }

        /**
         * <p>Whether to only return apps verified by Whop. Verified website templates — websites with a published web build — are included, even though websites are otherwise left out of app lists.</p>
         */
        @JsonSetter(value = "verified_apps_only", nulls = Nulls.SKIP)
        public Builder verifiedAppsOnly(Optional<Boolean> verifiedAppsOnly) {
            this.verifiedAppsOnly = verifiedAppsOnly;
            return this;
        }

        public Builder verifiedAppsOnly(Boolean verifiedAppsOnly) {
            this.verifiedAppsOnly = Optional.ofNullable(verifiedAppsOnly);
            return this;
        }

        /**
         * <p>A search string matched against app names.</p>
         */
        @JsonSetter(value = "query", nulls = Nulls.SKIP)
        public Builder query(Optional<String> query) {
            this.query = query;
            return this;
        }

        public Builder query(String query) {
            this.query = Optional.ofNullable(query);
            return this;
        }

        /**
         * <p>The field to sort apps by. Defaults to discoverable_at, showing the most recently published apps first. <code>template_usage</code> ranks Whop-verified apps first, then apps with a banner image, then by how many apps were created from each app as a template.</p>
         */
        @JsonSetter(value = "order", nulls = Nulls.SKIP)
        public Builder order(Optional<ListAppsRequestOrder> order) {
            this.order = order;
            return this;
        }

        public Builder order(ListAppsRequestOrder order) {
            this.order = Optional.ofNullable(order);
            return this;
        }

        /**
         * <p>Sort direction.</p>
         */
        @JsonSetter(value = "direction", nulls = Nulls.SKIP)
        public Builder direction(Optional<ListAppsRequestDirection> direction) {
            this.direction = direction;
            return this;
        }

        public Builder direction(ListAppsRequestDirection direction) {
            this.direction = Optional.ofNullable(direction);
            return this;
        }

        /**
         * <p>The number of apps to return (default 20, max 100).</p>
         */
        @JsonSetter(value = "first", nulls = Nulls.SKIP)
        public Builder first(Optional<Integer> first) {
            this.first = first;
            return this;
        }

        public Builder first(Integer first) {
            this.first = Optional.ofNullable(first);
            return this;
        }

        /**
         * <p>A cursor; returns apps after this position.</p>
         */
        @JsonSetter(value = "after", nulls = Nulls.SKIP)
        public Builder after(Optional<String> after) {
            this.after = after;
            return this;
        }

        public Builder after(String after) {
            this.after = Optional.ofNullable(after);
            return this;
        }

        /**
         * <p>The number of apps to return from the end of the range.</p>
         */
        @JsonSetter(value = "last", nulls = Nulls.SKIP)
        public Builder last(Optional<Integer> last) {
            this.last = last;
            return this;
        }

        public Builder last(Integer last) {
            this.last = Optional.ofNullable(last);
            return this;
        }

        /**
         * <p>A cursor; returns apps before this position.</p>
         */
        @JsonSetter(value = "before", nulls = Nulls.SKIP)
        public Builder before(Optional<String> before) {
            this.before = before;
            return this;
        }

        public Builder before(String before) {
            this.before = Optional.ofNullable(before);
            return this;
        }

        public ListAppsRequest build() {
            return new ListAppsRequest(
                    accountId,
                    appType,
                    viewType,
                    verifiedAppsOnly,
                    query,
                    order,
                    direction,
                    first,
                    after,
                    last,
                    before,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
