/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.exports;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.whop.api.core.ClientOptions;
import com.whop.api.core.MediaTypes;
import com.whop.api.core.ObjectMappers;
import com.whop.api.core.QueryStringMapper;
import com.whop.api.core.RequestOptions;
import com.whop.api.core.WhopApiApiException;
import com.whop.api.core.WhopApiException;
import com.whop.api.core.WhopApiHttpResponse;
import com.whop.api.errors.BadRequestError;
import com.whop.api.errors.ConflictError;
import com.whop.api.errors.ForbiddenError;
import com.whop.api.errors.NotFoundError;
import com.whop.api.errors.UnauthorizedError;
import com.whop.api.resources.exports.requests.CreateExportsRequest;
import com.whop.api.resources.exports.requests.ListExportsRequest;
import com.whop.api.resources.exports.requests.RetrieveExportsRequest;
import com.whop.api.resources.exports.types.ListExportsResponse;
import com.whop.api.types.Export;
import com.whop.api.types.V1ErrorResponse;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawExportsClient {
    protected final ClientOptions clientOptions;

    public RawExportsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Lists the exports requested for an account, newest first. Only exports of resources the credential is allowed to export are returned.
     */
    public WhopApiHttpResponse<ListExportsResponse> list() {
        return list(ListExportsRequest.builder().build());
    }

    /**
     * Lists the exports requested for an account, newest first. Only exports of resources the credential is allowed to export are returned.
     */
    public WhopApiHttpResponse<ListExportsResponse> list(RequestOptions requestOptions) {
        return list(ListExportsRequest.builder().build(), requestOptions);
    }

    /**
     * Lists the exports requested for an account, newest first. Only exports of resources the credential is allowed to export are returned.
     */
    public WhopApiHttpResponse<ListExportsResponse> list(ListExportsRequest request) {
        return list(request, null);
    }

    /**
     * Lists the exports requested for an account, newest first. Only exports of resources the credential is allowed to export are returned.
     */
    public WhopApiHttpResponse<ListExportsResponse> list(ListExportsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("exports");
        if (request.getAccountId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "account_id", request.getAccountId().get(), false);
        }
        if (request.getResource().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "resource", request.getResource().get(), false);
        }
        if (request.getStatus().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "status", request.getStatus().get(), false);
        }
        if (request.getCreatedAfter().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "created_after", request.getCreatedAfter().get(), false);
        }
        if (request.getCreatedBefore().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "created_before", request.getCreatedBefore().get(), false);
        }
        if (request.getOrder().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "order", request.getOrder().get(), false);
        }
        if (request.getDirection().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "direction", request.getDirection().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new WhopApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListExportsResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new WhopApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new WhopApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Starts an asynchronous CSV export of a resource for an account. Returns the export in <code>pending</code>; poll <code>GET /exports/{id}</code> until <code>download_url</code> is set.
     */
    public WhopApiHttpResponse<Export> create(CreateExportsRequest request) {
        return create(request, null);
    }

    /**
     * Starts an asynchronous CSV export of a resource for an account. Returns the export in <code>pending</code>; poll <code>GET /exports/{id}</code> until <code>download_url</code> is set.
     */
    public WhopApiHttpResponse<Export> create(CreateExportsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("exports");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new WhopApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new WhopApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Export.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 409:
                        throw new ConflictError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, V1ErrorResponse.class),
                                response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new WhopApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new WhopApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Fetches an export's status and, once complete, its download link.
     */
    public WhopApiHttpResponse<Export> retrieve(String id) {
        return retrieve(id, RetrieveExportsRequest.builder().build());
    }

    /**
     * Fetches an export's status and, once complete, its download link.
     */
    public WhopApiHttpResponse<Export> retrieve(String id, RequestOptions requestOptions) {
        return retrieve(id, RetrieveExportsRequest.builder().build(), requestOptions);
    }

    /**
     * Fetches an export's status and, once complete, its download link.
     */
    public WhopApiHttpResponse<Export> retrieve(String id, RetrieveExportsRequest request) {
        return retrieve(id, request, null);
    }

    /**
     * Fetches an export's status and, once complete, its download link.
     */
    public WhopApiHttpResponse<Export> retrieve(
            String id, RetrieveExportsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("exports")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new WhopApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Export.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new WhopApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new WhopApiException("Network error executing HTTP request", e);
        }
    }
}
