/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.socialaccounts.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ConnectSocialAccountsRequestScopesItem {
    public static final ConnectSocialAccountsRequestScopesItem ADVERTISE =
            new ConnectSocialAccountsRequestScopesItem(Value.ADVERTISE, "advertise");

    private final Value value;

    private final String string;

    ConnectSocialAccountsRequestScopesItem(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ConnectSocialAccountsRequestScopesItem
                        && this.string.equals(((ConnectSocialAccountsRequestScopesItem) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ADVERTISE:
                return visitor.visitAdvertise();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ConnectSocialAccountsRequestScopesItem valueOf(String value) {
        switch (value) {
            case "advertise":
                return ADVERTISE;
            default:
                return new ConnectSocialAccountsRequestScopesItem(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ADVERTISE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAdvertise();

        T visitUnknown(String unknownType);
    }
}
