/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.whop.api.resources.forumposts.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.whop.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListForumPostsRequest.Builder.class)
public final class ListForumPostsRequest {
    private final Optional<String> after;

    private final Optional<String> before;

    private final Optional<Integer> first;

    private final Optional<Integer> last;

    private final String experienceId;

    private final Optional<Boolean> includeBountyAnchors;

    private final Optional<String> parentId;

    private final Optional<Boolean> pinned;

    private final Map<String, Object> additionalProperties;

    private ListForumPostsRequest(
            Optional<String> after,
            Optional<String> before,
            Optional<Integer> first,
            Optional<Integer> last,
            String experienceId,
            Optional<Boolean> includeBountyAnchors,
            Optional<String> parentId,
            Optional<Boolean> pinned,
            Map<String, Object> additionalProperties) {
        this.after = after;
        this.before = before;
        this.first = first;
        this.last = last;
        this.experienceId = experienceId;
        this.includeBountyAnchors = includeBountyAnchors;
        this.parentId = parentId;
        this.pinned = pinned;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return <p>the elements in the list that come after the specified cursor.</p>
     */
    @JsonProperty("after")
    public Optional<String> getAfter() {
        return after;
    }

    /**
     * @return <p>the elements in the list that come before the specified cursor.</p>
     */
    @JsonProperty("before")
    public Optional<String> getBefore() {
        return before;
    }

    /**
     * @return <p>the first <em>n</em> elements from the list.</p>
     */
    @JsonProperty("first")
    public Optional<Integer> getFirst() {
        return first;
    }

    /**
     * @return <p>the last <em>n</em> elements from the list.</p>
     */
    @JsonProperty("last")
    public Optional<Integer> getLast() {
        return last;
    }

    /**
     * @return The unique identifier of the experience to list forum posts for.
     */
    @JsonProperty("experience_id")
    public String getExperienceId() {
        return experienceId;
    }

    /**
     * @return Whether to include top-level bounty discussion anchors as rich forum items.
     */
    @JsonProperty("include_bounty_anchors")
    public Optional<Boolean> getIncludeBountyAnchors() {
        return includeBountyAnchors;
    }

    /**
     * @return The unique identifier of a parent post to list comments for. When set, returns replies to that post.
     */
    @JsonProperty("parent_id")
    public Optional<String> getParentId() {
        return parentId;
    }

    /**
     * @return Whether to filter for only pinned posts. Set to true to return only pinned posts.
     */
    @JsonProperty("pinned")
    public Optional<Boolean> getPinned() {
        return pinned;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListForumPostsRequest && equalTo((ListForumPostsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListForumPostsRequest other) {
        return after.equals(other.after)
                && before.equals(other.before)
                && first.equals(other.first)
                && last.equals(other.last)
                && experienceId.equals(other.experienceId)
                && includeBountyAnchors.equals(other.includeBountyAnchors)
                && parentId.equals(other.parentId)
                && pinned.equals(other.pinned);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.after,
                this.before,
                this.first,
                this.last,
                this.experienceId,
                this.includeBountyAnchors,
                this.parentId,
                this.pinned);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ExperienceIdStage builder() {
        return new Builder();
    }

    public interface ExperienceIdStage {
        /**
         * <p>The unique identifier of the experience to list forum posts for.</p>
         */
        _FinalStage experienceId(@NotNull String experienceId);

        Builder from(ListForumPostsRequest other);
    }

    public interface _FinalStage {
        ListForumPostsRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Returns the elements in the list that come after the specified cursor.</p>
         */
        _FinalStage after(Optional<String> after);

        _FinalStage after(String after);

        /**
         * <p>Returns the elements in the list that come before the specified cursor.</p>
         */
        _FinalStage before(Optional<String> before);

        _FinalStage before(String before);

        /**
         * <p>Returns the first <em>n</em> elements from the list.</p>
         */
        _FinalStage first(Optional<Integer> first);

        _FinalStage first(Integer first);

        /**
         * <p>Returns the last <em>n</em> elements from the list.</p>
         */
        _FinalStage last(Optional<Integer> last);

        _FinalStage last(Integer last);

        /**
         * <p>Whether to include top-level bounty discussion anchors as rich forum items.</p>
         */
        _FinalStage includeBountyAnchors(Optional<Boolean> includeBountyAnchors);

        _FinalStage includeBountyAnchors(Boolean includeBountyAnchors);

        /**
         * <p>The unique identifier of a parent post to list comments for. When set, returns replies to that post.</p>
         */
        _FinalStage parentId(Optional<String> parentId);

        _FinalStage parentId(String parentId);

        /**
         * <p>Whether to filter for only pinned posts. Set to true to return only pinned posts.</p>
         */
        _FinalStage pinned(Optional<Boolean> pinned);

        _FinalStage pinned(Boolean pinned);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ExperienceIdStage, _FinalStage {
        private String experienceId;

        private Optional<Boolean> pinned = Optional.empty();

        private Optional<String> parentId = Optional.empty();

        private Optional<Boolean> includeBountyAnchors = Optional.empty();

        private Optional<Integer> last = Optional.empty();

        private Optional<Integer> first = Optional.empty();

        private Optional<String> before = Optional.empty();

        private Optional<String> after = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ListForumPostsRequest other) {
            after(other.getAfter());
            before(other.getBefore());
            first(other.getFirst());
            last(other.getLast());
            experienceId(other.getExperienceId());
            includeBountyAnchors(other.getIncludeBountyAnchors());
            parentId(other.getParentId());
            pinned(other.getPinned());
            return this;
        }

        /**
         * <p>The unique identifier of the experience to list forum posts for.</p>
         * <p>The unique identifier of the experience to list forum posts for.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("experience_id")
        public _FinalStage experienceId(@NotNull String experienceId) {
            this.experienceId = Objects.requireNonNull(experienceId, "experienceId must not be null");
            return this;
        }

        /**
         * <p>Whether to filter for only pinned posts. Set to true to return only pinned posts.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage pinned(Boolean pinned) {
            this.pinned = Optional.ofNullable(pinned);
            return this;
        }

        /**
         * <p>Whether to filter for only pinned posts. Set to true to return only pinned posts.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "pinned", nulls = Nulls.SKIP)
        public _FinalStage pinned(Optional<Boolean> pinned) {
            this.pinned = pinned;
            return this;
        }

        /**
         * <p>The unique identifier of a parent post to list comments for. When set, returns replies to that post.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage parentId(String parentId) {
            this.parentId = Optional.ofNullable(parentId);
            return this;
        }

        /**
         * <p>The unique identifier of a parent post to list comments for. When set, returns replies to that post.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "parent_id", nulls = Nulls.SKIP)
        public _FinalStage parentId(Optional<String> parentId) {
            this.parentId = parentId;
            return this;
        }

        /**
         * <p>Whether to include top-level bounty discussion anchors as rich forum items.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage includeBountyAnchors(Boolean includeBountyAnchors) {
            this.includeBountyAnchors = Optional.ofNullable(includeBountyAnchors);
            return this;
        }

        /**
         * <p>Whether to include top-level bounty discussion anchors as rich forum items.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "include_bounty_anchors", nulls = Nulls.SKIP)
        public _FinalStage includeBountyAnchors(Optional<Boolean> includeBountyAnchors) {
            this.includeBountyAnchors = includeBountyAnchors;
            return this;
        }

        /**
         * <p>Returns the last <em>n</em> elements from the list.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage last(Integer last) {
            this.last = Optional.ofNullable(last);
            return this;
        }

        /**
         * <p>Returns the last <em>n</em> elements from the list.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "last", nulls = Nulls.SKIP)
        public _FinalStage last(Optional<Integer> last) {
            this.last = last;
            return this;
        }

        /**
         * <p>Returns the first <em>n</em> elements from the list.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage first(Integer first) {
            this.first = Optional.ofNullable(first);
            return this;
        }

        /**
         * <p>Returns the first <em>n</em> elements from the list.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "first", nulls = Nulls.SKIP)
        public _FinalStage first(Optional<Integer> first) {
            this.first = first;
            return this;
        }

        /**
         * <p>Returns the elements in the list that come before the specified cursor.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage before(String before) {
            this.before = Optional.ofNullable(before);
            return this;
        }

        /**
         * <p>Returns the elements in the list that come before the specified cursor.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "before", nulls = Nulls.SKIP)
        public _FinalStage before(Optional<String> before) {
            this.before = before;
            return this;
        }

        /**
         * <p>Returns the elements in the list that come after the specified cursor.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage after(String after) {
            this.after = Optional.ofNullable(after);
            return this;
        }

        /**
         * <p>Returns the elements in the list that come after the specified cursor.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "after", nulls = Nulls.SKIP)
        public _FinalStage after(Optional<String> after) {
            this.after = after;
            return this;
        }

        @java.lang.Override
        public ListForumPostsRequest build() {
            return new ListForumPostsRequest(
                    after,
                    before,
                    first,
                    last,
                    experienceId,
                    includeBountyAnchors,
                    parentId,
                    pinned,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
